### PR TITLE
🎉 🎨 ✨ Remove middleware/index.js

### LINKED ISSUE #4172: Refactor Middleware + Express Apps
This is a follow up to #1961 and #4069.

The Ghost middlewares are currently a complete mess. We have two apps (blog and admin) and some middlewares for each in `middleware/index.js` and others in `middleware/middleware.js`. Some of the middlewares are shared between both apps, others really only make sense on one. The separation of blog and admin into their own express apps was a good start to get things cleaned up. 

As part of this issue the following tasks should be considered:

- [x] Find a new home for each middleware
- [ ] Refactor /ghost/api into its own express app
- [ ] Clean up the set up process of Ghost (how the express app gets initialised)
- [x] Improve test coverage for middleware

I'll be working on all of these.

### LINKED ISSUE #6948: Error when fetching non-existent asset as first request after restart
If you start Ghost, and the first thing that you try to request is a non existent asset (e.g. something like `/content/images/i-dont-exist.jpg`) you will get an error:

```
Error: Cannot find module 'hbs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at new View (/Users/hannah/Ghost/Ghost/node_modules/express/lib/view.js:78:30)
    at EventEmitter.render (/Users/hannah/Ghost/Ghost/node_modules/express/lib/application.js:569:12)
    at ServerResponse.render (/Users/hannah/Ghost/Ghost/node_modules/express/lib/response.js:961:7)
    at renderErrorInt (/Users/hannah/Ghost/Ghost/core/server/errors/index.js:323:36)
   ...
```

See [this gist](https://gist.github.com/ErisDS/0ce509aa1fd07f5c1fa12079b200e1d8) for the full stack trace.

In order to see this error you will need to be on a theme which doesn't call navigation in the `error.hbs` template, or where #6928 (which fixes that bug) is already merged.

This error occurs regardless of whether #6938 (moving hbs stuff around) is merged, which is expected because there is no functional change - just noting it here as a related change.

### Steps to Reproduce

1. Make sure your blog is running Casper
2. Start (or restart) Ghost
3. Don't request any other pages of Ghost yet!!
4. Navigate straight to `http://localhost:2368/content/images/i-dont-exist.jpg` (or another image that doesn't exist for your blog
5. 💥 

This really should be rendering an error page!

### Technical details:

* Ghost Version: 0.8.0 / latest master

### PR DESCRIPTION
**Pull request by ErisDS**
closes #4172, closes #6948

NOTE: This includes #7542 and some of #7484 

This is the big picture of what I have been trying to achieve with refactoring our middleware and getting rid of middleware/index.js

This is missing a lot of cleanup work, for example:
- [ ] it doesn't have the 💄 tasks from https://github.com/TryGhost/Ghost/pull/7484/commits
- [ ] it doesn't have decide-is-admin removal (part 2) yet
- [ ] api app.js is still a huge file, it needs splitting into app.js and route.js
- [ ] asset handling hasn't been improved yet & needs more error handling
- [ ] there's still a random helper loading in server/app.js
- [ ] which is a symptom of the fact I still need to tackle how themes fit into this
- [ ] the middleware folder could probably be reorganised a bit more?
- [ ] try to optimise loading times as shown by debug?
- [ ] consider if blog is the right name for the blog app
- [ ] consider where blog & admin should live, should they be internal apps?
- [ ] maybe move some custom logic from middleware/error-handler into GhostError
- [ ] test the private blogging filterPrivate routes functionality is still working as it uses req.url
- [ ] I'm sure there are more TODOs in the code 😁

### CODE REVIEW

File: core/server/middleware/error-handler.js [hunk 1]
```diff
@@ -4,9 +4,11 @@ var _ = require('lodash'),
     config = require('../config'),
     errors = require('../errors'),
     i18n = require('../i18n'),
-    _private = {};
+    _private = {},
+    errorHandler = {},
+    htmlStackExclusions = ['NotFoundError', 'DatabaseNotPopulatedError'];
 
-_private.parseStack = function (stack) {
+_private.parseStack = function parseStack(stack) {
```
Comment (kirrg001) [inline core/server/middleware/error-handler.js]: i have two questions:
1. any information to share what this function is doing?
2. can we put this function into the GhostError?

```
if (!err instanceof errors.NotFoundError && !err instanceof DatabaseNotPopulatedError)
  templateData.stack = err.getPrettyStack();
```

File: core/server/middleware/error-handler.js [hunk 2]
```diff
@@ -35,64 +37,30 @@ _private.parseStack = function (stack) {
...
     if (_.isArray(err)) {
         err = err[0];
     }
 
     if (!(err instanceof errors.GhostError)) {
-        err = new errors.GhostError({
-            err: err
-        });
+        // We need a special case for 404 errors
+        if (err.statusCode && err.statusCode === 404) {
```
Comment (kirrg001) [inline core/server/middleware/error-handler.js]: originally https://github.com/TryGhost/Ghost/pull/7542#discussion_r82830112
is see that you have changed it already.

How about putting the 404 check into the GhostError class?

File: core/server/middleware/error-handler.js [hunk 3]
```diff
@@ -103,15 +71,68 @@ module.exports = function errorHandler(err, req, res, next) {
...
+    // 405 Method Not Allowed
+    next(new errors.NotFoundError({message: i18n.t('errors.errors.resourceNotFound')}));
+};
+
+errorHandler.pageNotFound = function pageNotFound(req, res, next) {
+    next(new errors.NotFoundError({message: i18n.t('errors.errors.pageNotFound')}));
+};
+
+errorHandler.handleJSONResponse = function _handleJSONResponse(err, req, res, next) {
+    /*jshint unused:false */
```
Comment (kirrg001) [inline core/server/middleware/error-handler.js]: suggestion: `/*jshint unused:false*/ next`

File: core/server/middleware/error-handler.js [hunk 4]
```diff
@@ -103,15 +71,68 @@ module.exports = function errorHandler(err, req, res, next) {
...
+        }]
+    });
+};
+
+errorHandler.handleHTMLResponse = function handleHTMLResponse(err, req, res, next) {
+    /*jshint unused:false */
+    // Make sure the error can be served
+    err = _private.prepareError(err, req, res);
+
+    // @TODO reconsider this
```
Comment (kirrg001) [inline core/server/middleware/error-handler.js]: would be cool actually to not load available themes into config and rather ask a theme unit which knows all this stuff. then we could use this unit here. maybe we can extend the TODO a bit or add a task into theme audit issue?

File: core/server/middleware/error-handler.js [hunk 5]
```diff
@@ -103,15 +71,68 @@ module.exports = function errorHandler(err, req, res, next) {
...
+            message: err.message,
+            code: err.statusCode
+        };
+
+    if (!_.includes(htmlStackExclusions, err.errorType)) {
+        templateData.stack = _private.parseStack(err.stack);
     }
 
-    // jscs:disable
-    res.format({
```
Comment (kirrg001) [inline core/server/middleware/error-handler.js]: buuurrn

File: core/server/middleware/error-handler.js [hunk 6]
```diff
@@ -35,64 +37,30 @@ _private.parseStack = function (stack) {
...
 /**
- * @TODO: test uncaught exception (wrap into custom error!)
+ * Get an error ready to be shown the the user
+ *
  * @TODO: support multiple errors
  * @TODO: decouple req.err
  */
-module.exports = function errorHandler(err, req, res, next) {
+_private.prepareError = function prepareError(err, req, res) {
+    /*jshint unused:false */
```
Comment (kirrg001) [inline core/server/middleware/error-handler.js]: can be removed i think

File: core/server/middleware/error-handler.js [hunk 7]
```diff
@@ -103,15 +71,68 @@ module.exports = function errorHandler(err, req, res, next) {
...
+};
+
+errorHandler.pageNotFound = function pageNotFound(req, res, next) {
+    next(new errors.NotFoundError({message: i18n.t('errors.errors.pageNotFound')}));
+};
+
+errorHandler.handleJSONResponse = function _handleJSONResponse(err, req, res, next) {
+    /*jshint unused:false */
+    // Make sure the error can be served
+    err = _private.prepareError(err, req, res);
```
Comment (kirrg001) [inline core/server/middleware/error-handler.js]: suggestion:
Not a big fan of the function design here, that's why i would like to suggest this here:

```
_private.beforeResponse= function(err, req,res) {
   req.set..
   res....
};

_private.prepareError = function (done) {
    return function prepareError(err, req, res, next) {
          // ...
          done(err, req, res,next);
    });
};

errorHandler.handleJSONResponse = _private.prepareError(function _handleJSONResponse(err, req, res, next){
    _private.beforeResponse(err, req, res);
});

```

File: core/test/utils/assertions.js [hunk 8]
```diff
@@ -0,0 +1,19 @@
+var should = require('should'),
+    errorProps = ['message', 'errorType'];
+
+should.Assertion.add('JSONErrorObject', function () {
```
Comment (kirrg001) [inline core/test/utils/assertions.js]: cool 🇹🇭

File: core/server/middleware/check-ssl.js [hunk 9]
```diff
@@ -44,7 +44,7 @@ checkSSL = function checkSSL(req, res, next) {
                 forceAdminSSL: config.get('forceAdminSSL'),
                 configUrlSSL: config.get('urlSSL'),
                 configUrl: config.get('url'),
-                reqUrl: req.url
+                reqUrl: req.originalUrl || req.url
```
Comment (kirrg001) [inline core/server/middleware/check-ssl.js]: i saw this change a couple of times in the past. seems like this can be forgotten very easily. 
any idea how to prevent?

**Review by kirrg001 — CHANGES_REQUESTED** [review]
Looks all supi!
I've added some small comments.

I have two architecture question in my head:
1. should we move `blog` and `admin` to `apps`?
2. i am not sure about having `app.js` in `core/server/app.js`. Maybe it makes sense for now and later we put it to `/apps/bootstrap.js`?(or similar)

**Comment by ErisDS** [comment]
> 1. should we move blog and admin to apps?
Right now, I am not sure - I have that as a TODO in one of the commits, I've added it as a TODO to the list on this PR, whatever is left I will move to a new issue to track
2. i am not sure about having app.js in core/server/app.js. Maybe it makes sense for now and later we put it to /apps/bootstrap.js?(or similar)
Also not sure yet

I think these are both good questions with no clear answer right now, but that this is a step in the right direction and we can change all this again later if an answer becomes clear?

File: core/server/middleware/error-handler.js (hunk 4 above)
Comment (ErisDS) [inline core/server/middleware/error-handler.js]: Yes, this is what I meant by the TODO: "which is a symptom of the fact I still need to tackle how themes fit into this" - I need to do more work here definitely

File: core/server/middleware/error-handler.js (hunk 3 above)
Comment (ErisDS) [inline core/server/middleware/error-handler.js]: Sorry, what do you mean here ?

File: core/server/middleware/error-handler.js (hunk 1 above)
Comment (ErisDS) [inline core/server/middleware/error-handler.js]: For 1: Not really, but I will look it up and add a comment to the function
For 2: I have added a TODO for this of "maybe move some custom logic from middleware/error-handler into GhostError"  I am not 100% confident I understand that file yet 😁

Comment (kirrg001) [inline core/server/middleware/error-handler.js]: ok agree. maybe raise some questions in DM to me. 

but one change i would like to see: can we check error instances?
```if (!err instanceof errors.NotFoundError && !err instanceof DatabaseNotPopulatedError)```

File: core/server/middleware/check-ssl.js (hunk 9 above)
Comment (ErisDS) [inline core/server/middleware/check-ssl.js]: This is a good question. I think it is a bit weird how express works, and unfortunately we didn't really understand how it worked when we started out.

In uncapitalise I added an example, which is true for the old setup where only blogApp was mounted. With multiple mounted apps, more of the url lives in `baseUrl` instead of in `url`:

```
req.originalUrl = /blog/ghost/signin/?asdAD=asdAS
req.url = /ghost/signin/?asdAD=asdAS
req.baseUrl = /blog
req.path =  /ghost/signin/
```

I think, unfortunately, unless we always test properly we will always have issues in this area, just as we have constant regressions and bugs with subdirectories for the same reason.

File: core/server/middleware/error-handler.js (hunk 3 above)
Comment (kirrg001) [inline core/server/middleware/error-handler.js]: the jshint comment here is confusing, it refers to the next param or?
```_handleJSONResponse(err, req, res, /*jshint unused: false*/ next)```

File: core/server/middleware/error-handler.js (hunk 4 above)
Comment (kirrg001) [inline core/server/middleware/error-handler.js]: ok that was not obvious to me, thanks!

**Comment by kirrg001** [comment]
> I think these are both good questions with no clear answer right now, but that this is a step in the right direction and we can change all this again later if an answer becomes clear?

Totally!

File: core/server/middleware/check-ssl.js (hunk 9 above)
Comment (ErisDS) [inline core/server/middleware/check-ssl.js]: Just added another TODO to check the filterPrivateRoutes middleware in the private-blogging app because this is also using req.url and I'm not sure if the usage is correct.

File: core/server/middleware/error-handler.js (hunk 2 above)
Comment (kirrg001) [inline core/server/middleware/error-handler.js]: cool 👍

File: core/server/middleware/error-handler.js (hunk 1 above)
Comment (ErisDS) [inline core/server/middleware/error-handler.js]: Is that instead of https://github.com/TryGhost/Ghost/pull/7548/files/79e7eba9fb0c2d7dcc4b4afb48beafc952f4f693#diff-6b41d6f0ef148f7d202931a87d5c4130R118?

File: core/server/middleware/check-ssl.js (hunk 9 above)
Comment (kirrg001) [inline core/server/middleware/check-ssl.js]: yeah understand 👍

**Comment by ErisDS** [comment]
So, I did some research into the `parseStack` function. It outputs stacks that are broken into objects. The following handlebars code in `user-error.hbs` then outputs it so it looks "pretty" 

```
{{#each stack}}
<li>
  at
  {{#if function}}<em class="error-stack-function">{{function}}</em>{{/if}}
  <span class="error-stack-file">({{at}})</span>
</li>
{{/each}}
```

Here's what it looks like (A handlebars templating error):



Without this, a plain stack would look like:



I definitely think we need to revisit whether this is useful or necessary, however I need to move on to other things for a while. I've added some TODOs for error handling to the theme audit issue: https://github.com/TryGhost/Ghost/issues/7491

**Comment by ErisDS** [comment]
I've pushed an extra commit which makes some minor changes, not much though, most things I've just marked as TODOs as I need to do some other work for a bit :(

**Review by kirrg001 — APPROVED** [review]

**Comment by SeanHayes** [comment]
Does anyone know when this PR will make it into a release?

**Comment by ErisDS** [comment]
Not for some time - this is part of the [alpha](http://support.ghost.org/v1-0-alpha/) work to get us to [ghost 1.0](https://dev.ghost.org/lts/)

**Comment by bonesoul** [comment]
any status updates on this?
