### PR TITLE
No more CodeMirror

### LINKED ISSUE #4368: Drop CodeMirror from the Editor
With reference to the [Split Screen Editor Epic (#1294)](https://github.com/TryGhost/Ghost/issues/1294)

--- 

The Ghost editor undeniably needs some :heart:. No matter how you consider what the editor might look like in the future, there is one underlying problem - to ship improvements like spellcheck, we need to build a completely custom editor, that's an enormous undertaking, and it would detract from all the other features we want to ship :-1:.

That is, unless we drop formatting/syntax highlighting from the left side of the editor :boom: 

**yep**... I'm talking about dropping CodeMirror in favour of a plain textarea.

CodeMirror currently has two main jobs: 1) it formats/syntax highlights the markdown and 2) provides an API for interacting with the entered text. However, what it does under the bonnet is generate a completely custom representation of the document which is neither markdown or HTML. This breaks the [browser spellcheck](https://github.com/TryGhost/Ghost/issues/1240), doesn't work reliably [on mobile/touch](https://github.com/TryGhost/Ghost/issues/960) (which meant we had to remove it from mobile/touch devices), and the way it interprets markdown is quite different to our HTML conversion, which causes [weird](https://github.com/TryGhost/Ghost/issues/959) [bugs](https://github.com/TryGhost/Ghost/issues/1909) and adds complexity.

If we strip out CodeMirror, we will lose formatting, but what we get instead will be an editor with working **spellcheck**, working **mobile uploads** and significantly reduced complexity: because we only have two document representations - markdown and HTML, and we are in control of them both. This means we can focus on making the conversion between them better (i.e. adding advanced markdown features).

In the future, we'll be able to bring back formatting if we want it using contenteditable, but in the meantime we can more easily focus on the features we want to bring to the editor, the markdown we want to support, and creating our own way of modelling documents - because the editor is so significantly less complicated.

I've been working on a prototype testing out how to interact with selections in the textarea to make sure that image uploads will still work (on ALL devices) etc and to me this feels like taking back control, and I'm REALLY, _**ridiculously**_ excited about it.

### PR DESCRIPTION
**Pull request by ErisDS**
Now rebased on ember-cli, and with improved image upload handling

closes #4368, fixes #1240 (spellcheck)
- Drop CodeMirror in favour of a plain text area
- Use rangyinputs to handle selections cross-browser
- Create an API for interacting with the textarea
- Replace marker manager with a much simpler image manager
- Reimplement shortcuts, including some bug fixes

### CODE REVIEW

**Comment by ErisDS** [comment]
There was a bug in the original PR such that image uploads were only working if you used the full image tag ``, whereas the dropzone is triggered from as little as `![]`. 

The if statement here: https://github.com/ErisDS/Ghost/commit/98356eb581d4b94b8e4bfeba5fc86db7871cc75d#diff-36b6e407d6ee15870d0692e86d7e3dd8R34 handles that case (I should probably add a comment to explain).

One thing I have noticed whilst playing around with this editor, is that the onChange event that is now the trigger for autosave doesn't fire when images get uploaded. It is possible that other non-human input e.g. shortcuts (i.e. where JS does the insert into the textarea) may also be affected.

Still wanted to get this version up to see how it fairs against Travis. Code review & testing would be much appreciated.

**Comment by ErisDS** [comment]
Comment added to the image handler + I've found the magic bullet for ensuring that autosave gets triggered by uploads, shortcuts and any other programmatic text manipulation in the same way as typing:

https://github.com/ErisDS/Ghost/commit/4854db1bf66ce35367a3a8df7ad741b9e2ba76b2#diff-c54414e2bf948de8c8eabe735323a7d9R97

I think this might be ready :anguished:

File: core/client/app/components/gh-ed-editor-scroller.js [hunk 1]
```diff
@@ -0,0 +1,67 @@
+import Ember from 'ember';
+import setScrollClassName from 'ghost/utils/set-scroll-classname';
+
+var EditorScroller = Ember.Component.extend({
```
Comment (novaugust) [inline core/client/app/components/gh-ed-editor-scroller.js]: I'm looking around, and it doesn't look like this gets used anywhere. Dead code?

File: core/client/app/mixins/ed-editor-api.js [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+var EditorAPI = Ember.Mixin.create({
+    getValue: function () {
+        return this.get('element').value;
+    },
+
+    getSelection: function () {
+        return this.$().getSelection();
+    },
+
+    getLineToCursor: function () {
```
Comment (novaugust) [inline core/client/app/mixins/ed-editor-api.js]: Some docs on these api methods would be cool, but not crucial - just took me a moment to think of what "getLineToCursor" does

File: core/client/app/mixins/ed-editor-api.js [hunk 3]
```diff
@@ -0,0 +1,101 @@
+import Ember from 'ember';
+
+var EditorAPI = Ember.Mixin.create({
+    getValue: function () {
+        return this.get('element').value;
```
Comment (novaugust) [inline core/client/app/mixins/ed-editor-api.js]: Just code-style-wise, this threw me for a loop for a bit. I think our convention's been to work with `this.$()` like you did in `getSelection`, rather than going for the raw dom element

File: core/shared/lib/showdown/extensions/ghostimagepreview.js [hunk 4]
```diff
@@ -1,5 +1,4 @@
 /* jshint node:true, browser:true */
```
Comment (novaugust) [inline core/shared/lib/showdown/extensions/ghostimagepreview.js]: I can't remember why we have two copies of this file now. Did `ember-cli`'s `app.import(...)` fail with files that were outside the scope of the project? That sounds right..

Comment (ErisDS) [inline core/shared/lib/showdown/extensions/ghostimagepreview.js]: I wouldn't worry about it - as soon as this one is merged I have an incoming PR to fix this properly.

**Comment by novaugust** [comment]
Ack... I went off and was making comments on a commit and lost track of what I said and can't find them again. #fail .

Anyhoo, rather than doing the `onChange` action, we can just hook our editor's value into ember's observable network and use the `notifyPropertyChange` method: http://emberjs.com/api/classes/Ember.Observable.html

**Comment by novaugust** [comment]
Otherwise, everything looks good 'nuff to me ;) Just get rid of the dead code and ping me and i'll hit das button

**Comment by novaugust** [comment]
woop woop
screen shot 2015-03-17 at 11 18 20
