### PR TITLE
Fix/delete by author

### LINKED ISSUE #7137: Unable to delete a user, causes all subsequent db requests to fail
### Issue Summary

When attempting to delete a user who has posts I'm seeing a 500 Internal Server Error, all subsequent API requests also return a 500 error.

### Steps to Reproduce

1. Ensure you have a user who has authored some posts
2. Sign out and sign in as a user who has permissions to delete users
3. Select the user from step 1 in the Team page then click the cog icon and select "Delete User"
4. Click "Delete"

At this point I see a long spinner which eventually results in the 500 error and this message in the app log:

```
ERROR: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? 
 
 InternalServerError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Error.InternalServerError (/Users/kevinansfield/code/ghost/Ghost/core/server/errors/internal-server-error.js:6:18)
    at null.<anonymous> (/Users/kevinansfield/code/ghost/Ghost/core/server/models/post.js:661:23)
From previous event:
    at Function.destroyByAuthor (/Users/kevinansfield/code/ghost/Ghost/core/server/models/post.js:660:19)
    at Function.tryCatcher (/Users/kevinansfield/code/ghost/Ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Function.destroyByAuthor (/Users/kevinansfield/code/ghost/Ghost/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/kevinansfield/code/ghost/Ghost/core/server/api/users.js:397:39
    at /Users/kevinansfield/code/ghost/Ghost/node_modules/knex/lib/transaction.js:38:20
    at processImmediate [as _immediateCallback] (timers.js:383:17) 

DELETE /ghost/api/v0.1/users/7/ 500 60093.195 ms - 167
```

Any requests after this point have a similar response.

In case it's particular to my database state, [here's a copy of my sqlite db](https://cl.ly/3d0Y1r170u02)

### Technical details:

* Ghost Version: master
* Database: sqlite

### PR DESCRIPTION
**Pull request by kirrg001**
closes #7137 

Deleting the content from the database runs in a transaction. see
https://github.com/TryGhost/Ghost/blob/master/core/server/api/users.js#L390

`destroyByAuthor` is one of the operations we trigger to delete all the conent, see https://github.com/TryGhost/Ghost/blob/master/core/server/models/post.js#L647

The post model has a specific hook for deleting content to delete the relations as well, see https://github.com/TryGhost/Ghost/blob/master/core/server/models/post.js#L122

This hook is part of the transaction. But the `options` are ignored. `(model/*, attr, options*/)` 
We use the `options` to forward the transaction reference, which we need to pass into the bookshelf queries. So `return model.load('tags').call('related', 'tags').call('detach')` does not forward the transaction and that's why it stucks when deleting the content.

### CODE REVIEW

**Comment by kirrg001** [comment]
ready for review 🎉

**Comment by ErisDS** [comment]
As this PR is a little old, could you please:
- update the PR message to explain in a bit more detail what the fix is? It's quite a big change.
- rebase against master

I think it would be good to get this merged before cutting the `lts` branch?

**Comment by kirrg001** [comment]
@ErisDS rebased. forgot to update the commit message, if you merge you can add:

The Post `destroying` hook is triggered when deleting posts from the database. Because deletion runs in a transaction, the `options` object was totally ignored. options contains the sql transaction.

File: core/server/models/post.js [hunk 1]
```diff
@@ -119,13 +119,24 @@ Post = ghostBookshelf.Model.extend({
...
+                        return baseUtils.tagUpdate.detachTagFromPost(model, tag, options)();
+                    });
+                })
+                .then(function () {
+                    if (model.previous('status') === 'published') {
+                        model.emitChange('unpublished');
+                    }
+
+                    model.emitChange('deleted');
+                });
```
Comment (ErisDS) [inline core/server/models/post.js]: This is a big change that doesn't seem to be explained in the PR message. Adding explanations in the commit message is nice, but in the PR message it is needed so that I am able to understand what you are changing and why please :)

File: core/server/models/base/token.js [hunk 2]
```diff
@@ -36,7 +36,7 @@ Basetoken = ghostBookshelf.Model.extend({
             .query('where', 'expires', '<', Date.now())
             .fetch(options)
             .then(function then(collection) {
-                collection.invokeThen('destroy', options);
+                return collection.invokeThen('destroy', options);
```
Comment (ErisDS) [inline core/server/models/base/token.js]: Looking at this code now, this seems really quite weird. What is the difference between `invokeThen` and calling `destroy()` itself? Just asking out of interest.

Also, I know that bookshelf is moving away from using collections entirely, so perhaps this code needs a different refactor? Again, wanted to flag this up whilst we're here so that we know what needs to be done

**Review by ErisDS — COMMENTED** [review]
Got a few questions / concerns that I'd like a little bit of clarification on before merging please.

File: core/server/models/post.js (hunk 1 above)
Comment (kirrg001) [inline core/server/models/post.js]: see https://github.com/TryGhost/Ghost/pull/7145#issuecomment-247973183

File: core/server/models/base/token.js (hunk 2 above)
Comment (kirrg001) [inline core/server/models/base/token.js]: Nothing changed here except of the `return` statement.

see: http://bookshelfjs.org/#Collection-instance-invokeThen

Comment (ErisDS) [inline core/server/models/base/token.js]: I understand that only the return statement changed, I'm just questioning whether this code is even correct ?

Comment (kirrg001) [inline core/server/models/base/token.js]: i didn't concentrated on verifying that, just stumbled over the non existing return. 
i can extend my big test case to ensure expired tokens get deleted?maybe a good idea
