### PR TITLE
Node version check w/o semver

### LINKED ISSUE #6691: Can't install ghost npm package w/ recent versions of npm@3.
### Issue Summary

Unable to install the ghost npm package with npm version 3. It appears as though the `preinstall` script has run afoul of the way that npm 3 behaves. After a cursory look at what's going on, it appears as though it gets into an endless recursive install and just keeps on trying to `npm install semver` over and over.

### Steps to Reproduce

1. In an otherwise unused directory, do an `npm install ghost`.

### Technical details:

* Ghost Version: 0.7.8 (npm package)
* Node Version: 4.4.x
* Browser/OS: OS X; Linux
* Database: n/a

### PR DESCRIPTION
**Pull request by ErisDS**
This PR is an attempt to reduce the amount of friction users have with installing Ghost.

The other option rather than doing this would be simply to remove this check.

Unfortunately, different versions of `npm` all handle `preinstall` quite differently. The order of operations are completely different between npm@2 and npm@3. Further still, using `npm install` inside of a `preinstall` script runs into permissions issues frequently.

This PR removes the need for npm installing `semver` and also removes the require of `package.json` from the check that is run during the preinstall.

I'm then using a very simple strategy to attempt to match the current node version with one of the version strings in `package.json#engines`:
- clean up the node version string to be just the first two digits: `x.x` - major & minor, as these are the only ones we ever want to match against.
- for each version in engines:
  - detect the first char as `~` or `^` as we have to do different matches for these
  - also simplify the string to major & minor
  - for ~ check the strings are identical (0.10 or 0.12)
  - for ^ check the first number is the same (4) and the second number is the same or greater (2+)

This should also work when we remove `~0.10.0` and add `^6.??.0` in October.

I have tested this on my mac using both npm@2 and npm@3. I have tested both running `npm install` inside Ghost, and proxied testing `npm install ghost` by using a local package as described [here](http://podefr.tumblr.com/post/30488475488/locally-test-your-npm-modules-without-publishing).

I don't really know how to replicate the issues which result in the error `npm WARN cannot run in wd` - these are usually to do with needing sudo or some other permission issue?

If anyone has an idea what to test to see if this code is less painful, I'd be grateful.

---

closes #6691
- removes dependency on semver & package.json in preinstall script
- has a simplified proxy of semver to look for the right version numbers

### CODE REVIEW

File: core/server/utils/pre-check.js [hunk 1]
```diff
@@ -0,0 +1,47 @@
+var validVersions = process.env.npm_package_engines_node.split(' || '),
```
Comment (kirrg001) [inline core/server/utils/pre-check.js]: **this is a general suggestion**
put the script into `core/server/utils/npm/preinstall.js`
just having the `pre-check.js` inside `utils` folder looks like it's a server util.
And if we name the script `preinstall.js` it fits the npm wording.

Comment (ErisDS) [inline core/server/utils/pre-check.js]: ❤️  this suggestion! On it 👍

**Comment by ErisDS** [comment]
Note: I'm aware we now have 2 checks which do roughly the same thing, as I didn't do anything with the one in startup-checks yet. 

My main goal here is just to fix the install process before we do another release. 

We're hatching a plan to completely overhaul the install process, so I'm not too worried about having stuff hanging around as that project will definitely fix it.

File: core/server/utils/pre-check.js [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+
+        validVersions.forEach(function (version) {
+            var matchChar = version.charAt(0),
+                versionString = version.match(majMinRegex)[0];
+
+            if (
+                (matchChar === '~' && currentVersion === versionString)
+                || (matchChar === '^'
+                    && currentVersion.match(majorRegex)[0] === versionString.match(majorRegex)[0]
+                    && currentVersion.match(minorRegex)[0] >= versionString.match(minorRegex)[0]
```
Comment (kirrg001) [inline core/server/utils/pre-check.js]: suggestion:
we could compare strings here. we have two numbers, on position 0 and position 2. position 1 is a dot.

```
if (... currentVersion[0] === versionString[0] && currentVersion[2] >= versionString[2])
```

The disadvantage of this line of code is that we don't ensure that the value inside the strings are numbers.
But that is totally up to you, that was just something i had in my mind.

**Comment by kirrg001** [comment]
i like this improvement. i've tested so far with `npm2` and several combinations, couldn't break it. will try on `npm3` soon.

**Comment by ErisDS** [comment]
Just for reference, I seem to be able to switch npm versions quite easily by doing `npm i -g npm@2` or `npm i -g npm@3`.

**Comment by kirrg001** [comment]
tested on `npm3`, found nada issues.
