### PR TITLE
Fix post deletion scroll on content and tag screens

### LINKED ISSUE #6006: Bug: Content management items
Two minor bugs on content mgmt at the moment:
1. When you delete a post, expected behaviour is that the next post below the current one will be selected. (Same as an email inbox) – Currently, the very first/most-recent post is selected at the top of the list when a post is deleted.
2. ~~Deleting a bunch of posts in a row breaks loading, leaves a big empty gap with no way to load in any new posts (see below).~~ closed by #6387 (#6390)

image

### LINKED ISSUE #6390: Load more posts after mass deletion on content screen
>Deleting a bunch of posts in a row breaks loading, leaves a big empty gap with no way to load in any new posts (see below).

Part 2 of #6006

### PR DESCRIPTION
**Pull request by novaugust**
Closes #6390
- check if more posts should be loaded whenever one is deleted
- delete dead code from posts controller
- delete duplicate component gh-infinite-scroll-box
- simplify posts-list-item `posts.post` or `editor.edit` link logic by modifying `gh-content-view-container` to yield necessary vars directly and use inline ifs in template
- add `gh-tag` component for rendering tags and updating infinite scroll box on `settings/tags` page

### CODE REVIEW

**Comment by novaugust** [comment]
This has an issue right now where the redirection inside of `transitionTo` somehow interferes with the link to that post properly receiving the `active` class. In other words, the "selected" CSS doesn't show up, but all the rest of the behaviour is correct. Not sure what's up with the links, but I'll be thinking on it

File: core/client/app/routes/posts.js [hunk 1]
```diff
@@ -69,6 +69,22 @@ export default AuthenticatedRoute.extend(ShortcutsRoute, PaginationRouteMixin, {
...
+            let transitionDueToDeletion = this.get('controller.currentPost.isDeleted')
+                && transition.targetName === 'posts.index';
+            let posts, nextPost, deletedPostIndex;
+
+            if (transitionDueToDeletion) {
+                posts = this.get('controller.sortedPosts');
+                deletedPostIndex = this.get('controller.currentPostIndex');
+                nextPost = posts.objectAt(deletedPostIndex);
+                if (nextPost) {
+                    return this.transitionTo('posts.post', nextPost);
```
Comment (kevinansfield) [inline core/client/app/routes/posts.js]: You might want to abort the existing transition here and then try redirecting to the `nextPost.id` so that the relevant model hooks in the post controller get called - not tested it but just a hunch that it might fix the `active` link issue.

Comment (novaugust) [inline core/client/app/routes/posts.js]: I actually had that originally, and took it out on the hunch that it might be the issue :D Read up on their docs: the difference is, if you call `.abort()` within here you'll trigger a new round of "willTransition", whereas just doing a `transitionTo` is equivalent to a redirect so you won't call willTransition twice

**Comment by novaugust** [comment]
I really don't have a clue what's up with the active bit. I can always remove the "next post on delete" functionality from this PR and at least get in the post loading on delete bits if desired.

**Comment by kevinansfield** [comment]
Not too sure either 🤔, would you mind removing the "next post on delete" functionality from this PR?

I'm wondering if it might be more suitable to add an `afterDelete` action to the posts controller and pass that to the delete-post modal as a closure action that it can call after a successful delete. Not sure if that will fix the `active` issue but it would at least prevent the route needing to know about the controller's internals.

**Comment by novaugust** [comment]
> and pass that to the delete-post modal

Tricky to do when it's wrapped up in the gh-fullscreen-modal ;)

Yeah, I'll break this apart.

**Comment by kevinansfield** [comment]
> Tricky to do when it's wrapped up in the gh-fullscreen-modal ;)

Yeah, I haven't come up with an easy way to pass arbitrary data through the nested component at the top-level yet :disappointed:

For the time-being it's possible to pass `model=(hash model=post afterDelete=(action 'afterDelete'))` (all the brackets!)

File: core/client/app/controllers/posts.js [hunk 2]
```diff
@@ -81,14 +81,6 @@ export default Controller.extend({
...
 
     actions: {
-        showPostContent(post) {
-            if (!post) {
-                return;
-            }
-
-            this.transitionToRoute('posts.post', post);
-        },
-
```
Comment (novaugust) [inline core/client/app/controllers/posts.js]: Dead code

File: core/client/app/components/gh-posts-list-item.js [hunk 3]
```diff
@@ -34,10 +34,6 @@ export default Component.extend(ActiveLinkWrapper, {
         return Ember.String.htmlSafe(`background-image: url(${this.get('authorAvatar')})`);
     }),
 
-    viewOrEdit: computed('previewIsHidden', function () {
-        return this.get('previewIsHidden') ? 'editor.edit' : 'posts.post';
-    }),
-
```
Comment (novaugust) [inline core/client/app/components/gh-posts-list-item.js]: Rather than calculate this view logic for every item, just threw an inline if into the template.

**Comment by novaugust** [comment]
@kevinansfield updated to just do "load posts on post deletion"

File: core/client/app/controllers/posts.js (hunk 2 above)
Comment (halfdan) [inline core/client/app/controllers/posts.js]: @novaugust You are dead code!

Comment (novaugust) [inline core/client/app/controllers/posts.js]: !!!!!!!!!!!!!!!

**Comment by kevinansfield** [comment]
@novaugust Looks good so far, could you also add this behaviour to the tags screen? It also uses `gh-infinite-scroll` and suffers from the same issue if you delete a lot of tags

**Comment by novaugust** [comment]
@kevinansfield This has been on my mind, just haven't made the time. Should get it done after the next meeting

**Comment by novaugust** [comment]
in before the meeting! updated with the requested tag behaviour
