### PR TITLE
Show correct error message the first time account is locked

### LINKED ISSUE #7251: Validation for incorrect password is incorrect when account is locked
### Issue Summary

When intentionally spamming the signup screen, there's a validation issue whenever you spam it too many times. It counts down correctly from 4 attempts remaining down to 1, but if you enter it incorrectly one more time after that (which locks your account, instead of returning "your account is locked" it says "Your password is incorrect. attempt remaining!" (it's missing a number).

This isn't really a security issue as the account locking still happens (trying to enter the correct password after getting the validation message without a number of remaining attempts gets the "Your account is locked" message), but it is a bit odd.

### Steps to Reproduce

1. Setup blog and create account
2. Keep trying to log in with a bad password until you get locked out
3. Notice that on the last try you get the wrong message

This _is_ a server issue as looking at the server logs, the validation message shown is being returned by the server.

### Technical details:

* Ghost Version: [master](https://github.com/TryGhost/Ghost/commit/6c199afedf50ea3c3d1ebd7f5781d540b16f45f3)
* Node Version: latest 4.x
* Browser/OS: Chrome 52
* Database: SQLite

### PR DESCRIPTION
**Pull request by acburdine**
closes #7251
- check if remaining attemps is 0, if so then show account locked error

Turns out this was a bug in the user model. Regardless, this fixes it
- [x] tests

### CODE REVIEW

**Comment by acburdine** [comment]
@kirrg001 It's an interesting way of testing, but there are now tests for it 😛

File: core/test/integration/model/model_users_spec.js [hunk 1]
```diff
@@ -662,4 +662,45 @@ describe('User Model', function run() {
...
+            return UserModel.check(object).then(userWasLoggedIn)
+                .catch(checkAttemptsError(4))
+                .then(userWasLoggedIn)
+                .catch(checkAttemptsError(3))
+                .then(userWasLoggedIn)
+                .catch(checkAttemptsError(2))
+                .then(userWasLoggedIn)
+                .catch(checkAttemptsError(1))
+                .then(userWasLoggedIn)
+                .catch(checkLockedError);
```
Comment (acburdine) [inline core/test/integration/model/model_users_spec.js]: Promise 🔗 s FTW!

File: core/server/models/user.js [hunk 2]
```diff
@@ -554,6 +554,12 @@ User = ghostBookshelf.Model.extend({
                 return bcryptCompare(object.password, user.get('password')).then(function then(matched) {
                     if (!matched) {
                         return Promise.resolve(self.setWarning(user, {validate: false})).then(function then(remaining) {
+                            if (remaining === 0) {
```
Comment (kirrg001) [inline core/server/models/user.js]: if you would change `if (level > 4) {` in line `529` to `if (level > 3) {`, then it works without having this extra check here.

File: core/test/integration/model/model_users_spec.js (hunk 1 above)
Comment (kirrg001) [inline core/test/integration/model/model_users_spec.js]: hehe 👍

**Comment by ErisDS** [comment]
Just want to flag up that these if statements have changed a few times trying to get this right in all cases. Probably worth doing  git blame and looking at the change history.

File: core/server/models/user.js (hunk 2 above)
Comment (ErisDS) [inline core/server/models/user.js]: That would, I believe, lock the account after 4 attempts instead of 5?

Comment (ErisDS) [inline core/server/models/user.js]: Case in point: https://github.com/TryGhost/Ghost/commit/b7a80eb5fd515dae92b57cce394a3a618b006171

Comment (acburdine) [inline core/server/models/user.js]: Yeah that's what would happen. The reason this check is necessary is because of how the entire method is ordered.
