### PR TITLE
Fixed wrong handling of formats param

### LINKED ISSUE #9077: Directly loading an editor URL results in empty content
### Issue Summary

If you access an editor URL directly (eg. http://ghost.blog/ghost/#/editor/59c27dcda3a99a2a33e8bdb3) then the post content will not be displayed in the editor

### Steps to Reproduce

1. Open a post in the editor
2. Refresh the page
3. Note that the post content is now missing

Opening the editor via a URL should be no different to navigating from the posts list.

After investigating, the client appears to be doing the correct thing but the API is not returning the correct formats.

Client loads an individual post when accessed via URL, http://ghost.blog/ghost/api/v0.1/posts/59c27dcda3a99a2a33e8bdb3/?status=all&staticPages=all&formats=mobiledoc%2Cplaintext&include=tags - the response from the API is only returning the `html` attribute, not `mobiledoc` and `plaintext` as specified in the URL.

### Technical details:

* Ghost Version: master
* Browser/OS: Chrome/macOS

### PR DESCRIPTION
**Pull request by kirrg001**
closes #9077

- caused by our API layer refactoring, see https://github.com/TryGhost/Ghost/pull/9068
- we can now see that code was written wrong because of this horrible API bug
- this fixes the formats parameter for querying a single post

This allows an extra `formats` option (next to include and context).

### CODE REVIEW

File: core/server/api/posts.js [hunk 1]
```diff
@@ -105,7 +105,7 @@ posts = {
 
         // Push all of our tasks into a `tasks` array in the correct order
         tasks = [
-            apiUtils.validate(docName, {attrs: attrs, opts: options.opts || []}),
+            apiUtils.validate(docName, {attrs: attrs, opts: options.opts || ['formats']}),
```
Comment (kirrg001) [inline core/server/api/posts.js]: Hmmmm i am not sure why we use `options.opts`. It's only used in the post API, no where else.
I assume it's only used in tests to extend the possible options to pass in, but not sure that makes any sense.

Comment (kirrg001) [reply core/server/api/posts.js]: Oh it's used from the scheduler API. Will add a comment.

**Comment by kevinansfield** [comment]
👍 working for me 😄
