### PR TITLE
Fix 404 error handling in editor, tags, and team routes

### LINKED ISSUE #6094: Accessing unknown tag shows 500 instead of 404
Steps to reproduce:

1. Visit http://localhost:2368/ghost/settings/tags/unknown/ (making sure you don't already have a tag with the slug `unknown` :wink: )
2. You are shown the 500 error screen

Expected result:

- 404 response from the API is handled gracefully
- You are shown the 404 "not found" screen

screen shot 2015-11-19 at 16 08 29

### PR DESCRIPTION
**Pull request by acburdine**
closes #6094
- adds 404-handler mixin
- applies mixin to settings/tags/tag and editor/edit routes

TODO: 
- [x] Add tests
- [x] :8ball:

### CODE REVIEW

**Comment by acburdine** [comment]
@kevinansfield I tried to add tests for this, but was running into several issues. While it works when I run the blog locally, it appeared the acceptance tests weren't waiting for the transition to the 'error404' route to occur.

**Comment by acburdine** [comment]
@kevinansfield I got tests working, but in an odd fashion. On my local, the PhantomJS tests keep timing out, while the Chrome tests seem to work just fine. Not quite sure what's going on.

**Comment by acburdine** [comment]
@kevinansfield Turns out that when an adapter error is thrown in tests, it stops the tests. I found that you have to override the default adapter error behavior in order to make the tests work.

File: core/client/tests/acceptance/settings/tags-test.js [hunk 1]
```diff
@@ -46,9 +48,11 @@ describe('Acceptance: Settings - Tags', function () {
 
     beforeEach(function () {
         application = startApp();
+        errorOverride();
```
Comment (kevinansfield) [inline core/client/tests/acceptance/settings/tags-test.js]: I think in this case it would be better to add the override only to the tests that we know will throw an error - we don't want to hide errors in tests where we aren't expecting them.

**Comment by acburdine** [comment]
@kevinansfield should be good to go now :+1:
