### PR TITLE
🐛  fix transfer ownership

### LINKED ISSUE #8781: Ghost admin: Deleting initial owner makes initial setup run again
As I have mentioned in the title, when you transfer ownership of the blog and delete the initial owner that you have created while first setting up ghost admin, the ghost admin shows the setup page again.

---

This page shows on log-out after I have transferred ownership of my blog to another user and delete the previous/original owner:
image

### PR DESCRIPTION
**Pull request by kirrg001**
closes #8781

- when the ownership get's transferred, the id of the new owner is not '1' anymore
- we previously added a database rule, which signalises if the blog is setup or not, see https://github.com/TryGhost/Ghost/commit/827aa15757bcfdcfe7cbb0a3ce9e3c3117657ce2#diff-7a2fe80302d7d6bf67f97cdccef1f71fR542
- this database rule is based on the owner id being '1', which is wrong when you transfer ownership
- we should keep in mind, that the owner id being '1' is only the default Ghost setup, but it can change

- [x] blog setup and locked users
- [x] add tests
- [x] do final manual test

### CODE REVIEW

File: core/server/data/importer/importers/data/base.js [hunk 1]
```diff
@@ -182,54 +182,57 @@ class Base {
...
-                return models.User.findOne({
-                    email: oldUser.email,
-                    status: 'all'
-                }, options).then(function (userModel) {
-                    // CASE: user could not be imported e.g. multiple roles attached
-                    if (!userModel) {
-                        userModel = {
-                            id: models.User.ownerUser
-                        };
+        return models.User.getOwnerUser(options)
```
Comment (kirrg001) [inline core/server/data/importer/importers/data/base.js]: Nothing in this file has changed, except of fetching the owner user. This is not optimal, because it would fetch the owner for each table, but it should be a cached query. There is no need in my opinion to pre-optimise this until we want to optimise the performance of the importer.

File: core/server/models/base/index.js [hunk 2]
```diff
@@ -302,17 +302,12 @@ ghostBookshelf.Model = ghostBookshelf.Model.extend({
...
      * please use these static definitions when comparing id's
-     * we keep type number, because we have too many check's where we rely on
+     * we keep type Number, because we have too many check's where we rely on Number
      * context.user ? true : false (if context.user is 0 as number, this condition is false)
      */
     internalUser: 1,
-    ownerUser: 1,
     externalUser: 0,
 
-    isOwnerUser: function isOwnerUser(id) {
```
Comment (kirrg001) [inline core/server/models/base/index.js]: This fn was invented to have an easy, centralised comparison for the owner user, but transferring the ownership can result in an owner user with the id being not '1'. The function was added when we worked on OAuth, not used anyway right now.

File: core/server/models/user.js [hunk 3]
```diff
@@ -333,7 +333,7 @@ User = ghostBookshelf.Model.extend({
         status = data.status;
         delete data.status;
 
-        options = options || {};
+        options = _.cloneDeep(options || {});
```
Comment (kirrg001) [inline core/server/models/user.js]: `findOne` modifies the options, we have to clone them.
