### PR TITLE
Prevent multiple owner creation via importer

### LINKED ISSUE #4778: Bug: Imports from a Ghost installation: Imported 'Owner' account login not permitted, gives incorrect error message.
### Issue Summary
When importing data from a Ghost installation (Blog Old) to a different install of Ghost (Blog New) and then logging out of the Blog New admin account on Blog New a user attempting to log back in to Blog New with the (different) account details for the imported "Owner" account from Blog Old is given an error message saying that the account is "Locked due to too many login attempts.", urging them to use the Forgotten Password link, even though this account has never attempted a log in before on this new installation of Ghost. When user follows through with password reset the account works fine.

### Steps to Reproduce

Export Ghost settings and data from one Ghost install, import into a different installation.

Log out of Ghost on the installation which the data was imported into.

Attempt log in with account credentials contained in imported data and settings, see incorrect error message.

screen

### Expected behavior 

User is given correct error message explaining why they are unable to log in. Or, user is able to log in to imported accounts without any issues when importing from another Ghost installation. If password reset is required on import, a call to action.

### Technical details

* Ghost Version: Release 0.5.7
* Node Version: 0.10.25

### PR DESCRIPTION
**Pull request by cobbspur**
closes #4778
- If import contains an owner that does not match original owner they are downgraded to admin
- Change error message for locked users to more generic message to account for imported users
- Adds duplicated user test

### CODE REVIEW

File: core/server/data/import/utils.js [hunk 1]
```diff
@@ -136,11 +134,20 @@ utils = {
...
                 return user.id === parseInt(roleUser.user_id, 10);
             });
+
+            // Check for owner users that do not match current owner and change role
+            // to administrator
+
+            if (roleUser.role_id === 4 && user && user.email && user.email !== owner.email) {
+                roleUser.role_id = 1;
+                user.roles = [1];
+            }
```
Comment (ErisDS) [inline core/server/data/import/utils.js]: Although I'm pretty sure that on 99.9% of blogs, the role ids are 1 for admin and 4 for owner, there is no guarantee that this is the case.

For this reason, we have to jump through extra steps to match the role id to a role and then look for the name, as is done for models here: https://github.com/cobbspur/Ghost/blob/owner/core/server/data/import/data-importer.js#L23

For the import here, the role ids should be mapped to the roles listed in the imported JSON, but if they are missing I think it is safe to fall back to the assumption that 1 === admin, and 4 === owner.

In the future, for smarts, it might be useful to define a shorthand for this such that you could define something like: 

```
"users": [{
   id: 3,
   name: "A User",
   email: "user@example.com",
   roles: ["Owner"]
}]
```
(this is from the bare-minimum user map as described in the JSON format doc: https://github.com/TryGhost/Ghost/wiki/import-format#linking-objects-to-users)

This would allow the quick-creation of a user map where each user has a certain role. It is certainly a different thing to this PR and just an idea I wanted to write down whilst I was thinking of it :) You'll know best whether this is a good idea :wink:

**Comment by cobbspur** [comment]
Updated PR to map roles
Now also checks for unknown roles and changes these users to authors
