### PR TITLE
Fixed gh-date-time-picker not using site's timezone for min/max date

### LINKED ISSUE #15497: Post settings menu date picker doesn't use site timezone
### Issue Summary

The timezone of post settings menu date picker doesn't match the site's timezone. This prevents a user from editing the publication date of a post when the publication date is published the following day relative to the user's current timezone.

### Steps to Reproduce

- Set the site's timezone to one that is a day ahead of your current timezone
- Start a new draft
- Open the post settings menu, note that the publish date is set to the right date (one day ahead of you)
- Try to edit that value:
image

Note that although the date in the box is correct (the 29th in the screenshot), the selected date in the date picker is the previous day (the 28th), or today in your current timezone. Today in the site timezone (29th) is not selectable.

### Ghost Version

5.16

### Node.js Version

16

### How did you install Ghost?

ghost install

### Database type

MySQL 8

### Browser & OS version

Tested in latest Mac Chrome

### Relevant log / error output

_No response_

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

### PR DESCRIPTION
**Pull request by ozanuslan**
#### Summary
+ Expected behavior of the default `'now'` option for both min and max date available was not met. `'now'` option for min/max date used `moment()` function which did not consider the timezone of the site. Now `moment.tz()` is used instead of `moment()`, and blogTimezone attribute is provided as the timezone. With this change, default `'now'` option will use the site's timezone.
+ Fixes: #15497 

- [x] There's a clear use-case for this code change, explained below
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test:all` and `yarn lint`)

### CODE REVIEW

File: ghost/admin/app/components/gh-date-time-picker.js [hunk 1]
```diff
@@ -121,15 +121,15 @@ export default class GhDateTimePicker extends Component {
 
         // unless min/max date is at midnight moment will disable that day
         if (minDate === 'now') {
-            this.set('_minDate', moment(moment().format(DATE_FORMAT)));
+            this.set('_minDate', moment.tz(moment().format(DATE_FORMAT)), blogTimezone);
```
Comment (SimonBackx) [inline ghost/admin/app/components/gh-date-time-picker.js:124]: Thank you for your contribution! I only have two remarks that should be easy to fix.

- `blogTimezone` has been added as an argument to `set` instead of `moment.tz`
- Say that the current date in the timezone of the server is `2022-01-02`. And your local timezone, the current date is `2022-01-01`. Then this line will run the following code:
```
this.set('_minDate', moment.tz('2022-01-01', blogTimezone));
```
Which means that the minimum selectable day is still not right, sadly. 

I think we need one extra change here (for both the minimum and maximum date):

```suggestion
            this.set('_minDate', moment.tz(moment().tz(blogTimezone).format(DATE_FORMAT), blogTimezone));
```

Comment (ozanuslan) [reply ghost/admin/app/components/gh-date-time-picker.js:124]: You are absolutely right! Let me quickly push a new commit implementing these changes. 🚀

Comment (ozanuslan) [reply ghost/admin/app/components/gh-date-time-picker.js:124]: One quick question about the new change. Do you think we still need the outer `moment.tz` call if we are setting the timezone of the date inside?
```suggestion
            this.set('_minDate', moment(moment().tz(blogTimezone).format(DATE_FORMAT)));
```

**Comment by SimonBackx** [comment]
Fantastic! 🙌 Thank you!

**Review by SimonBackx — APPROVED** [review]

**Comment by ErisDS** [comment]
Hey @ozanuslan Not sure if you found this through hacktoberfest, but I've added the approved label to this PR to make sure it counts. We have plenty of open issues and ongoing projects for hacktoberfest and would love to see you around again 👋

**Comment by ozanuslan** [comment]
Thank you for being so considerate @ErisDS :smiley: Really appreciate it. My hacktoberfest contributions have been fulfilled, so it's fine if this one doesn't count. I've contributed to Ghost at last year's hacktoberfest as well, so I though it would be a shame if I didn't contribute this year as well. I'll try to check out more issues as I find some free time. Thanks again :wave:

**Comment by ErisDS** [comment]
Ah yes! I thought I recognised your name from somewhere 🙂 We always have plenty of open issues - we now track more bugs and projects in the public repo - and would love to have more regular contributors to help us get more stuff out to our users ⚡ there's always so much to do!
