### PR TITLE
🐛 Ensure config is update when deleting theme

### LINKED ISSUE #8059: Bug: Deleted theme still shows in Ghost-Admin
### Issue Summary

If you delete a theme in admin, it still shows up (though it does appear to get deleted). If you activate the theme, it will say theme not found.

### Steps to Reproduce

1. Delete theme
2. Theme still shows up, activate theme

### Technical details:

* Ghost Version: LTS 0.11.5 
(note this seems to be okay on LT 0.11.4 and on master)

### PR DESCRIPTION
**Pull request by ErisDS**
Adding an extra call to the api in the deletion route test made the tests fail. Fixing the config call back to what it was before made it pass again.

fixes #8059

- Not sure why I changed this the first time, it was obviously like this for a reason 😂
- Config.set() doesn't update the object properly, modifying this._config does
- Thank heavens this doesn't exist in alpha anymore 😁

### CODE REVIEW

File: core/test/functional/routes/api/themes_spec.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ describe('Themes API', function () {
             }).catch(done);
     });
 
-    describe('success cases', function () {
+    describe.only('success cases', function () {
```
Comment (kevinansfield) [inline core/test/functional/routes/api/themes_spec.js]: 🙈

Comment (ErisDS) [inline core/test/functional/routes/api/themes_spec.js]: FUCK! 😂 😂

Comment (kirrg001) [inline core/test/functional/routes/api/themes_spec.js]: only me and only you....aahhhhhh 🎹

**Comment by ErisDS** [comment]
It's always the same. Big PRs I check and double check, 1-liners fail linting 5 times 😂

**Review by kirrg001 — APPROVED** [review]

File: core/server/config/index.js [hunk 2]
```diff
@@ -94,7 +94,7 @@ ConfigManager.prototype.loadThemes = function () {
 
     return readThemes(self._config.paths.themePath)
         .then(function (result) {
-            self.set({paths: {availableThemes: result}});
+            self._config.paths.availableThemes = result;
```
Comment (kirrg001) [inline core/server/config/index.js]: It's funny because i saw this line was changed in one of your PR's, but i thought "yeah that makes sense, nconf uses the set function.........."

Totally confused between LTS and master sometimes 💃
