### PR TITLE
🐛 Fixed slugs from exceeding db limit

### LINKED ISSUE #8143: Database soft limits
We have recently optimised our hard limits, see #7932.
One optimisation which is missing are the soft limits. A soft limit is a limit which is defined within the application as validation condition - client and server side. 

See original issue and discussion https://github.com/TryGhost/Ghost/issues/4134.
e.g. it was suggested to increase the post title validation from 150 to 255.

**We have to go over all soft limits and decide on a reasonable limit.**

### PR DESCRIPTION
**Pull request by aileen**
closes #8143

Fixed a potential issue (edge-case), where our generated and validated (in terms of check for existance and add a counter) would return a slug, that will exceed the maximum length of the slug fields (191 chars).

This is mostly possible for the post title, which can be 255 chars long and would generate a slug with the same length. This would prevent the user from actually saving a post.

I tried first to determine the expected length for a slug that already exists, but decided that the **easier** and simplyfied implementation is to always cut a slug to **185 chars** (+ counter). This makes it easier to find duplicates and includes a possible high number of counts (edge-edge-case).

### CODE REVIEW

**Comment by AileenCGN** [comment]
@kirrg001 I would like to hear your thought about that. I am not entirely sure, if I might've forgotten a case...

I tried for quite a while to implement it in a different way, but take this situation:
- slug gets generates with 191 chars
- another slug is about to get generated, but is actually a duplicate, so I remove the `-` and the counter that is about to get added and trim the slug by the same amount. Let's say, it's now 189 chars long.
- our fn checks again, if this slug exists and comes to the conclusion that it doesn't so the returned slug would then the the 189 chars long one (without `-` and count).
- only for the third time then, we would add a counter to it.

We could definitely implement this logic, but IMO this is a but too much for such edge cases and I therefore vote for my solution.

File: core/server/models/base/index.js [hunk 1]
```diff
@@ -712,7 +712,10 @@ ghostBookshelf.Model = ghostBookshelf.Model.extend({
             });
         };
 
-        slug = utils.safeString(base, options);
+        // the slug may never be longer than the allowed limit of 191 chars, but should also
+        // take the counter into count. We reduce a too long slug to 185 so we're always on the
+        // safe side, also in terms of checking for existing slugs already.
+        slug = utils.safeString(base, options).slice(0, 185);
```
Comment (kirrg001) [inline core/server/models/base/index.js]: The only case i can think of which is very edgy, but still want to share.
If you import a slug which is longer than 185, we don't want to cut off the slug.
Instead we want to show the validation error to the user, so he can fix his issue by himself.

Other than that, i have no simpler or better idea to this. It's edgy anyway.

Comment (AileenCGN) [reply core/server/models/base/index.js]: I‘ll check tomorrow, if this rn is actually ever touched when importing. Currently I‘d say no, but I‘ll verify this tomorrow and maybe create an error if so.

Comment (kirrg001) [reply core/server/models/base/index.js]: Thanks 👍  Other than that we can merge this, thanks.

Comment (AileenCGN) [reply core/server/models/base/index.js]: Unfortunately, they are cut off on an import 😔

I played around with it for a couple of hours and couldn't find an appropriate solution. The only easy-to-implement way I found, was to show a warning, rather than an error, [here](https://github.com/TryGhost/Ghost/blob/master/core/server/data/importer/importers/data/base.js#L60)

The only place and way I found where import errors are produces is in the schema validation, which is called [here](https://github.com/TryGhost/Ghost/blob/master/core/server/models/base/index.js#L124). But because, we didn't set a shorter soft limit for the slug values, the validation would only fail, when the hard limit of 191 is reached.

So one easy option for this super edge case would be to produce a warning, when the slug is longer than 185 characters, cut it off anyway, and produce the normal validation error, when the slug is > 191 characters.

Comment (AileenCGN) [reply core/server/models/base/index.js]: I changed the code, so that the slug will not be cut on an import.

**Review by kirrg001 — APPROVED** [review]
This is a good fix. I can't of a simpler/better solution at the moment.  It protects a validation error when the input source (post title, user name) is greater than 191. It does not auto-fix slugs to import. The user has to fix this alone, because a slug can represent an existing url. This is an edge case anyway, because e.g. post titles are usually not so long, same for user names.
