### PR TITLE
🐛 Fixed 404 in collection index page if using data.slug

### LINKED ISSUE #10542: `data: post.slug` breaks meta layer on index collection page
Steps to reproduce:

```
collections:
  /blog/:
     permalink: /blog/{slug}/
     data: post.known
```

Serve /blog/. See error in stdout

```
MESSAGE: Cannot read property 'name' of null

TypeError: Cannot read property 'name' of null
    at getPostSchema (/ghost/ghost-workspace2/core/server/data/meta/schema.js:82:61)
```

### PR DESCRIPTION
**Pull request by naz**
closes #10542

@kirrg001 seems like a pretty straight forward fix but maybe you could think of some of the edge cases that could've been broken. One thing that I was puzzled about for a while when testing is that alliased resource in `data: {resource.slug}` e.g.: `data: post.know` wasn't accessible anymore and redirected me to the collection page, but later found the answer in the docs: `The source route of the data will be redirected to the new custom route. ` :grimacing:

### CODE REVIEW

File: core/server/services/routing/helpers/fetch-data.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ function fetchData(pathOptions, routerOptions, locals) {
 
     // CASE: fetch more data defined by the router e.g. tags, authors - see TaxonomyRouter
     _.each(routerOptions.data, function (query, name) {
-        props[name] = processQuery(query, pathOptions.slug, locals);
+        props[name] = processQuery(_.merge(query, defaultQueryOptions), pathOptions.slug, locals);
```
Comment (kirrg001) [inline core/server/services/routing/helpers/fetch-data.js]: `defaultQueryOptions` is only valid if the target fetch is from post or page api endpoint.

Comment (gargol) [reply core/server/services/routing/helpers/fetch-data.js]: yeah, was thinking about his part as well.... the other way around it would be having a config similar to:
```
const defaultDataQueryOptions = {
    post: {
        options: {
            include: 'author,authors,tags'
        }
    },
    page: {
        options: {
            include: 'author,authors,tags'
        }
    },
    tag: {
        // nothing is needed , same for author
    }
};
```
but with tag and author resources, no additional relations are needed to render collections index page.

Comment (gargol) [reply core/server/services/routing/helpers/fetch-data.js]: @kirrg001 maybe adding per resource config like that will make it more explicit.. even if there's nothing to 'extend'. will do the change :+1:

File: core/server/services/routing/helpers/fetch-data.js [hunk 2]
```diff
@@ -28,6 +28,13 @@ const defaultQueryOptions = {
     }
 };
 
+const defaultDataQueryOptions = {
```
Comment (gargol) [inline core/server/services/routing/helpers/fetch-data.js]: @kirrg001 changed the config to be more explicit. Think it's pretty readable this way

File: core/server/data/meta/schema.js [hunk 3]
```diff
@@ -69,6 +69,8 @@ function getPostSchema(metaData, data) {
     var description = metaData.excerpt ? escapeExpression(metaData.excerpt) : null,
         schema;
 
+    const context = data.page ? 'page' : 'post';
```
Comment (kirrg001) [inline core/server/data/meta/schema.js]: Does this work with v0.1? v0.1 had no differentiation for posts & pages.
`getPostSchema` is not only used for the "data" property. It's also used if you serve a post or a page.

Comment (gargol) [inline core/server/data/meta/schema.js]: Was thinking of adding a parameter `context` which would be for the caller - `getSchema` to specify, but didn't go that route as it's not really guaranteed what the properties would be present if e.g. [amp](https://github.com/TryGhost/Ghost/pull/10718/files#diff-50462e912decc8ded2e96b6f5e46e31cR178) condition kicks in. Additionally, the logic below depends on the post/page property being present and the 'context' check - `_.includes(context, 'post')` is not directly guaranteeing that I think. 

These ifs for post or page are another sign of issues with meta layer :man_shrugging:

File: core/server/data/meta/schema.js [hunk 4]
```diff
@@ -38,15 +38,15 @@ function trimSchema(schema) {
 function trimSameAs(data, context) {
     var sameAs = [];
 
-    if (context === 'post') {
-        if (data.post.primary_author.website) {
-            sameAs.push(escapeExpression(data.post.primary_author.website));
+    if (context === 'post' || context === 'page') {
```
Comment (kirrg001) [inline core/server/data/meta/schema.js]: This commit refs https://github.com/TryGhost/Ghost/issues/10082.
I'd suggest to add a bug fix emoji and a ref to this issue as part of the commit :)

File: core/server/services/routing/helpers/fetch-data.js (hunk 2 above)
Comment (kirrg001) [reply core/server/services/routing/helpers/fetch-data.js]: Looks okay as a hot fix, but IMO the includes shouldn't be here at all. They should be part of the target api version config (long-term).

File: core/server/data/meta/schema.js (hunk 3 above)
Comment (gargol) [reply core/server/data/meta/schema.js]: It would default to `post` in that case, but will double check :+1:

File: core/server/data/meta/schema.js (hunk 4 above)
Comment (gargol) [reply core/server/data/meta/schema.js]: Good call. Will do :+1:

File: core/server/data/meta/schema.js (hunk 3 above)
Comment (gargol) [reply core/server/data/meta/schema.js]: Verified and works as expected. Merging these changes
