### PR TITLE
Fix test conflicts

### LINKED ISSUE #6710: Test interdependence issue
Whilst changing the existing `grunt coverage-integration` task to be `grunt coverage-all` in #6704 , I initially put the unit tests after the integration etc tests. That resulted in two tests inside of `unit/config_spec.js` failing with the output below.

Putting the unit tests first resolves the issue enough for #6704, but it would be good to resolve this issue as it means the tests are affecting each other and they definitely shouldn't be.

```
1738 passing (2m)
  11 pending
  2 failing

  1) Config Theme should have exactly the right keys:
     AssertionError: expected Object {
  cover: 'casper',
  description: 'casper',
  logo: 'casper',
  navigation: Array [ Object { label: 'Home', url: '/' } ],
  permalinks: '/:year/:month/:day/:slug/',
  postsPerPage: '5',
  title: 'casper',
  url: 'http://my-ghost-blog.com'
} to have keys url, title, description, logo, cover
	extra keys: navigation, postsPerPage, permalinks
      at Assertion.fail (node_modules/should/lib/assertion.js:91:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:163:19)
      at Context.<anonymous> (core/test/unit/config_spec.js:41:37)

  2) Config Url urlFor should return url for an author when asked for:

      AssertionError: expected '/author/ghost-owner/' to be '/author/joe-bloggs/'
      + expected - actual

      -/author/ghost-owner/
      +/author/joe-bloggs/
      
      at Assertion.fail (node_modules/should/lib/assertion.js:91:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:163:19)
      at Context.<anonymous> (core/test/unit/config_spec.js:299:61)
```

### PR DESCRIPTION
**Pull request by jaswilli**
Closes #6710
- Restore config to baseline before testing.
- Don't mutate fixture data. 😡

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -230,10 +230,10 @@ var _              = require('lodash'),
                 },
                 coverage_all: {
                     src: [
-                        'core/test/unit',
-                        'core/server/apps',
                         'core/test/integration',
-                        'core/test/functional'
+                        'core/server/apps',
+                        'core/test/functional',
+                        'core/test/unit'
```
Comment (jaswilli) [inline Gruntfile.js]: This is just reordered to show that it works. We can leave it like this or I'll change it back--doesn't matter to me.

**Comment by ErisDS** [comment]
That was fast! :dash: 

Also.. this seems pretty healthy:
