### PR TITLE
🐛  Fixed page preview

### LINKED ISSUE #12444: Page previews are rendered in post template with 'post' context
The [`page` context](https://ghost.org/docs/api/v3/handlebars-themes/context/page/) doesn't work for unpublished pages - the `post` context is used when previewing unpublished pages instead.

Additionally, unpublished pages when previewed also incorrectly display the default members CTA.

image

### PR DESCRIPTION
**Pull request by tpatel**
issue #12444

We're adding the `page` property set to true in the serializer so that the context is correctly set to `page` in the context helper.

https://github.com/TryGhost/Ghost/blob/4ef019d88d1c65d15d79b9c720f45218ea34e143/core/frontend/services/routing/helpers/context.js#L62-L65

### CODE REVIEW

File: core/server/api/canary/utils/serializers/output/preview.js [hunk 1]
```diff
@@ -5,5 +5,9 @@ module.exports = {
         frame.response = {
             preview: [mapper.mapPost(model, frame)]
         };
+        const type = model.get('type');
```
Comment (allouis) [inline core/server/api/canary/utils/serializers/output/preview.js:8]: Should we replace the conditional with something like this?
```js
frame.response.preview[0].page = model.get('type') === 'page';
```

That way the response "shape" is always the same, rather than only including the property for pages?

**Review by allouis — COMMENTED** [review]
Looks good, just one question/suggestion!

File: core/server/api/canary/utils/serializers/output/preview.js (hunk 1 above)
Comment (tpatel) [reply core/server/api/canary/utils/serializers/output/preview.js:8]: My thought behind that choice was to have as little side effects as possible, so only change the shape of the object if needed.
I agree it would be cleaner to always have the same shape though!
