### PR TITLE
🎨 Collect & simplify package utils

### LINKED ISSUE #8056: Bug, Blog shows 500 error for large themes
### Issue Summary

Blog shows 500 error when using a theme with many files in it (>100).

### Steps to Reproduce

1. Create a theme with many files in it.
2. Upload and activate theme.
3. Load blog in browser.

### Technical details:

* Ghost Version: Current LTS

### PR DESCRIPTION
**Pull request by ErisDS**
closes #8056

This needs a bit of testing still, but the premise is in place.

The fundamental change is not recursively reading and storing every file in the theme. This should both increase boot speed and reduce load time for blogs with large themes or a large number of themes.

That information was originally intended to be used for things like detecting partial folders, assets etc, sort of how gscan does, but that was never implemented. It's a huge waste of resources.

The only info that ever gets used is the package.json, and even then only the name & version fields, so we could even reduce the stored data further?

- this PR collects together our utilities for reading, filtering, etc etc packages.
- it leaves read-themes where it is & in place as a little wrapper around packages
- I could also get rid of read themes all together?

### CODE REVIEW

**Comment by ErisDS** [comment]
@kirrg001 will test and finish this tomorrow, would appreciate an early review.

**Comment by ErisDS** [comment]
P.S. first commit is also part of it's own PR.

Middle 3 commits merge cleanly into alpha, only the last one will need a bit of fiddling because theme reading is in a different place. Should still be trivial to sort this tomorrow as well.

File: core/server/utils/packages/filter-packages.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+    return _.reduce(packages, function (result, pkg, key) {
+        var item = {};
+        if (!key.match(notAPackageRegex)) {
+            item = {
+                name: key,
+                package: pkg['package.json'] || false
+            };
+
+            if (_.indexOf(active, key) !== -1) {
+                item.active = true;
```
Comment (kirrg001) [inline core/server/utils/packages/filter-packages.js]: Where is `active` used in the code base?
e.g `availableThemes[...].active`?I could not find a usage, maybe you can help and know where this is used.

The active option makes this function a little bit un-generic, because this module is now part of packages.

Comment (kirrg001) [inline core/server/utils/packages/filter-packages.js]: Ah i think it's used in the admin right?

Comment (kevinansfield) [inline core/server/utils/packages/filter-packages.js]: In LTS `vailableThemes[...].active` is used in the Ghost-Admin, the alpha now only relies on `settings.activeTheme`

Comment (kirrg001) [inline core/server/utils/packages/filter-packages.js]: 👍 worth a comment for LTS code base
And we could remove it on master.

File: core/server/utils/packages/read-packages.js [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+            return statFile(join(packagePath, packageName)).then(function (stat) {
+                return stat.isDirectory();
+            });
+        })
+        .map(function readPackageJson(packageName) {
+            var absolutePath = join(packagePath, packageName);
+            return processPackage(absolutePath, packageName);
+        })
+        .then(function (packages) {
+            return _.keyBy(packages, 'name');
```
Comment (kirrg001) [inline core/server/utils/packages/read-packages.js]: using `keyBy` 👍

File: core/server/utils/packages/read-packages.js [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+
+            return processPackage(absolutePath, packageName)
+                .then(function gotPackage(pkg) {
+                    var res = {};
+                    res[packageName] = pkg;
+                    return res;
+                });
+        })
+        .catch(function () {
+            // @TODO: maybe log the error here?
```
Comment (kirrg001) [inline core/server/utils/packages/read-packages.js]: I would not return `{}` and instead return the error to the caller. And the caller can handle/decide.

e.g. if we read the active theme on bootstrap and it's not available - Ghost would log the error and show the user.

File: core/server/utils/packages/filter-packages.js (hunk 1 above)
Comment (ErisDS) [inline core/server/utils/packages/filter-packages.js]: Is relying on settings.activeTheme (and ostensibly, settings.activeApps) better than merging the two data structures at the API level? 

I'm easy either way, just flagging that the use case for packages is larger than just themes.

Comment (kevinansfield) [inline core/server/utils/packages/filter-packages.js]: I'd prefer it merged into the /themes or /apps endpoint personally, especially as we move towards apps where there can be multiple active. Having activate/deactivate, etc built into related endpoints would prevent a lot of logic being layered on top of the single settings endpoint.

**Comment by ErisDS** [comment]
I think this one is GTG now, just waiting for Travis to start working again.

File: core/server/utils/packages/filter-packages.js (hunk 1 above)
Comment (ErisDS) [inline core/server/utils/packages/filter-packages.js]: I think we can move towards this 👍

File: core/server/utils/packages/filter-packages.js [hunk 4]
```diff
@@ -27,6 +27,8 @@ filterPackages = function filterPackages(packages, active) {
                 package: pkg['package.json'] || false
             };
 
+            // At the moment we only support themes. This property is used in Ghost-Admin LTS
+            // It is not used in Ghost-Admin 1.0, and therefore this can be removed.
```
Comment (kirrg001) [inline core/server/utils/packages/filter-packages.js]: 👍

**Review by kirrg001 — APPROVED** [review]
LGTM 👍

**Comment by ErisDS** [comment]
Blah! I just found a bug 😭

**Comment by ErisDS** [comment]
Will supply a fix.

**Comment by ErisDS** [comment]
Bug is that there is one place where the old config structure with the the paths included IS used - and that's in errors/index.js for handling custom error templates. Will probably implement a workaround for now & a nicer fix later so we can ship the LTS.

**Comment by kirrg001** [comment]
I actually looked at this line in errors/index.js and i thought everything is fine, because we still read all files from each theme?But if you found a bug, that's good 👍

**Comment by ErisDS** [comment]
We don't still read all files, we only read package.json 😳
