### PR TITLE
Fix 404 error on short URL in private blog

### LINKED ISSUE #9578: private blogging: 404 on short urls
### Issue Summary

Ghost returns a 404 for short urls if private blogging is enabled.
Was raised in the forum: https://forum.ghost.org/t/short-url-s-returning-404/911/3

### Steps to Reproduce

1. Enabled private blogging.
2. Publish a post with e.g. 2 characters
3. Serve the post
4. 404

### Technical details:

* Ghost Version: latest
* Node Version: any
* Browser/OS: any
* Database: any

I have not investigated. We appreciate any help 🤠

### PR DESCRIPTION
**Pull request by tiendq**
close #9578
- updated check statements to disable RSS for private blog

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `grunt validate`)

### CODE REVIEW

**Comment by kevinansfield** [comment]
> What's exact failed issue? mysql?

Travis just randomly fails 😞 At times it gets rather busy and causes timeouts or failed DB connections. I've restarted the job for you.

**Comment by Tiendq** [comment]
Thank you @kevinansfield, checks are passed now :)

File: core/server/apps/private-blogging/lib/middleware.js [hunk 1]
```diff
@@ -70,7 +70,9 @@ privateBlogging = {
         // NOTE: Redirect to /private if the session does not exist.
         privateBlogging.authenticatePrivateSession(req, res, function onSessionVerified() {
             // CASE: RSS is disabled for private blogging e.g. they create overhead
-            if (req.path.lastIndexOf('/rss/', 0) === 0 || req.path.lastIndexOf('/rss/') === req.url.length - 5) {
+            let path = req.path;
+
+            if (path === '/rss' || (path.length > 4 && path.lastIndexOf('/rss/') === path.length - 5)) {
```
Comment (kirrg001) [inline core/server/apps/private-blogging/lib/middleware.js]: > path === '/rss'

This is not really needed. Ghost will redirect any request without trailing slash. The redirect middleware should/could kick-in before this logic happens, but this is unrelated to this PR. We should not take care of none trailing slash cases anywhere right now.

---

To be honest, i am not sure why this condition was written so complicated. Maybe there is a reason, but i don't get it. Originally added/extended [here](https://github.com/TryGhost/Ghost/commit/8a16dd5d7e7ab00bfe85ec7b7730dd6f82af21e8).

We need to ensure that all rss routes, expect of the private RSS url, result in a 404 response for private blogging. So we need to ensure blogs on subdirectories work, tag rss is covered, normal rss etc.

So I think we can simplify this condition to? 🤔 

> path.match(/\\/rss\\//)

Feel free to add any cases to `core/test/unit/apps/private-blogging/middleware_spec.js`.

Comment (Tiendq) [reply core/server/apps/private-blogging/lib/middleware.js]: I'm quite busy now, will take a look at it soon. Did you run the tests? Tests failed so I need to wrote it that way to cover all cases.

Comment (kirrg001) [reply core/server/apps/private-blogging/lib/middleware.js]: Yeah i did 👍

Comment (Tiendq) [reply core/server/apps/private-blogging/lib/middleware.js]: This test will fail if I don't check for `/rss` (no trailing slash).

`it('filterPrivateRoutes should 404 for /rss requests', function () {` at line 245 in `core/test/unit/apps/private-blogging/middleware_spec.js`

Comment (kirrg001) [reply core/server/apps/private-blogging/lib/middleware.js]: Yeah, not sure the test is 100% correct, because `/rss` will be redirected anyway to `/rss/`.

Alternative, we could use:

> path.match(/\\/rss\\/?/)

**Review by tiendq — COMMENTED** [review]
Use simple check with Regex

File: core/server/apps/private-blogging/lib/middleware.js [hunk 2]
```diff
@@ -70,7 +70,7 @@ privateBlogging = {
         // NOTE: Redirect to /private if the session does not exist.
         privateBlogging.authenticatePrivateSession(req, res, function onSessionVerified() {
             // CASE: RSS is disabled for private blogging e.g. they create overhead
-            if (req.path.lastIndexOf('/rss/', 0) === 0 || req.path.lastIndexOf('/rss/') === req.url.length - 5) {
+            if (req.path.match(/\/rss\/?/)) {
```
Comment (kirrg001) [inline core/server/apps/private-blogging/lib/middleware.js]: I think we need the $ at the end, otherwise it could match e.g. `/rss-post/`.

Comment (tiendq) [reply core/server/apps/private-blogging/lib/middleware.js]: Hmm, it passed all tests :). What are possibilities of RSS path? are they /rss and /tag1/tag2/rss? I think I need to add some tests too.

**Review by kirrg001 — CHANGES_REQUESTED** [review]
https://github.com/TryGhost/Ghost/pull/9628/files#r192563967

**Review by tiendq — COMMENTED** [review]
Update regex, add a test case

**Comment by kirrg001** [comment]
@tiendq Thanks :)

**Review by kirrg001 — APPROVED** [review]

File: core/server/apps/private-blogging/lib/middleware.js [hunk 3]
```diff
@@ -70,7 +70,7 @@ privateBlogging = {
         // NOTE: Redirect to /private if the session does not exist.
         privateBlogging.authenticatePrivateSession(req, res, function onSessionVerified() {
             // CASE: RSS is disabled for private blogging e.g. they create overhead
-            if (req.path.lastIndexOf('/rss/', 0) === 0 || req.path.lastIndexOf('/rss/') === req.url.length - 5) {
+            if (req.path.match(/\/rss\/?$/)) {
```
Comment (kirrg001) [inline core/server/apps/private-blogging/lib/middleware.js]: I just remembered that rss is paginated e.g. `/rss/2/`.
Regex has to be extended for that. Sorry, forgot about it 🙈

**Review by kirrg001 — CHANGES_REQUESTED** [review]
https://github.com/TryGhost/Ghost/pull/9628/files#r192741665

File: core/server/apps/private-blogging/lib/middleware.js (hunk 3 above)
Comment (tiendq) [reply core/server/apps/private-blogging/lib/middleware.js]: It's fine, I'll fix it :)

**Review by kirrg001 — CHANGES_REQUESTED** [review]
Okay i think we are finished here 😀 Thanks!

**Review by kirrg001 — APPROVED** [review]
Okay i think we are finished here 😀 Thanks!

**Comment by kirrg001** [comment]
@tiendq One last question. I remember you have added a test to ensure a two letter blog post does not result in a 404, didn't you? 🤔

**Comment by kirrg001** [comment]
> I have also added several tests for the check.

Yeah, but the original bug report is not covered :)

From #9578
> Publish a post with e.g. 2 characters
