### PR TITLE
#6893 allows navigation links directing to another port of the blog url

### LINKED ISSUE #6893: urlFor "nav" does the wrong thing when passed a port as a relative URL
If you setup a navigation item with a url that's just a port number on the same domain as configured in config.js, `urlFor` treats this like a relative path and starts adding slashes where there shouldn't be one. 

### Steps to Reproduce

1. Configure the url in `config.js` to be a URL that doesn't have a port number (it doesn't have to be right :wink: ) e.g. `http://ghost.dev`
2. In navigation, add an item which points at a port number on the same url e.g. `http://ghost.dev:3000`
3. Save the navigation item, everything will look fine in the admin panel
4. Open your theme, view the source, and see the url is output with an extra slash in the middle as well as at the end e.g. `http://ghost.dev/:3000/`

This is a bug with the logic here: https://github.com/TryGhost/Ghost/blob/c549914ae867cb3f185b159e0a11ac713e0218c3/core/server/config/url.js#L204

In the case that there's a port number which isn't included in config.js, this is effectively pointing at an external site.

### Technical details:

* Ghost Version: 0.8

### PR DESCRIPTION
**Pull request by sakulstra**
This pr fixes #6893. This allows the usage of blogurl:port inside the navigation.
- Closes #6893
- modified logic to allow urls in form of domain:port to be referenced in navigation
- added a test for a domain:port link

### CODE REVIEW

File: core/test/unit/config_spec.js [hunk 1]
```diff
@@ -355,6 +355,9 @@ describe('Config', function () {
                 testData = {nav: {url: 'http://my-ghost-blog.com/short-and-sweet/'}, secure: true};
                 config.urlFor(testContext, testData).should.equal('https://my-ghost-blog.com/short-and-sweet/');
 
+                testData = {nav: {url: 'http://my-ghost-blog.com:3000/'}};
+                config.urlFor(testContext, testData).should.equal('http://my-ghost-blog.com:3000/');
+
```
Comment (sakulstra) [inline core/test/unit/config_spec.js]: Sry for the late response - this will also succeed but I will add an additional test if you want me to ;)

Comment (kirrg001) [inline core/test/unit/config_spec.js]: yes that would be good, thank you 👍

Comment (sakulstra) [inline core/test/unit/config_spec.js]: done and passing :)

Comment (kirrg001) [inline core/test/unit/config_spec.js]: i actually meant without `http://`. But we can ignore it.

**Comment by kirrg001** [comment]
LGTM 👍

**Comment by sakulstra** [comment]
Sry removed false branch...
