### PR TITLE
Check Old Password on Password Change

### LINKED ISSUE #6620: Password change does not verify current password
### Issue Summary

Account password can be changed in the profile page without giving the current password.

### Steps to Reproduce

1. Login and go to profile page
2. Put new password without giving the current one
3. Change password

I believe it should require the previous password.

### Technical details:

* Ghost Version: 0.7.8
* Node Version: 4.4.0
* Browser/OS: Firefox/Linux
* Database: sqlite3

### PR DESCRIPTION
**Pull request by dbalders**
Closes #6620
- Changed it from always returning true, to evaluate if it is the
  current logged in user, and if so, check the old password. If not,
  ignore

password-change

### CODE REVIEW

File: core/server/models/user.js [hunk 1]
```diff
@@ -612,11 +612,17 @@ User = ghostBookshelf.Model.extend({
...
             user = _user;
-            if (userId === options.context.user) {
+            if (Number(userId) === options.context.user) {
+                // If the old password wasn't sent through, make it blank
+                if (!oldPassword) {
+                    oldPassword = '';
+                }
+                // Check the old password entered against the user's old password
                 return bcryptCompare(oldPassword, user.get('password'));
+            } else {
```
Comment (acburdine) [inline core/server/models/user.js]: Do we really need the else statement here? As the line above is returning the result of bcryptCompare and thus exiting the function, the extra else IMO isn't needed :smile:

Comment (dbalders) [inline core/server/models/user.js]: The else is necessary because if the user that is being edited is not the same user that is logged in, it should not be checking the old password and just skips that step entirely.

Comment (acburdine) [inline core/server/models/user.js]: I get that, but this:

```js
if (conditionA) {
    return someFunc();
} else {
    return true;
}
```

is equivalent to:
```js
if (conditionA) {
    return someFunc();
}

return true;
```

Honestly it isn't super important, but IMO it looks nicer without the unnecessary else.

Comment (dbalders) [inline core/server/models/user.js]: ah, i see :+1:

**Comment by ErisDS** [comment]
I've taken this for a spin and also looked at a the code a bit more closely, and I don't think this fix is correct. 

Several lines above where this fix has been added, there is an [explicit case testing for this](https://github.com/TryGhost/Ghost/blob/dc04b95fb6e6816f938aa7300bb8bac3d57eddb6/core/server/models/user.js#L607-L607), which if it was triggered, would output a different error message. At the moment, we're getting a "your password is wrong" message, rather than a "password is required" message.

Also, if I run `grunt coverage-integration`, it's easy to see that this case is not getting covered by the tests:



I think you've correctly identified the problem, that the check for `userId === options.context.user` is failing because userId is a string, not a number, but I think the fix needs to be applied much earlier.

IMO it should be fixed on line 597, where the userId is assigned, and I think it should use `parseInt` rather than Number, because that's what we use elsewhere.

It would also be good to add a test case which fails before adding the fix, and passes afterwards, covering line 606.

**Comment by dbalders** [comment]
@ErisDS good find. Updated and should be good to go now.

**Comment by ErisDS** [comment]
I'm sure there was a comment here that disappeared :confused: 

Do you have time to please look at adding a new test to [here](https://github.com/TryGhost/Ghost/blob/master/core/test/integration/api/api_users_spec.js#L1109) it should hopefully be straightforward to add the missing case for a user changing their own password and needing the oldpassword?

**Comment by dbalders** [comment]
@ErisDS ya for sure, I actually deleted the comment and that was why haha. Forgot to put the test in!

**Comment by dbalders** [comment]
test in
