### PR TITLE
🐛 Fixed Member model removing labels when unset

### LINKED ISSUE #12600: member unsubscribing from newsletter erases their membership labels
member unsubscribing from newsletter erases their membership labels
ghost 3.40.5

apply label(s) to a member and have them unsubscribe from newsletter (by clicking on link in newsletter email, didn't test via portal)

-> label(s) have disappeared

### PR DESCRIPTION
**Pull request by allouis**
closes https://github.com/TryGhost/Ghost/issues/12600

The bookshelf-relations plugin which we use will **remove** all
relations when they are set to an empty array, but will leave them alone
if it's set to undefined.

Our logic to deduplicate uppercase & lowercase version of the same label
was in advertently always setting the labels to an array, but when the
model was saved without passing the labels, this array would be empty.

Here we've added a check which will skip all label handling, if there
are no labels set.

### CODE REVIEW

File: core/server/api/canary/members.js [hunk 1]
```diff
@@ -184,7 +184,7 @@ module.exports = {
         permissions: true,
         async query(frame) {
             try {
-                frame.options.withRelated = ['stripeSubscriptions'];
+                frame.options.withRelated = ['stripeSubscriptions', 'labels'];
```
Comment (allouis) [inline core/server/api/canary/members.js:187]: Now that we don't automatically overwrite labels (and thus include them in the result) - we have to explicitly request labels in the result

File: core/server/models/member.js [hunk 2]
```diff
@@ -106,6 +106,11 @@ const Member = ghostBookshelf.Model.extend({
     onSaving: function onSaving(model, attr, options) {
         let labelsToSave = [];
 
+        if (_.isUndefined(this.get('labels'))) {
+            this.unset('labels');
```
Comment (allouis) [inline core/server/models/member.js:110]: This is to ensure that an undefined value is treated the same as the absence of a value e.g.
```js
Member.add({name: 'egg', email: 'egg@monst.er'})
Member.add({name: 'egg', email: 'egg@monst.er', labels: undefined})
```
From what I can tell, both calls will be skipped over by `bookshelf-relations` and then inserted - however the second call needs to be looked at by bookshelf relations, so that it can have the property removed before being sent to the database! 

This change ensures that consumers of the Model have a more understandable interface

Comment (rishabhgrg) [reply core/server/models/member.js:110]: Makes sense 👍

**Review by rshbhgrg — APPROVED** [review]
Its been a while so i am not 100%, but I think the explicit handling for null /undefined  seems only around thinking of cleaning up for case-insensitive labels but definitely seems to have missed the case of no labels set in API which caused the problem. The fix looks good to me 👍
