### PR TITLE
Origin Header revisited

### LINKED ISSUE #6106: Revisit origin validation
A large part of the work to get public API access to be available, involved implementing client authentication. The Ghost admin panel is a client, and is allowed to authenticate to the API via its very own client credentials. 

As a layer of security,  client authentication includes origin validation. This means that we check that requests to the API come from a permitted url. These are the urls defined in `config.js` and at the moment can be either `url` or `urlSSL`. If the origin validation fails, the client is denied access.

This means that, if at any time you try to login or access your admin panel from a URL which is not the URL set in config.js, you will see an error, and at the moment that error is not at all clear.

### The problem

At the moment, the first you might know that this is affecting you, is that you'll be unable to login. The easiest way to reproduce this right now on a standard dev install, is to try loading the admin panel from `http://127.0.0.1:2368` rather than `http://localhost:2368` and see that you can't login:

The `access denied` error message makes it look like your login has failed, when in fact, it was the admin client being denied access to the API to even try to log you in. The only other things you might see are the client console error:

And server console error:

None of which gives you a clear idea of what is wrong.

### The solution

There are a few things that we can do to improve the user experience here.

The first thing is to update the error message to be as clear as possible, both on the client side and in the server console. The error should clearly state that the problem is due to the URL not matching the one in config.js, something like:

E.g. 'Access Denied from url: xxx. Please use the url configured in config.js'

As this error is most likely to happen to people just setting up or developing on Ghost (using ngrok will cause this) we should also make sure we output one of our 3-colour error messages on the console. This should be the error, some context, and how to find the solution

- Access Denied from url: xxx. Please use the url configured in config.js
- You have attempted to access your Ghost admin panel from a url that does not appear in config.js
- For information on how to fix this, please visit http://support.ghost.org/some-new-docs-url

As well as improving the error message, it may also make sense to add both localhost and 127.0.0.1 as valid origins for `development` mode, to account for this, in the vein of having sensible defaults. If anyone has any other ideas for sensible defaults, please say :)

At some point soon, we will be adding a UI for managing clients, where you will be able to add any additional trusted domains that you want to be able to access your blog (see #4177)

- [ ] Improve the error message on the client
- [ ] Improve the error message in the server logs
- [ ] add sensible defaults like localhost and 127.0.0.1 for dev mode

### PR DESCRIPTION
**Pull request by sebgie**
closes #6106
- added override for my-ghost-blog.com
- added local IP addresses to be allowed
- changed localhost/127.0.0.1 to be allowed in production

### CODE REVIEW

File: core/server/middleware/auth.js [hunk 1]
```diff
@@ -36,15 +36,32 @@ function isBearerAutorizationHeader(req) {
...
 
     if (origin && client && client.type === 'ua' && (
-        _.some(client.trustedDomains, {trusted_domain: origin})
-        || origin === url.parse(config.url).hostname
+        _.indexOf(getIPs(), origin) >= 0
+        || _.some(client.trustedDomains, {trusted_domain: origin})
+        || origin === configHostname
+        || configHostname === 'my-ghost-blog.com'
         || origin === url.parse(config.urlSSL ? config.urlSSL : '').hostname
-        || (origin === '127.0.0.1' && isDevelopment)
```
Comment (ErisDS) [inline core/server/middleware/auth.js]: Have we lost 127.0.0.1 here?

Comment (kevinansfield) [inline core/server/middleware/auth.js]: Would 127.0.0.1 be one of the network interfaces from `os.networkInterfaces()`?

Comment (ErisDS) [inline core/server/middleware/auth.js]: Confirmed! Good :fishing_pole_and_fish:
