### PR TITLE
🐛 Fixed Content API v2 Settings browse returns relative image path

### LINKED ISSUE #10363: Content API returns relative image path for settings.icon
The Content API return absolute URLs for all images.

The settings endpoint delivers a relative path for the property `icon` like this:

`icon: "/content/images/2019/01/favicon.png"`

### PR DESCRIPTION
**Pull request by kirrg001**
closes #10363

No extra tests needed IMO.

### CODE REVIEW

File: core/server/api/v2/utils/serializers/output/utils/mapper.js [hunk 1]
```diff
@@ -70,6 +70,12 @@ const mapPost = (model, frame) => {
...
 
+const forSettings = (attrs) => {
+    url.forSetting(attrs);
+    return attrs;
+};
+
 module.exports.mapPost = mapPost;
 module.exports.mapUser = mapUser;
 module.exports.mapTag = mapTag;
+module.exports.forSettings = forSettings;
```
Comment (gargol) [inline core/server/api/v2/utils/serializers/output/utils/mapper.js]: Maybe to keep the same convention similar to above `mapTag`, `mapUser` etc. we could go with `mapSetting`?

Comment (kirrg001) [reply core/server/api/v2/utils/serializers/output/utils/mapper.js]: yeah this was a mistake 👍

**Comment by gargol** [comment]
We seem to have a default value of sort for `icon` - `/content/images/2018/04/favicon.png`. So, this test should have broken this [test](https://github.com/TryGhost/Ghost/blob/master/core/test/functional/api/v2/content/settings_spec.js#L25). I see it's using `defaultSettings.blog` but don't know why it doesn't have the `icon` value in it :thinking:
