### PR TITLE
Fixed published time and modified time for Structured data

### LINKED ISSUE #12059: Article structured data is invalid on pages
### Issue Summary

Based on the [test from Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fdemo.ghost.io%2Fabout%2F), it seems that the Article structured data is invalid on pages. It's missing `datePublished` which is identified as an "error" by the tool. Image shows correctly when you upload one. There is a "warning" about `dateModified` missing.

Screen Shot 2020-07-18 at 7 42 47 PM

Screen Shot 2020-07-18 at 7 43 00 PM

This issue only exists for page types. Posts work as expected.

### To Reproduce

1. Run a test on any Ghost page using [Google's Structured Data Tool](https://search.google.com/structured-data/testing-tool).

## Expected:

The test using the tool above should pass the way it does for posts.
- `datePublished` should be populated.
- `dateModified` should be populated.

### Technical details:

* Ghost Version: `3.22`
* Node Version: `10`

### PR DESCRIPTION
**Pull request by roshandash411**
closes #12059
Published Time and Modified Time were not populating for 'page' context because it is an extension of 'post' and hence there was no context 'page'. Fixed it by handling this scenario for published time and modified time

### CODE REVIEW

File: core/frontend/meta/context_object.js [hunk 1]
```diff
@@ -26,6 +26,13 @@ function getContextObject(data, context) {
         chosenContext = data.tag;
     } else if (_.includes(context, 'author') && data.author) {
         chosenContext = data.author;
+    } else if (_.includes(context, 'page') && data.post) {
```
Comment (ErisDS) [inline core/frontend/meta/context_object.js:29]: I'm not sure that this if statement is necessary - did you test if it gets executed?

Logically it is the exact same as:

`if ((_.includes(context, 'page') || _.includes(context, 'amp')) && data.post) {`

So I can't see that this is needed

**Review by ErisDS — CHANGES_REQUESTED** [review]
@roshandash411 thank you for this PR!
I wasn't expecting the getContextObject method to need adjusting, and I can't see a case where the extra if is needed.

If we can clean this up, this PR should be good to merge!

File: core/frontend/meta/context_object.js (hunk 1 above)
Comment (roshandash411) [reply core/frontend/meta/context_object.js]: @ErisDS Yeah you are right, my bad. I had overlooked the first statement and just saw the
 `_.includes(context, 'page') && data.page` and thought that I had missed it. Fixed it and updated the PR.

**Comment by roshandash411** [comment]
@ErisDS : Yeah you are right, my bad I had overlooked it. I have updated the PR with the fix.

**Review by ErisDS — APPROVED** [review]
