### PR TITLE
Changed featureImageALt function to allow up to 190 characters in alt…

### LINKED ISSUE #22023: API has different max length for feature_image_alt than editor. API 190 / Editor 125
### Issue Summary

Updating feature_image_alt over admin API allows 190 characters.
The Editor will only allow 125

A feature_image_alt up to 190 characters is accepted when updating a post at   `/admin/posts/{{id}}` 

When editing the same posts and saving, the error "Update failed: Feature image alt text cannot be longer than 125 characters." is displayed. See screenshot.

Image

### Steps to Reproduce

1. Update a post over API  `/admin/posts/{{id}}`  with string longer than 125 characters, ex { "feature_image_alt" : "The image shows a wet, pink-lit city street with a car in the background and a person in a coat standing in the foreground." }
2. Open the posts in Editor, attempt to save.

Expecting Editor & admin API to have the same max length, 190 characters

### Ghost Version

5.106.1-0-ga963b514+moya

### Node.js Version

N/A

### How did you install Ghost?

GhostPro

### Database type

MySQL 5.7

### Browser & OS version

N/A

### Relevant log / error output

```shell
Update failed: Feature image alt text cannot be longer than 125 characters.
```

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

### PR DESCRIPTION
**Pull request by kaimcfarlane**
### [Fixes #22023](https://github.com/TryGhost/Ghost/issues/22023)

**Summary:**
This pull request ensures that users have a seamless experience when managing feature_image_alt text, whether through the API or the Admin panel, by standardizing the character limit across both interfaces.

**Changes Implemented:**
Updated Character Limit in Admin Panel: Modified the validation logic in the Ghost Admin panel to increase the feature_image_alt character limit from 125 to 190 characters, matching the Admin API's allowance.

**Use-Case for This Change:**
Users utilizing the Admin API can set feature_image_alt text up to 190 characters. However, when editing such posts in the Admin panel, they encounter errors due to the lower character limit. This change ensures consistency between the API and Admin panel, enhancing usability and preventing potential data loss or errors during post edits.

### CODE REVIEW

**Comment by cathysarisky** [comment]
Great work, @kaimcfarlane .  I have a client who will be thrilled about this, but I think that coderabbit is right that you're off by one.  See https://github.com/TryGhost/Ghost/blob/1891c2a6bec4d4e820651f049b9b25998b844be1/ghost/core/core/server/data/schema/schema.js#L116

File: ghost/admin/app/validators/post.js [hunk 1]
```diff
@@ -205,8 +205,8 @@ export default BaseValidator.create({
     },
 
     featureImageAlt(model) {
-        if (!validator.isLength(model.featureImageAlt || '', 0, 125)) {
-            model.errors.add('featureImageAlt', 'Feature image alt text cannot be longer than 125 characters.');
+        if (!validator.isLength(model.featureImageAlt || '', 0, 190)) {
+            model.errors.add('featureImageAlt', 'Feature image alt text cannot be longer than 190 characters.');
```
Comment (cathysarisky) [inline ghost/admin/app/validators/post.js:209]:
```suggestion
            model.errors.add('featureImageAlt', 'Feature image alt text cannot be longer than 191 characters.');
```

File: ghost/admin/app/validators/post.js [hunk 2]
```diff
@@ -205,8 +205,8 @@ export default BaseValidator.create({
     },
 
     featureImageAlt(model) {
-        if (!validator.isLength(model.featureImageAlt || '', 0, 125)) {
-            model.errors.add('featureImageAlt', 'Feature image alt text cannot be longer than 125 characters.');
+        if (!validator.isLength(model.featureImageAlt || '', 0, 190)) {
```
Comment (cathysarisky) [inline ghost/admin/app/validators/post.js:208]:
```suggestion
        if (!validator.isLength(model.featureImageAlt || '', 0, 191)) {
```

**Review by cathysarisky — CHANGES_REQUESTED** [review]
