### PR TITLE
🐛fixed error for tips on subdirectory sites

### LINKED ISSUE #21123: Tips and Donation Feature - Request URL Issue
### Issue Summary

Hello, I am new to ghost so please let me know if I can offer further clarification to my problem. Thank you.

I have a self-hosted ghost install, and I updated ghost to include the tips/donation feature. 
When I visit: https://domain.com/blog/#/portal/support, there is an issue with these two requests:

session/ | 404 | fetch | FeedbackPage.js:12
create-stripe-checkout-session/ | 404 | fetch | FeedbackPage.js:12

and I see this message in the browser:

Sorry, that didn’t work.
Something went wrong, please try again later.

The request urls look like this:

Request URL: https://domain.com/members/api/session/
Request URL: https://domain.com/members/api/create-stripe-checkout-session/

however I am expecting them to be:

Request URL: https://domain.com/blog/members/api/session/
Request URL: https://domain.com/blog/members/api/create-stripe-checkout-session/

as https://domain.com/blog is what is setup in my ghost config

Also, if I visit https://domain.com/blog/#/portal/signup

this request, for example, returns 204

Fetchmember/	204	fetch	FeedbackPage.js:12

with the following request url:

Request URL: https://domain.com/blog/members/api/member/

I am trying to understand why /blog/ is not being included in the requests sent when visiting
https://domain.com/blog/#/portal/support

For example, if I run curl -i https://domain.com/blog/members/api/session/ I get a 204 response.

Thank you for your help.
- Sally

### Steps to Reproduce

Assumes self-hosted ghost installation where ghost is located here: https://domain.com/blog
Update ghost to include tips/donations
Expected request url to match and behave similarly to #/portal/signup

### Ghost Version

5.92.0

### Node.js Version

18.20.4

### How did you install Ghost?

Digital Ocean Ubuntu

### Database type

MySQL 8

### Browser & OS version

_No response_

### Relevant log / error output

_No response_

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

### PR DESCRIPTION
**Pull request by cathysarisky**
closes #21123 

There was an error in the calculation of the site's url for sites setup as subdirectories (yoursite/blog instead of just yoursite/).

Fixed and tested with a manual build of portal.  There's apparently a gap in test coverage here, as it passed both before and after...

### CODE REVIEW

File: apps/portal/src/components/pages/SupportPage.js [hunk 1]
```diff
@@ -8,12 +8,12 @@ const SupportPage = () => {
...
     const [disabledFeatureError, setDisabledFeatureError] = useState(null);
-    const {member, t} = useContext(AppContext);
+    const {member, t, site} = useContext(AppContext);
 
     useEffect(() => {
         async function checkoutDonation() {
-            const siteUrl = window.location.origin;
-            const currentUrl = siteUrl + window.location.pathname;
+            const siteUrl = site.url;
+            const currentUrl = window.location.href.split('#')[0];
```
Comment (sagzy) [inline apps/portal/src/components/pages/SupportPage.js:16]: I'd suggest keeping `const currentUrl = window.location.origin + window.location.pathname`, so that both hash fragments and query parameters are stripped from the resulting URL.

**Review by sagzy — COMMENTED** [review]
Hey @cathysarisky!

Thanks for the fix 🙏 I can replicate the bug without the fix, and the bug is gone with your fix 🙌 

Added one comment
