### PR TITLE
🎨 fix admin and theme caching issues

### LINKED ISSUE #7958: Ghost-Admin assets are cached in development mode
### Issue Summary

Similar to https://github.com/TryGhost/Ghost/issues/7812 the admin JS files are being cached when running Ghost in development mode requiring Web Inspector to be open constantly with the "disable cache when open" option checked.

### Steps to Reproduce

1. Start ghost in development mode `gulp dev`
2. Open the admin area in a web browser
3. Make a change to the admin JS files (easiest thing is to add a bit of text to a template)
4. Refresh the screen, note that the change is not present
5. Clear the cache or open web inspector with the "disable cache when open" option checked
6. Refresh the screen, not that the change is now present

We shouldn't be caching any admin assets whilst in development mode as in the best case it creates fiction and in the worst case can cause developers to fall into traps thinking that their changes are broken.

### Technical details:

* Ghost Version: master (needs checking on LTS)
* Node Version: 4.7.0
* Browser/OS: Chrome/macOS

### PR DESCRIPTION
**Pull request by acburdine**
refs #7812, closes #7958
- fixes boolean logic wrt to theme cache value from config
- disable cache for admin assets in development
- only add asset hash in production

### CODE REVIEW

File: core/server/admin/app.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ module.exports = function setupAdminApp() {
     // @TODO ensure this gets a local 404 error handler
     adminApp.use('/assets', serveStatic(
         config.get('paths').clientAssets,
-        {maxAge: utils.ONE_YEAR_MS, fallthrough: false}
+        {maxAge: (config.get('env') === 'production') ? utils.ONE_YEAR_MS : 0, fallthrough: false}
```
Comment (acburdine) [inline core/server/admin/app.js]: I thought about making this configurable via config - but as the admin app is really an integral part of Ghost itself (as in people can't edit or re-upload the admin client), it seemed unnecessary.

File: core/server/data/meta/asset_url.js [hunk 2]
```diff
@@ -39,11 +39,13 @@ function getAssetUrl(path, isAdmin, minify) {
         // we don't want to concat the path with our favicon url
         output += path;
 
-        if (!config.get('assetHash')) {
-            config.set('assetHash', utils.generateAssetHash());
-        }
+        if (config.get('env') === 'production') {
```
Comment (acburdine) [inline core/server/data/meta/asset_url.js]: This might actually be unnecessary, the asset hash wasn't what was causing the issue. However @JohnONolan  mentioned that we shouldn't be using asset hashes in development, so this removed them.

File: core/server/middleware/static-theme.js [hunk 3]
```diff
@@ -20,8 +20,10 @@ function forwardToExpressStatic(req, res, next) {
     if (!req.app.get('activeTheme')) {
         next();
     } else {
+        var configMaxAge = config.get('caching:theme:maxAge');
+
         express.static(path.join(config.getContentPath('themes'), req.app.get('activeTheme')),
-            {maxAge: config.get('caching:theme:maxAge') || utils.ONE_YEAR_MS}
+            {maxAge: (configMaxAge || configMaxAge === 0) ? configMaxAge : utils.ONE_YEAR_MS}
```
Comment (acburdine) [inline core/server/middleware/static-theme.js]: We have to explicitly check for a value of "0" here since it's a falsey value and JS will ignore it 😛

File: core/server/admin/app.js (hunk 1 above)
Comment (kirrg001) [inline core/server/admin/app.js]: I would add this to production config (as we do for theme caching), because we would like to avoid having the env checks everywhere.

File: core/server/data/meta/asset_url.js (hunk 2 above)
Comment (kirrg001) [inline core/server/data/meta/asset_url.js]: I would suggest, if this is unnecessary or not related to caching, it shouldn't be part of the PR. If we need an issue, let's raise it 👍

File: core/server/middleware/static-theme.js (hunk 3 above)
Comment (kirrg001) [inline core/server/middleware/static-theme.js]: yeah good point 👍

File: core/server/data/meta/asset_url.js (hunk 2 above)
Comment (JohnONolan) [inline core/server/data/meta/asset_url.js]: AFAIK this still very much causes browser cache issues - unless the hashes are being changed on every single build, which seems to defeat the purpose ? I don't know why we need this in dev

I'm more than happy to be wrong though - if someone has better info

Comment (kevinansfield) [inline core/server/data/meta/asset_url.js]: It shouldn't have any effect on browser caching - the problem was that we were setting long-expires cache headers in dev mode, we would have had the same problem with or without the hash.

Normally asset hashes would work around the long-expires cache header because they would be re-generated any time the file contents change but we only have a poor-mans asset hash as an escape valve to force a re-download of assets after a server restart - this was why users were reporting they had to restart their server to see any changes. If we didn't have the asset hash they wouldn't see any changes until they cleared their cache.

Comment (acburdine) [inline core/server/data/meta/asset_url.js]: At any rate - I think I'll remove this from the PR -> it _shouldn't_ cause issues with caching and we can re-evaluate disabling it in dev mode at a later time.

**Review by kirrg001 — APPROVED** [review]
