### PR TITLE
🐛  Fix double slash in scheduling API URL

### LINKED ISSUE #8568: Scheduling api url is not correctly composed.
### Issue Summary
When I debugged your scheduling process, I noticed that api requests from post-scheduling adapter goes with double-slash part in url (see screenshot https://cl.ly/2K2a1P2N1Q0t).
That's happened cause here https://cl.ly/352p1K1f3Z3Z in your code, apiUrl is already with trailing slash.

I had a problem with that, cause my NGINX configured to remove double(tripple ..) slashes, and your scheduling doesn't works properly. 

Thanks

### PR DESCRIPTION
**Pull request by aileen**
closes #8568

Use our `urlJoin` util to concatenate the URL (not the query part of it, as this is not supported in `urlJoin`) and to prevent possible missing or double slashes, as `config.apiUrl` could be with or without trailing slash.

### CODE REVIEW

**Comment by kevinansfield** [comment]
Code looks fine but I'm wondering if we should add a test to avoid regressions and confirm the fix is doing what it's supposed to be doing?

File: core/server/adapters/scheduling/post-scheduling/index.js [hunk 1]
```diff
@@ -14,7 +15,7 @@ _private.normalize = function normalize(options) {
 
     return {
         time: moment(object.get('published_at')).valueOf(),
-        url: apiUrl + '/schedules/posts/' + object.get('id') + '?client_id=' + client.get('slug') + '&client_secret=' + client.get('secret'),
+        url: utils.url.urlJoin(apiUrl + '/schedules/posts/' + object.get('id')) + '?client_id=' + client.get('slug') + '&client_secret=' + client.get('secret'),
```
Comment (kirrg001) [inline core/server/adapters/scheduling/post-scheduling/index.js]: This looks a bit confusing.

`utils.url.urlJoin(apiUrl + '/schedules/posts/' + object.get('id'))`

vs.

`utils.url.urlJoin(apiUrl, '/schedules/posts', object.get('id'))`
`utils.url.urlJoin(apiUrl, 'schedules', 'posts', object.get('id'))`

Comment (AileenCGN) [inline core/server/adapters/scheduling/post-scheduling/index.js]: 💯

**Review by kirrg001 — APPROVED** [review]
