### PR TITLE
"url" field is undefined when restricting returned fields via the API

### LINKED ISSUE #6625: "url" field is undefined when restricting returned fields via the API
### Issue Summary
When querying a posts list with the API, the "url" field returns "undefined" if the fields to be returned have been specified.

Interestingly, if one wants to construct a full list of post urls with no further information, a list of all fields except the url is returned.

### Steps to Reproduce

This first query returns a list of all posts with all their fields.
````
$.get(ghost.url.api('posts', {limit: "all"})).done(function(data) {
    var allposts = data.posts;
    console.log(allposts);
})
````

The following query, which should return exactly the same thing, returns all fields except "url" and "author".
 ````
$.get(ghost.url.api('posts', {limit: "all", fields: "id,uuid,title,slug,markdown,html,image,featured,page,status,language,meta_title,meta_description,created_at,created_by,updated_at,updated_by,published_at,published_by,author,url"})).done(function(data) {
    var allfields = data.posts;
    console.log(allfields);
})
````
The "author" can be added by using "include: "author", so this may be a feature and not a bug.
Using the syntax author_id also returns the expected result.

To test what happens if a list of URLs needs to be generated, the following query can be used :
````
$.get(ghost.url.api('posts', {limit: "all", fields: "url"})).done(function(data) {
    var urlquery = data.posts;
    console.log(urlquery);
})
````

### Technical details:

* Ghost Version: 0.7.8
* Node Version: 2.14.7
* Browser/OS: all tested.
* Database: sqlite3

### PR DESCRIPTION
**Pull request by vkandy**
Closes #6625 

`GET /posts` query with `?field=url` as query string returns "undefined" as url value. The `url` property is constructed from id, published_dt, and slug. Post instances are loaded with attributes given in `fields` parameter. If the `fields` parameter doesn't contain `id`, `published_dt`, and `slug`, URL can't be constructed and undefined is returned.

Fix was to load the 3 required properties when `field` parameter contains `url`. Response is sent after filtering out any properties that were not requested.
- "url" and "author" fields depend on {id, published_at, slug, author_id} to construct post url.
- results are transformed by filtering out additional properties to return just the requested fields

### CODE REVIEW

**Comment by vkandy** [comment]
Please review.

Response returns `author_id` when `?field=author` is passed. Do we return name or id or both? The docs aren't clear: http://api.ghost.org/docs/fields

**Comment by ErisDS** [comment]
The author/author_id aspect is a slightly blurry boundary because it is a related object.

Posts have a `field` called `author_id` and a related object called `author`. Usually control over this is provided by using `?include=author` to include the full related object instead of the id. 

Ideally at this point, you would be able to say `include=author&fields=author.name` in order to get just an author name, but handling joins in fields is a separate issue.

**Comment by ErisDS** [comment]
I have tested this out with the reproduction steps [listed in this comment](https://github.com/TryGhost/Ghost/issues/6625#issuecomment-232625892) and am no longer able to reproduce either bug 😉

**Comment by vkandy** [comment]
Added a test case for this fix. Good for review.

**Comment by kirrg001** [comment]
i was able to reproduce with postman. will review

File: core/server/api/posts.js [hunk 1]
```diff
@@ -55,7 +55,27 @@ posts = {
...
          */
         function modelQuery(options) {
-            return dataProvider.Post.findPage(options);
+            var requestedColumns = [];
+
+            // 'url' and 'author' depend on other columns. Make sure to load them.
+            if (_.isArray(options.columns)) {
+                requestedColumns = _.clone(options.columns);
+                if (_.includes(options.columns, 'url') || _.includes(options.columns, 'author')) {
+                    options.columns.push('id', 'published_at', 'slug', 'author_id');
```
Comment (kirrg001) [inline core/server/api/posts.js]: instead of defining a specific solution here, i would suggest making this part of the model logic. something like pseudo:

```
fetchPage
  if (options.columns) {
     // only allow permitted columns
     options.columns = _.intersection(options.columns, this.prototype.permittedAttributes());

     // ensure minimum required columns for further logic
     options.columns union this.defaultColumnsToFetch();
  }

// per model (can be empty)
defaultColumnsToFetch: function()
   return 'id, slug....';
```

Comment (vkandy) [inline core/server/api/posts.js]: Just to make sure we are on the same page... I think we only need these 4 extra properties when `url` or `author` is present in the `fields` parameter. 
Do we treat them as default columns to fetch if at least 1 column is requested?

Comment (kirrg001) [inline core/server/api/posts.js]: there are two ways: either we fetch by default almost everything and pick what the user has requested for (maybe a performance issue) or we always fetch a minimum set of attributes per model (depends what each model needs minimum to fulfil its needs).

in this case: there is a somewhere a piece of logic in the `toJSON` fn to generate a dynamic URL, which depends on a set of attributes. in my opinion we shouldn't add a another piece of logic somewhere in a controller, so that the `toJSON` will not return undefined.

**Comment by vkandy** [comment]
Based on @kirrg001 suggestion above, implemented a more generic solution. Base class for models defines `defaultColumnsToFetch()` which is overridden by subclasses. In this case, Posts overrides this method and returns `['id', 'published_at', 'slug', 'author_id']`.

`findPage()` loads model instances by performing union of permitted columns and default columns declared by models. 

Finally, the response from `toJSON()` is filtered and only columns requested by the client are returned.

File: core/server/models/base/index.js [hunk 2]
```diff
@@ -355,14 +362,21 @@ ghostBookshelf.Model = ghostBookshelf.Model.extend({
         }
 
         return itemCollection.fetchPage(options).then(function formatResponse(response) {
-            var data = {};
+            options.columns = allColumns;
```
Comment (kirrg001) [inline core/server/models/base/index.js]: suggestion:
now that we extend `options.columns`, maybe we can rename `allColumns` to `requestedColumns` (or something similar)

File: core/server/models/base/index.js [hunk 3]
```diff
@@ -355,14 +362,21 @@ ghostBookshelf.Model = ghostBookshelf.Model.extend({
...
+            var models = response.collection.toJSON(options);
 
             // re-add any computed properties that were stripped out before the call to fetchPage
-            options.columns = allColumns;
-            data[tableName] = response.collection.toJSON(options);
-            data.meta = {pagination: response.pagination};
+            // pick only requested before returning JSON
+            return Promise.map(models, function (model) {
```
Comment (kirrg001) [inline core/server/models/base/index.js]: suggestion: 
no need to use `Promise.map`, here is no async operation happening. 
```
// pick only requested ...
models = _.map(models, function(model) {...});
```

**Comment by ErisDS** [comment]
The failing lint build was a random travis error - this is green now!

**Comment by vkandy** [comment]
As per the suggestions above, renamed `allColumns` to `requestedColumns` (these are the attributes client asked for).
Replaced `Promise.map()` with `_.map()`. My rationale was that we could benefit from concurrency on large arrays but I guess the savings are minimal and `_.map` is more readable.
