### PR TITLE
💄 Improve URL consistency, Part 2: urlFor('home')

### LINKED ISSUE #7666: Audit & Overhaul of the URL utilities
This is an audit & overhaul issue. We could spend forever on it, the idea is to spend a small amount of time and significantly reduce the number of issues. The long tail of edgecases get cleaned up over time.

The audit centres around the `utils/url.js` file & how the utilities inside it are structured and used.

First, there are one or two known issues:

## Audit:

Review & fix the following bugs:
- [x] Fix GhostAuth redirect uri mismatch error for urls with a trailing slash. #7656
- [ ] Canonical vs logo blog URLs being output differently i.e. one has a trailing slash and one doesn't  (reported in slack, could have been a theme issue).
- [ ] Audit the codebase for use of the `urlJoin` and `urlFor` functions:
    - where they are used, are they used correctly? Consider how they are used to try to identify any small improvements
    - is there anywhere that they should be used and are not? All internal Ghost urls should be either fetched from `urlFor` or concatenated using `urlJoin` never `+`.
- [ ] Review recent url & subdirectory related issues, and check to see if the changes in 1.0 have caused any regressions
- [ ] Check the test coverage for the utilities, and any places in the codebase where the utilities are heavily used.

## Overhaul:
- [ ] if test coverage is found to be lacking, improve this
- [ ] make any small improvements that have been identified
- [ ] summarise findings & write a new issue to cover any larger changes that you'd like to make

### PR DESCRIPTION
**Pull request by aileen**
closes #7666

Using `urlFor('home')` instead `config.get('url')` in Ghost.
When `urlFor('home', true)` returns the absolute adress of the blog as defined in the config.
Will always return a trailing `/`.

### CODE REVIEW

File: core/server/apps/subscribers/lib/helpers/subscribe_form.js [hunk 1]
```diff
@@ -43,6 +43,7 @@ subscribeScript =
 subscribe_form = function (options) {
     var root = options.data.root,
         data = _.merge({}, options.hash, _.pick(root, params), {
+            // @TODO: shall we use `urlJoin` here instead of `path.join`?
```
Comment (ErisDS) [inline core/server/apps/subscribers/lib/helpers/subscribe_form.js]: Yes definitely, path.join will give it a `\` on windows.

Comment (AileenCGN) [inline core/server/apps/subscribers/lib/helpers/subscribe_form.js]: Is this something, we should do globally? Found some more places where we could use `urlJoin` instead of `path.join`...

Comment (ErisDS) [inline core/server/apps/subscribers/lib/helpers/subscribe_form.js]: Quite possibly.

Path should be for anything to do with fs, url for anything accessed via HTTP

Comment (AileenCGN) [inline core/server/apps/subscribers/lib/helpers/subscribe_form.js]: > Path should be for anything to do with fs, url for anything accessed via HTTP
If we're going to audit/refactor the usage `path.join()` in a new PR, this is ready to go.

**Comment by AileenCGN** [comment]
@kirrg001 this is ready for review!

File: core/server/api/authentication.js [hunk 2]
```diff
@@ -216,8 +216,10 @@ authentication = {
         }
 
         function sendResetNotification(data) {
-            var baseUrl = config.get('forceAdminSSL') ? (config.get('urlSSL') || config.get('url')) : config.get('url'),
-                resetUrl = globalUtils.url.urlJoin(baseUrl, 'ghost/reset', globalUtils.encodeBase64URLsafe(data.resetToken), '/');
+            var baseUrl = config.get('forceAdminSSL') ? globalUtils.url.urlFor('home', {secure: true}, true) : globalUtils.url.urlFor('home', true),
```
Comment (kirrg001) [inline core/server/api/authentication.js]: In this case we are generating the home url/base url, which is the blog url, not the admin url.
I wonder, why do we ask for `config.get('forceAdminSSL')`?I know you didn't change this logic.

File: core/server/api/settings.js [hunk 3]
```diff
@@ -65,7 +65,7 @@ updateConfigCache = function () {
     config.set('theme:twitter', (settingsCache.twitter && settingsCache.twitter.value) || '');
     config.set('theme:facebook', (settingsCache.facebook && settingsCache.facebook.value) || '');
     config.set('theme:timezone', (settingsCache.activeTimezone && settingsCache.activeTimezone.value) || config.get('theme').timezone);
-    config.set('theme:url', config.get('url') ? generalUtils.url.urlJoin(config.get('url'), '/') : '');
+    config.set('theme:url', globalUtils.url.urlFor('home', true));
```
Comment (kirrg001) [inline core/server/api/settings.js]: I made a project search and we are almost *always* using absolute home urls. Could we made this as default?

File: core/server/api/authentication.js [hunk 4]
```diff
@@ -216,8 +216,10 @@ authentication = {
...
+                resetUrl = baseUrl.replace(/\/$/, '') +
```
Comment (kirrg001) [inline core/server/api/authentication.js]: you can use `urlJoin` in this case.

File: core/server/api/configuration.js [hunk 5]
```diff
@@ -27,7 +28,7 @@ function getBaseConfig() {
         fileStorage:    config.get('fileStorage') !== false,
         useGravatar:    !config.isPrivacyDisabled('useGravatar'),
         publicAPI:      config.get('publicAPI') === true,
-        blogUrl:        config.get('url').replace(/\/$/, ''),
```
Comment (kirrg001) [inline core/server/api/configuration.js]: A project search shows me that we are also using `config.get('urlSSL')` without the url helper.
Shouldn't we use `utils.url.urlFor('home', {secure: true}, true)` in this case?

**Review by kirrg001 — CHANGES_REQUESTED** [review]
All looks good. Added some smaller comments/questions. Thanks for tidying this up 👍

File: core/server/api/configuration.js (hunk 5 above)
Comment (AileenCGN) [inline core/server/api/configuration.js]: Bummer... This one slipped through.

Comment (kirrg001) [inline core/server/api/configuration.js]: Will reconsider my comment, as we force ssl when secure is true and `urlSSL` is not present.

File: core/server/api/authentication.js [hunk 6]
```diff
@@ -216,8 +216,8 @@ authentication = {
         }
 
         function sendResetNotification(data) {
-            var baseUrl = config.get('forceAdminSSL') ? (config.get('urlSSL') || config.get('url')) : config.get('url'),
-                resetUrl = globalUtils.url.urlJoin(baseUrl, 'ghost/reset', globalUtils.encodeBase64URLsafe(data.resetToken), '/');
+            var baseUrl = config.get('forceAdminSSL') ? globalUtils.url.urlFor('home', {secure: true}, true) : globalUtils.url.urlFor('home', true),
+                resetUrl = globalUtils.url.urlJoin(baseUrl.replace(/\/$/, ''), '/ghost/reset/', globalUtils.encodeBase64URLsafe(data.resetToken), '/');
```
Comment (kirrg001) [inline core/server/api/authentication.js]: If you are using `urlJoin`, you don't have to manually delete the trailing slash from the baseUrl.

File: core/server/api/configuration.js (hunk 5 above)
Comment (kirrg001) [inline core/server/api/configuration.js]: The problem with this is the following:
`getBaseUrl` was designed to force SSL if the users request is secure, but the config url is configured to http. In this case we force SSL and replace the protocol. So the secure option should always depend on the request. 
See https://github.com/TryGhost/Ghost/issues/6270

It would be great to add a comment to this function. 
I went again through the usages and most of the use cases only check if the config is available at all and then do an action. So nothing TODO here except of adding a comment for the `getBaseUrl` fn.

File: core/server/api/authentication.js [hunk 7]
```diff
@@ -216,8 +216,8 @@ authentication = {
         }
 
         function sendResetNotification(data) {
-            var baseUrl = config.get('forceAdminSSL') ? (config.get('urlSSL') || config.get('url')) : config.get('url'),
-                resetUrl = globalUtils.url.urlJoin(baseUrl, 'ghost/reset', globalUtils.encodeBase64URLsafe(data.resetToken), '/');
+            var baseUrl = config.get('forceAdminSSL') ? globalUtils.url.urlFor('home', {secure: true}, true) : globalUtils.url.urlFor('home', true),
```
Comment (kirrg001) [inline core/server/api/authentication.js]: In this case it makes sense to ask for `config.get('forceAdminSSL')`, because `/ghost` depends on the admin url! But there are cases in the code base where it does not make sense e.q. in `core/server/mail/utils.js`. It would be great to go over the cases again and verify it's correct or not.

**Review by kirrg001 — APPROVED** [review]
