### PR TITLE
✨ Use node-archiver to create zips

### LINKED ISSUE #7266: Downloading a large theme causes an error
When trying to download a theme with a lot of files (E.g. with a bunch of development-related files like node-modules), I see the following error:

```
ERROR: stdout maxBuffer exceeded 
 
 Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:266:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:536:20) 
```

### Steps to Reproduce

Example file:
[casper-with-nodemodules.zip](https://github.com/TryGhost/Ghost/files/436178/casper-with-nodemodules.zip)

1. Add this theme to your content/themes directory 
2. Attempt to download it

### LINKED ISSUE #7267: Theme uploader/downloader assumes ownership of `content/themes`
Whilst playing around trying to understand the download bug #7266 I lost a zip file that I didn't expect to lose.

### Steps to Reproduce

1. Create a new theme for testing purposes in content/themes/themename
2. Compress that theme, so you can test uploading it, it should live at content/themes/themename.zip
3. Uploading the theme
4. See the overwrite warning - cool, Ghost gets permission to overwrite my folder
5. After the theme is uploaded, the zip file you uploaded from is gone without permission

I understand why this is happening & that I'm doing a weird thing by uploading a file from the same directory it's about to be uploaded to, however the removal of the file is unexpected. I think zip files that are uploaded need to be stored somewhere temporary, and then deleted from the temporary location.

### PR DESCRIPTION
**Pull request by ErisDS**
closes #7266, closes #7267
- Adds node-archiver as a dependency
- Adds new zip-folder utility
- Switch out exec 'zip' for zip folder utility
- Store generated zips in os.tmpdir
- Don't delete zips from content/themes when uploading
- Fixes path resolution for delete

### CODE REVIEW

**Comment by ErisDS** [comment]
Have updated to not delete zip files from `content/themes`

File: core/server/api/themes.js [hunk 1]
```diff
@@ -74,15 +74,6 @@ themes = {
...
             .then(function () {
-                return storageAdapter.exists(config.paths.themePath + '/' + zip.name);
-            })
-            .then(function (zipExists) {
-                // delete existing theme zip
-                if (zipExists) {
-                    return storageAdapter.delete(zip.name, config.paths.themePath);
-                }
-            })
-            .then(function () {
```
Comment (kirrg001) [inline core/server/api/themes.js]: you also need to delete the code in destroy theme 👍

File: core/server/utils/zip-folder.js [hunk 2]
```diff
@@ -0,0 +1,20 @@
+var archiver = require('archiver'),
+    fs = require('fs');
+
+module.exports = function zipFolder(folderToZip, destination, callback) {
+    var output = fs.createWriteStream(destination),
```
Comment (kirrg001) [inline core/server/utils/zip-folder.js]: https://github.com/archiverjs/node-archiver/issues/148
We can add this later if you want 👍
