### PR TITLE
🐛  Add `published_at` to post model fixtures

### LINKED ISSUE #8562: Previous and next posts not rendered for welcome posts
### Issue Summary

After populating the db with the new welcome posts fixtures, no previous or next posts at the bottom of each post is rendered. The reason for that might be for the `published_at` date not being populated within the fixtures.

### Steps to Reproduce

1. Fresh install of Ghost beta (fresh db init) to see the new welcome posts fixtures
2. Click on any post
3. See, that there's no 'read next' section at the bottom
4. Add a new post
5. See that the section appears, but with wrong content

### Expected behaviour

Click on the first welcome post, see the second one in 'Read next' section.
Click on the second welcome post, see the previous and the next one. And so on...

### Technical details:

* Ghost Version: 1.0 beta-1
* Node Version: 4.5
* Database: sqlite/MySQL

### PR DESCRIPTION
**Pull request by aileen**
closes #8562

Before we create our model fixtures, we assign a `published_at` property with a difference of 1 second for each blog post, so the `prev_post` and `next_post` helper work correctly. This fixed also an issue, where the order of the fixtures wasn't correct.

### CODE REVIEW

File: core/server/data/migrations/init/2-create-fixtures.js [hunk 1]
```diff
@@ -10,6 +11,15 @@ module.exports = function insertFixtures(options) {
 
     return Promise.mapSeries(fixtures.models, function (model) {
         logging.info('Model: ' + model.name);
+
+        // The Post model fixtures need a `published_at` date, where at least the seconds
+        // are different, otherwise `prev_post` and `next_post` helpers won't workd with
+        // them.
+        if (model.name === 'Post') {
+            _.forEach(model.entries, function (post, key) {
```
Comment (kevinansfield) [inline core/server/data/migrations/init/2-create-fixtures.js]: I think `key` should be renamed to `index` here to avoid confusion. General naming rules are that a `key` relates to the name of a value on an object (usually a string), e.g. `foo["bar"]` and `index` relates to the position in an array (always an integer), e.g. `foo[1]`.

**Review by kevinansfield — CHANGES_REQUESTED** [review]
Minor naming change but otherwise everything looks good 👍

File: core/server/data/migrations/init/2-create-fixtures.js (hunk 1 above)
Comment (AileenCGN) [inline core/server/data/migrations/init/2-create-fixtures.js]: Ok! Makes sense!

**Comment by AileenCGN** [comment]
If the code seems ok, this is ready for merging! I tested it with sqlite and MySQL.

**Review by kevinansfield — APPROVED** [review]

File: core/server/data/migrations/init/2-create-fixtures.js [hunk 2]
```diff
@@ -10,6 +11,15 @@ module.exports = function insertFixtures(options) {
 
     return Promise.mapSeries(fixtures.models, function (model) {
         logging.info('Model: ' + model.name);
+
+        // The Post model fixtures need a `published_at` date, where at least the seconds
+        // are different, otherwise `prev_post` and `next_post` helpers won't workd with
+        // them.
+        if (model.name === 'Post') {
+            _.forEach(model.entries, function (post, index) {
+                post.published_at = moment().add(index, 'seconds');
```
Comment (kirrg001) [inline core/server/data/migrations/init/2-create-fixtures.js]: Is there a reason why this is not part of the post model layer? 🤔 

All the post fixtures are published posts and if a published post misses the `published_at` property, the model layer should handle this? e.g. we can disallow it for public usage, but internal usage will generate the date.

Comment (kevinansfield) [inline core/server/data/migrations/init/2-create-fixtures.js]: It would be a bit odd having something in the model layer that's only relevant to fixtures? I don't think the model layer should be randomly adding time to the `published_at` field but I could be wrong.

My initial thoughts were to manually specify the `published_at` date strings in the `fixtures.json` file but this seemed to work just as well.

Comment (kirrg001) [inline core/server/data/migrations/init/2-create-fixtures.js]: Yeah either as strings in the `fixtures.json` or handled model layer.

In my opinion, the model defines what is allowed and handles fallbacks and conditions in a centralised place. 

I can think of a valid case, that a public write access adds a post, which is published without a published date. But for now we can limit the `published_at` fallback for internal usage.

Comment (kevinansfield) [inline core/server/data/migrations/init/2-create-fixtures.js]: > I can think of a valid case, that a public write access adds a post, which is published without a published date. But for now we can limit the published_at fallback for internal usage.

The fallback in the model layer is already `new Date()` when `published_at` is not set which in general is fine, the problem was specific to fixtures because we were creating multiple posts almost instantaneously and `published_at` only has a resolution of seconds which was breaking prev/next handling.

If it becomes a problem for production sites I'd be inclined to change the date storage format so that we have millisecond resolution instead of resorting to adding seconds to `published_at` values here and there.

Comment (kirrg001) [inline core/server/data/migrations/init/2-create-fixtures.js]: > If it becomes a problem for production sites I'd be inclined to change the date storage format so that we have millisecond resolution instead of resorting to adding seconds to published_at values here and there.

The default `dateTime` type can't store MS. This would be a big change.

---

@AileenCGN 
We have a fixture utility, which was written for fixtures. This allows us to write a JSON file for the initial blog data. Having a hack inside the migration script works, but imagine every fixture requirement adds a hack somewhere. So it would be great if this condition here get's moved to our fixture utility. 

Having dates in our fixtures was never a requirement, but as soon as we have a second use case, we should add support for it e.g. textual parsing `published_at: now() + ...` (can be done via a moment plugin for sure)
