### PR TITLE
🐛 Fixed sqlite constraint error caused by updating a member email with an already existing email

### LINKED ISSUE #12045: SQLite constraint error when editing member email
### Issue Summary

Editing the email of a member to one that already exists causes Ghost to throw an error because the email field would no longer be unique.

```
[2020-07-14 12:46:07] ERROR "PUT /ghost/api/v3/admin/members/5f0d9afac6aef4cd5b400a7e/?include=labels" 500 30ms

update `members` set `uuid` = 'bf596234-a8c8-4d6b-9493-46bca691d781', `email` = 'test@test.com', `name` = 'cool', `note` = NULL, `geolocation` = NULL, `subscribed` = true, `created_at` = '2020-07-14 11:46:02', `created_by` = '1', `updated_at` = '2020-07-14 11:46:07', `updated_by` = '1' where `id` = '5f0d9afac6aef4cd5b400a7e' - SQLITE_CONSTRAINT: UNIQUE constraint failed: members.email

Error ID:
    9afbd2e0-c5c7-11ea-9763-dbdfbe7e02a4

Error Code:
    SQLITE_CONSTRAINT

----------------------------------------

InternalServerError: update `members` set `uuid` = 'bf596234-a8c8-4d6b-9493-46bca691d781', `email` = 'test@test.com', `name` = 'cool', `note` = NULL, `geolocation` = NULL, `subscribed` = true, `created_at` = '2020-07-14 11:46:02', `created_by` = '1', `updated_at` = '2020-07-14 11:46:07', `updated_by` = '1' where `id` = '5f0d9afac6aef4cd5b400a7e' - SQLITE_CONSTRAINT: UNIQUE constraint failed: members.email
    at new GhostError (/home/neo/ghost/Ghost/node_modules/@tryghost/errors/lib/errors.js:10:26)
................

Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: members.email
```

### To Reproduce

From Ghost Admin:

1. Create a member with email `test@test.com`
1. Create a second member with email `test2@test.com`
1. Edit the second member email to be `test@test.com` and save.
1. See error in Ghost Admin and Ghost console.

image

There should be a check on the incoming email to ensure it doesn't already exist before trying to save.

Originating from Sentry: https://sentry.io/organizations/ghost-foundation/issues/1634959159/

### Technical details:

* Ghost Version: 3.25.0
* Node Version: 12.18.0
* Browser/OS: Firefox/Linux
* Database: SQLite

### PR DESCRIPTION
**Pull request by imox2**
🐛 Fixed sqlite constraint error caused by updating a member email with an already existing email of different member

closes #12045
- on editing a member, if email is updated to an already existing email of
different member
  - it causes sqlite to throw an error because the email would no longer
    be unique. This was not handled and error was sent to Frontend and
    shown to user
    - Added a try catch, and if it is duplicated email problem threw a
    Validation Error
    - else member is updated successfully

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test` and `yarn lint`)

### CODE REVIEW

**Comment by imox2** [comment]
@naz can you please review it. Thanks

File: test/regression/api/canary/admin/members_spec.js [hunk 1]
```diff
@@ -494,7 +494,7 @@ describe('Members API', function () {
             });
     });
 
-    it('Fails to import memmber duplicate emails', function () {
+    it('Fails to import member duplicate emails', function () {
```
Comment (naz) [inline test/regression/api/canary/admin/members_spec.js:497]: :sweat_smile: :heavy_plus_sign: :+1:

File: core/server/translations/en.json [hunk 2]
```diff
@@ -251,6 +251,10 @@
                 "memberAlreadyExists": {
                     "message": "Member already exists",
                     "context": "Attempting to add member with existing email address."
+                },
+                "memberAlreadyExistsWithEmail": {
+                    "message": "Different member already exists with edited email",
+                    "context": "Attempting to edit member email to an existing email address."
```
Comment (naz) [inline core/server/translations/en.json:257]: @imox2 would rather reuse the error message above - `memberAlreadyExists`. To make it work for both add/edit actions can make the `add` word in the context a parameter. This way wording would stay more consistent and less copy to maintain in the future. For reference, you could check how parameterized errors are used [here](https://github.com/TryGhost/Ghost/blob/c8a6939b2edf8a4e4bdd705f4158be919713c57f/core/server/translations/en.json#L445-L450).

**Review by naz — CHANGES_REQUESTED** [review]

File: core/server/translations/en.json (hunk 2 above)
Comment (imox2) [reply core/server/translations/en.json:257]: @naz thanks for the review. Okay, doing that

**Comment by naz** [comment]
@imox2 congrats on 2nd ever PR merged in :wink: Keep it up!
