### PR TITLE
🐛 Fixed Hidden error in "Add tier" modal

### LINKED ISSUE #15290: Hidden error in "Add tier" modal
Try to add a tier but don’t fill the tier name field. There should be a field error that name is mandatory and the button should switch to “Retry. Instead, seems like nothing changes.

image

## Steps to reproduce 

1. Visit Settings > Memberships > Premium > Add tier
2. Hit the "Add tier" button without entering a name 
3. Notice that nothing happens
4. Look in the console, see the following error appearing:

image

Very unhelpful "Uncaught undefined" 😬 

## Expected behaviour

- The title field should get a red border
- A message should appear under the field saying name is required
- The "Add tier" button should change to a red "Retry" button

### Ghost Version
5.10

### PR DESCRIPTION
**Pull request by h2akim**
closes #15290 

- Capture error from model errors
- Add hasValidated for name property to properly mark field as error/success
- Add property to hasValidated after each failed validation
- Wrap saving on try-catch to suppress uncaught exception (validation error).

### CODE REVIEW

File: ghost/admin/app/components/modal-tier.js [hunk 1]
```diff
@@ -183,10 +179,17 @@ export default class ModalTierPrice extends ModalBase {
...
+        
+        try {
+            yield this.tier.save();
+            this.hasSaved = true;
+            yield this.confirm();
+            this.send('closeModal');
+        } catch (error) {
+            if (error === undefined) {
+                // Validation error
+            }
```
Comment (kevinansfield) [inline ghost/admin/app/components/modal-tier.js:191]: Could you re-throw here if it's not a validation error? Just so any unexpected server errors are still caught/tracked/displayed

Comment (h2akim) [reply ghost/admin/app/components/modal-tier.js:192]: Sure. Added throw error

**Review by kevinansfield — APPROVED** [review]

**Comment by kevinansfield** [comment]
Thanks for tackling this @h2akim 🙂
