### PR TITLE
🎨 Reduced favicon requirements and added image formatting

### LINKED ISSUE #13319: Support animated webp images
Animated webp become static when adding them to Ghost. To reproduce.

0. Create new post
1. drag animated webp (like [this](https://aws1.discourse-cdn.com/business4/uploads/ghost2/original/2X/e/e06710da861f0e7d91f383c9c9bfe755df18fac0.webp)), into editor
2. Click Preview

The preview webp is static (example [page](https://machine-learning-etc.ghost.io/p/0b4618c3-2989-4e8d-9f5c-0199b6a831ac/)). Related [discussion](https://forum.ghost.org/t/use-webp-images-for-posts/6710/20)

### PR DESCRIPTION
**Pull request by SimonBackx**
fixes https://github.com/TryGhost/Team/issues/1652
fixes https://github.com/TryGhost/Ghost/issues/13319

**Image formatting**
Added support for changing the format of images via the `handle-image-sizes` middleware (e.g. format SVG to png, jpeg, webp)

This change was required:
- Not all browsers support SVG favicons, so we need to convert them to PNGs
- We can't fit image resizing and formatting in the `serve-favicon` middleware: we need to store the resized image to avoid resizing on every request. This system was already present in the `handle-image-sizes` middleware.

To format an uploaded image:
- Original URL: https://localhost/blog/content/images/2022/05/giphy.gif
- To resize: https://localhost/blog/content/images/size/w256h256/2022/05/giphy.gif (already supported)
- To resize and format to webp: https://localhost/blog/content/images/size/w256h256/format/webp/2022/05/giphy.gif
- Animations are preserved when converting Gifs to Webp and in reverse, and also when only resizing (https://github.com/TryGhost/Ghost/issues/13319)

**Favicons**
- Custom favicons are no longer served via `/favicon.png` or `/favicon.ico` (only for default favicon), but use their full path
- Added support for uploading more image extensions in Ghost as a favicon: .jpg, .jpeg, .gif, .webp and .svg are now supported (already supported .png and .ico).
- File extensions other than jpg/jpeg, png, or ico will always get transformed to the image/png format to guarantee browser support (webp and svg images are not yet supported as favicons by all browsers).

For all image formats, other than .ico files:
- Allowed to upload images larger than 1000px in width and height, they will get cropped to 256x256px.
- Allowed uploading favicons that are not square. They will get cropped automatically.
- Allowed to upload larger files, up to 20MB (will get served at a lower file size after being resized)

For .svg files:
- The minimum size of 60x60px is no longer required.

For .ico files:
- The file size limit is increased to 200kb (coming from 100kb)

### CODE REVIEW

File: core/frontend/web/middleware/handle-image-sizes.js [hunk 1]
```diff
@@ -7,6 +7,8 @@ const activeTheme = require('../../services/theme-engine/active');
 const config = require('../../../shared/config');
 
 const SIZE_PATH_REGEX = /^\/size\/([^/]+)\//;
+// When formatting, we need to append the right extension to the file name, because the mime type is interpreted from the file extension, and not the file contents
+const FORMAT_PATH_REGEX = /_format\.([^/.]+)$/;
```
Comment (ErisDS) [inline core/frontend/web/middleware/handle-image-sizes.js:11]: I think we can remove the _ here?

Comment (ErisDS) [reply core/frontend/web/middleware/handle-image-sizes.js:11]: Oh I might be misunderstanding. I thought this was for a `/format/` path like `/size/` but it looks like its part of the filename...

Comment (SimonBackx) [reply core/frontend/web/middleware/handle-image-sizes.js]: Change was not yet pushed! Solved now :)
