### PR TITLE
fix for page deletion not updating sitemap-page.xml

### LINKED ISSUE #5913: Bug: deleted entries not removed from sitemap
### Issue Summary

When I delete entries (or make posts static) these URL's cease to work (as expected) but are still included in the sitemap.

### Steps to Reproduce

1. Create a page
2. View sitemap
3. Delete the page
4. View sitemap - page index is still visible
5. Attempt to click on link and visit page results in 404

1. Create port
2. View sitemap
3. Convert post to static page
4. View sitemap - static page still visible as a post
5. Attempt to click on legacy post results in a 404

The sitemap should not include objects know to result in a 404.

### Technical details

* Ghost Version: 0.7.0
* Client OS: Ubuntu 15.04
* Server OS: Ubunti 15.04
* Node Version: v0.10.25
* Browser: Chrome
* Database: Sqlite3

### PR DESCRIPTION
**Pull request by olsio**
closes #5913

Sitemap deletion is based on the page.unpublished event. The previous
logic was always sending post.unpublished instead. If page or post
event is triggered is based on the ‘page’ attribute of the model. When
the destroyed handler all attributes are already cleared from the model
which makes this logic always fall back to post.

The fix is to move to the destroying event which still has all the
model values in place.

### CODE REVIEW

File: core/server/models/post.js [hunk 1]
```diff
@@ -104,7 +104,7 @@ Post = ghostBookshelf.Model.extend({
             }
         });
 
-        this.on('destroyed', function onDestroyed(model) {
+        this.on('destroying', function onDestroying(model) {
```
Comment (olsio) [inline core/server/models/post.js]: This the fix with the least code, although it would have been possible to retrieve the previous page attributed from the previous method of the model but would have involved to change the emitChange method to check if it is a destroy or update.

File: core/test/integration/model/model_posts_spec.js [hunk 2]
```diff
@@ -513,7 +513,7 @@ describe('Post Model', function () {
                 }).catch(done);
             });
 
-            it.only('can save a draft without setting published_by or published_at', function (done) {
+            it('can save a draft without setting published_by or published_at', function (done) {
```
Comment (olsio) [inline core/test/integration/model/model_posts_spec.js]: Re-enabled the tests.

File: core/test/integration/model/model_posts_spec.js [hunk 3]
```diff
@@ -74,7 +74,7 @@ describe('Post Model', function () {
                 }).catch(done);
             });
 
-            it('can findAll, returning all related data', function (done) {
+            it.skip('can findAll, returning all related data', function (done) {
```
Comment (olsio) [inline core/test/integration/model/model_posts_spec.js]: Test is failing afterwards, has to be looked at.

Comment (ErisDS) [inline core/test/integration/model/model_posts_spec.js]: ah haaaa! `findAll` tests can be removed, if you don't mind - that method was removed just the other day: https://github.com/TryGhost/Ghost/pull/5909/files

**Comment by ErisDS** [comment]
The fix looks good to me, however there are some tests failing.

**Comment by olsio** [comment]
Working on it. Test is findAll related have to check why it is failing on the branch but not on master.

**Comment by ErisDS** [comment]
All `findAll` tests for posts, users and tags can be removed as that method no longer exists.

**Comment by ErisDS** [comment]
@olsio Sorry, I've now understood what the underlying problem with `findAll` is here. I'm working on a fix and should have a PR shortly. I recommend updating this PR to revert the changes that aren't related to the sitemap fix, and everything should be OK :+1:

**Comment by olsio** [comment]
Maybe I'll just wait for your PR to go through to see that Travis goes green.

**Comment by olsio** [comment]
@ErisDS I have removed the unrelated changes

**Comment by ErisDS** [comment]
@olsio this PR has a couple of merge commits that ought not to be in here - let me know if you need  a hand sorting them out.

**Comment by olsio** [comment]
@ErisDS yeah sorry, I screwed up branches yesterday :) should be back in order now.
