### PR TITLE
🐛 Fixed re-enabling of complimentary subscriptions

### LINKED ISSUE #12503: Unable to re-enable a complimentary plan when a cancelled one exists
### Issue Summary

When trying to re-enable a complimentary plan for a member who has a previously cancelled one, the toggle switches back to off and the new complimentary plan is not created.

### To Reproduce

1. Create a member
2. Enable their complimentary plan
3. Toggle the plan off & save
4. Turn it on again & save
5. 💥 The toggle slides back to off and the plan is not created

This might be tangentially related to discussions in https://github.com/TryGhost/Ghost/issues/12160 and https://github.com/TryGhost/Ghost/issues/12498, but it definitely used to work so this would be a regression.

### Technical details:

* Ghost Version: 3.40.2
* Node Version: 12.18.0
* Browser/OS: Firefox/Linux
* Database: SQLite

### PR DESCRIPTION
**Pull request by allouis**
closes #12503

Since we include _all_ subscriptions in the `stripeSubscriptions`
relation, we must check that for an existing active complimentary
subscription to decide whether or not we should skip creation of a
complimentary subscription

### CODE REVIEW

File: core/server/api/canary/members.js [hunk 1]
```diff
@@ -192,7 +192,7 @@ module.exports = {
                 frame.options.withRelated = ['stripeSubscriptions'];
                 const member = await membersService.api.members.update(frame.data.members[0], frame.options);
 
-                const hasCompedSubscription = !!member.related('stripeSubscriptions').find(subscription => subscription.get('plan_nickname') === 'Complimentary');
+                const hasCompedSubscription = !!member.related('stripeSubscriptions').find(sub => sub.get('plan_nickname') === 'Complimentary' && sub.get('status') === 'active');
```
Comment (rishabhgrg) [inline core/server/api/canary/members.js:195]: @allouis Should the `active` check here also include other status values - `'active', 'trialing', 'unpaid', 'past_due'` -that we consider as an active subscription for paid member ? 🤔
