### PR TITLE
🎨 Optimized loading stripe scripts only when it is needed

### LINKED ISSUE #11463: Stripe javascript file is loaded even if no stripe connection is setup
### Issue Summary

When enabling members but not paid members (without stripe connection), the stripe javascript is still loaded on the blog.

The load time hit is quite substantial, it would be great if would only be added if the stripe API key is set.

### To Reproduce

1. Enable members, but no stripe payment
2. Load the frontend
3. Stripe javascript file is loaded

### Technical details:

* Ghost Version: 3.1.1
* Node Version: All
* Browser/OS: All
* Database: All

In the `ghost_head.js` file in the helpers folder, there is just no difference at the moment:

```
function getMembersHelper() {
    return `
        <script src="https://js.stripe.com/v3/"></script>
        <script defer src="${getAssetUrl('public/members.js')}"></script>
    `;
}
```

### PR DESCRIPTION
**Pull request by skyeewers**
closes #11463

Ghost used to always load stripe.js into the frontend of all pages when memberships are enabled, even when Stripe isn't configured / memberships to a page are free.

This meant that some people's site were unnecessarily loading stripe.js, leading to unnecessarily long loading times & potentially even privacy issues (the stripe.js script sets cookies that might be problematic under GDPR, especially if the people running the site don't expect Stripe to be loaded because they haven't configured it).

This change changes Ghost's behaviour to only load stripe.js when both stripe API tokens are present & not empty (the quickets way to verify that Stripe is fully configured &  operational on a blog).

### CODE REVIEW

File: core/frontend/helpers/ghost_head.js [hunk 1]
```diff
@@ -44,10 +44,17 @@ function finaliseStructuredData(metaData) {
...
-        <script defer src="${getAssetUrl('public/members.js')}"></script>
-    `;
+    const stripePaymentProcessor = settingsCache.get('members_subscription_settings').paymentProcessors.find(
+        paymentProcessor => paymentProcessor.adapter === 'stripe'
+    );
+    const stripeSecretToken = stripePaymentProcessor.config.secret_token;
+    const stripePublicToken = stripePaymentProcessor.config.public_token;
+
+    var membersHelper = `<script defer src="${getAssetUrl('public/members.js')}"></script>`;
+    if (!!stripeSecretToken && stripeSecretToken !== '' && !!stripePublicToken && stripePublicToken !== '') {
```
Comment (gargol) [inline core/frontend/helpers/ghost_head.js]: Think it would be cleaner to reuse `isPaymentConfigured` method logic straight from membersService https://github.com/TryGhost/Ghost/blob/3.2.0/core/server/services/members/index.js#L26-L29 :
```js
const settings = settingsCache.get('members_subscription_settings');
return !!settings && settings.isPaid && settings.paymentProcessors.length !== 0;
```

and leave a comment about where it's taken from. Also, no need for stripeSecretToken/stripePublicToken checks as we don't allow any other processors so far. YAGNI :smile:  

Ideally, we'd have a separate flag in the `settingsCache` or public settings endpoint which would identify if Stripe payment processor is configured, but that goes out of the scope of this problem :slightly_smiling_face: Reason being: using the settings directly couples the "frontend" with Ghost instance internals which we are trying to avoid (frontend is meant to be as independent as possible so that it can be run separately from Ghost API instance in the future). **But**, for now, think this is an acceptable approach if we leave a note for a person that comes around to refactor this code. 

//cc @allouis you might be interested :wink:

**Review by naz — CHANGES_REQUESTED** [review]

File: core/frontend/helpers/ghost_head.js (hunk 1 above)
Comment (gargol) [reply core/frontend/helpers/ghost_head.js]: @allouis just had another look at this logic in attempt to update the PR and realized the method I referenced in membersService above - `isPaymentConfigured` is never used, additionally we probably have a leftover flag `isPaid` hanging in the settings object as it's never changed to anything but it's default `false` value. Think it's safe to remove both `isPaid` flag and the `isPaymentConfigured` method?

Comment (gargol) [reply core/frontend/helpers/ghost_head.js]: Additionally, we start an instance with `paymentProcessors` by [default](https://github.com/TryGhost/Ghost/blob/fa3686b/core/server/data/schema/default-settings.json#L210) just with empty values. So, I think, the solution here is the best one could have to check if payment is actually configured. Will merge this as is after little bit more testing and will clean up the flag and method mentioned above.

**Comment by gargol** [comment]
After having a closer look at this think your original solution was the best way to go about it. Thanks for the contribution @svenewers :tada:

**Comment by sunknudsen** [comment]
Thanks for PR @svenewers.

Curious, is it possible to enable memberships without loading `js.stripe.com/v3/` unless required (when subscribing to membership for example)?

**Comment by ErisDS** [comment]
Because you can build subscriptions into any page, there's no current way to detect if it's required. Therefore it is always included.

**Comment by sunknudsen** [comment]
@ErisDS, thanks for follow-up.

This is very unfortunate given it make it impossible to maintain a privacy-conscious website while monetizing paid content using memberships (which would be possible if one could use Stripe payment links or the Stripe API vs “Connect with Stripe” integration).

I **profoundly** appreciate the work that has been put into Ghost (thankful for such a beautiful and significant open source endeavour), but I am uncomfortable with the fact Ghost can see one’s customers and subscriptions on Stripe due to “Connect with Stripe” integration.

> Ghost will be able to see your account data (such as all payment and payout history), including any data created by other businesses you've connected. They'll also be able to create new payments and take other actions for you.

As a privacy and security researcher and [YouTuber](https://www.youtube.com/sunknudsen), my audience would be very upset if I used such an integration. 😔

Also, given [Stripe.js](https://stripe.com/docs/js) is considered a tracker (especially when [advanced fraud detection](https://stripe.com/docs/disputes/prevention/advanced-fraud-detection) is enabled), one has to get explicit user consent before loading `https://js.stripe.com/v3/` according to international privacy legislation.

I believe this is currently not possible… looks like `<script async src="https://js.stripe.com/v3/"></script>` is added to all pages as soon as memberships are enabled (see [these lines](https://github.com/TryGhost/Ghost/blob/main/core/frontend/helpers/ghost_head.js#L51-L62)).

I really wish one could use Ghost without worrying about above.

**Comment by allouis** [comment]
@sunknudsen If you do not connect to Stripe, then Stripe will not be loaded - you can then set up your own payment system and sync with Ghost using the API - maybe something like this will help you https://ghost.org/integrations/paypal/

**Comment by sunknudsen** [comment]
@allouis Thanks for sharing! I was hoping to enable free and paid tiers which is not possible using member “hack”.

That said, given “hack” is as good as it gets currently, I will be releasing an open source project shortly called `ghost-join` which replicates PayPal solution on Stripe.
