### PR TITLE
Replace jquery-ui.sortable with ember-sortable for nav items

### LINKED ISSUE #6457: Bug with reordering+deletion in Navigation page
I found a reproducible bug in the Navigation page that could potentially allow a user to delete more entries than they intended.

Actual results:
After some combinations of list-reordering steps, the list gets into a bad state where attempting to delete a single row actually ends up deleting multiple rows.

Expected results:
Clicking the delete icon for a row should delete only the intended row, nothing more or less.

Steps to reproduce:
- Create five entries ("Aardvark", "Bat", "Cat", "Dog", "Elephant")
- Move "Dog" into the second position (above "Bat")
- Move "Elephant" into the third position (above "Cat")
- Delete the fourth item ("Bat")
(At this point three rows have been deleted instead of one.)

Reproducibility:
100%. I can consistently reproduce this with the steps described.

Other details:
I'm using the hosted blogging platform on ghost.io, not the self-hosted distribution. I can't tell what version is running. The meta `ghost/config/environment` shows version "0.0.0 26ea9ad8" but that doesn't match up with a commit in this repo.

### PR DESCRIPTION
**Pull request by kevinansfield**
refs #6458, closes #6457
- replaces jquery-ui.sortable with ember-sortable for drag-n-drop handling
- moves the "new/blank" nav item out of the nav items list
  - allows it to be excluded from the draggable list
  - cleans up handling of the `navigationItems` array as there's no longer a need to ignore/exclude this extra item
- clears validation errors when typing in the respective field
- adds acceptance test for adding/removing nav items
- improves acceptance test for saving nav items to cover more edge cases

### CODE REVIEW

File: core/client/tests/acceptance/settings/navigation-test.js [hunk 1]
```diff
@@ -91,14 +129,105 @@ describe('Acceptance: Settings - Navigation', function () {
...
+                    'blank url still has validation error'
+                ).to.be.true;
+            });
+
+            fillIn('.gh-blognav-url:last input', '/new');
+            triggerEvent('.gh-blognav-url:last input', 'keypress');
+            triggerEvent('.gh-blognav-url:last input', 'blur');
+
+            andThen(function () {
+                expect(
```
Comment (acburdine) [inline core/client/tests/acceptance/settings/navigation-test.js]: This is what's causing one of the errors in the client tests. Is this due to improper fake-placeholder handling?

**Comment by acburdine** [comment]
Tested this and it looks good to me! However, the tests in https://github.com/kevinansfield/Ghost/blob/ember-sortable-nav-items/core/client/tests/integration/components/gh-navitem-url-input-test.js need to be updated to match the new `isNew` spec (most of them still are passing the `last` property). That and the "enter" test in that file isn't passed a `clearErrors` action method.

Otherwise, :+1:

**Comment by kevinansfield** [comment]
Thanks, some nice :fishing_pole_and_fish: there! I'd missed a few stilly things, that'll teach me to not assume everything's good after running isolated tests :smile:
