### PR TITLE
Disallow indexing of preview urls

### LINKED ISSUE #9749: Preview URLs are being indexed by search engines
Originally raised on the forum: https://forum.ghost.org/t/preview-article-links-ranking-in-google-possible-to-add-no-index-tag/2123

### To Reproduce

I'm not sure what the reproduction case for this is, in terms of how Google is finding the urls. It could be to do with Disqus and Google Analytics loading on the preview pages? These pages should definitely not be appearing in the sitemap (and they aren't).

Either way, we should prevent indexing on these pages. 

### Technical details:

* Ghost Version: 1.24

### PR DESCRIPTION
**Pull request by vikaspotluri123**
closes #9749

 - disallow indexing of /p/ in robots.txt
 - add meta robots tag to preview pages
   - robots.txt wont' be applied for blogs not mounted to the root (i.e. https://example.com/blog/)

I went ahead and disabled travis for now since I had a couple of questions 😄

### CODE REVIEW

File: core/server/helpers/ghost_head.js [hunk 1]
```diff
@@ -108,7 +108,8 @@ module.exports = function ghost_head(options) { // eslint-disable-line camelcase
         useStructuredData = !config.isPrivacyDisabled('useStructuredData'),
         referrerPolicy = config.get('referrerPolicy') ? config.get('referrerPolicy') : 'no-referrer-when-downgrade',
         favicon = blogIconUtils.getIconUrl(),
-        iconType = blogIconUtils.getIconType(favicon);
+        iconType = blogIconUtils.getIconType(favicon),
+        isPreviewPage = /^\/p\//.test(dataRoot.relativeUrl);
```
Comment (vikaspotluri123) [inline core/server/helpers/ghost_head.js]: Is there a better-suggested way of determining if a page is a preview page?

File: core/server/helpers/ghost_head.js [hunk 2]
```diff
@@ -176,6 +177,11 @@ module.exports = function ghost_head(options) { // eslint-disable-line camelcase
                 escapeExpression(metaData.blog.title) + '" href="' +
                 escapeExpression(metaData.rssUrl) + '" />');
 
+            // don't allow indexing of preview URLs!
+            if (isPreviewPage) {
+                head.push(writeMetaTag('robots', 'noindex,nofollow', 'name'));
```
Comment (vikaspotluri123) [inline core/server/helpers/ghost_head.js]: I noticed the `writeMetaTag` utility is available, but isn't used in this specific function - was there any specific reason for that?

File: core/test/integration/helpers/ghost_head_spec.js [hunk 3]
```diff
@@ -1218,6 +1218,19 @@ describe('{{ghost_head}} helper', function () {
             }).catch(done);
         });
 
+        it('disallows indexing for preview pages', function (done) {
```
Comment (vikaspotluri123) [inline core/test/integration/helpers/ghost_head_spec.js]: So this test makes sense, because we want to make sure the tag is added to `/p/` pages.

How should I go about adding tests to make sure it's not added to other pages? Should I add `should.not.match` lines to other tests where the `relativeUrl` parameter is (semi-arbitrarily) distinct?

File: core/server/helpers/ghost_head.js (hunk 1 above)
Comment (vikaspotluri123) [reply core/server/helpers/ghost_head.js]: I think I found the right place 😄

File: core/server/services/routing/helpers/context.js [hunk 4]
```diff
@@ -18,7 +18,8 @@ const labs = require('../../labs'),
     subscribePattern = new RegExp('^\\/subscribe\\/'),
     // routeKeywords.amp: 'amp'
     ampPattern = new RegExp('\\/amp\\/$'),
-    homePattern = new RegExp('^\\/$');
+    homePattern = new RegExp('^\\/$'),
+    previewPattern = new RegExp('^\\/p\\/');
```
Comment (sethbergman) [inline core/server/services/routing/helpers/context.js]: This is a great PR! I didn't even know that the preview pages were being indexed under the described conditions. I think it makes sense to add `<meta name="robots" content="noindex,nofollow" />` to all preview pages using the following RegExp:

```
\/p\/
```
RegEx Tester for the solution above: https://regex101.com/r/jRBDSJ/1
RegEx Tester for [current PR](https://github.com/TryGhost/Ghost/pull/9762/files#diff-e7b88060df0e3026e0ea24c3b5b4671cR22): https://regex101.com/r/5CqTPx/1

File: core/test/integration/helpers/ghost_head_spec.js (hunk 3 above)
Comment (sethbergman) [reply core/test/integration/helpers/ghost_head_spec.js]: As far as tests go, I'm not certain due to the complexities of the Ghost ecosystem, but [maybe this](https://github.com/TryGhost/Ghost/pull/9762/files#r207703580) will help.

File: core/server/services/routing/helpers/context.js (hunk 4 above)
Comment (vikaspotluri123) [reply core/server/services/routing/helpers/context.js]: Thanks for the suggestion! This regex would actually catch all instances of preview pages, since the regex is executed on the  [relative url](https://github.com/vikaspotluri123/Ghost/blob/8ca88cebeee4000fc7ca3d7165eae6747c130af0/core/server/services/routing/helpers/context.js#L50). This still allows the client to use, for example, a tag w/ slug `p` (i.e. `my.blog/tag/p/` would still match w/o the line start operater)

You can see similar / the same logic with the `subscribePattern` test 😄

Comment (sethbergman) [reply core/server/services/routing/helpers/context.js]: Thanks for clarifying the logic behind the relative URLs, and where to find them in the code base. I love using Ghost! 👻

**Comment by JohnONolan** [comment]
Nice, I was going to say don't forget about robots.txt but you already got it :)

File: core/test/integration/helpers/ghost_head_spec.js (hunk 3 above)
Comment (kirrg001) [reply core/test/integration/helpers/ghost_head_spec.js]: Adding one assertion to proof that the meta-tag is not present when `preview` is not included in the context object is enough.
