### PR TITLE
⚡️  Throw clear error message when `config.url` has no protocol

### LINKED ISSUE #8449: 🐛 server crashes if blog url has no protocol
If i add a url like `localhost:2368` the server crashes. The error log.

```
NAME: InternalServerError
MESSAGE: The server has encountered an error.

level:normal

TypeError: Cannot read property 'replace' of null
    at getSubdir (/Users/kirrg001/dev/ghost/ghost/core/server/utils/url.js:52:34)
    at deduplicateSubDir (/Users/kirrg001/dev/ghost/ghost/core/server/utils/url.js:61:18)
    at Object.urlJoin (/Users/kirrg001/dev/ghost/ghost/core/server/utils/url.js:115:11)
    at frontendRoutes (/Users/kirrg001/dev/ghost/ghost/core/server/blog/routes.js:28:26)
    at setupBlogApp (/Users/kirrg001/dev/ghost/ghost/core/server/blog/app.js:114:17)
    at setupParentApp (/Users/kirrg001/dev/ghost/ghost/core/server/app.js:65:36)
    at /Users/kirrg001/dev/ghost/ghost/core/server/index.js:72:37
```

Ghost: master

### PR DESCRIPTION
**Pull request by aileen**
closes #8449

Fixes an issue where Ghost would crash when the URL in `config` is set up without a protocol.
This PR checks the URL on startup within config utils and outputs a warning for the user, but also sanitises the URL to prevent crashes.

Not sure, if this is the wanted behaviour in this case.  We could also prevent Ghost from starting and output a more clear error message instead... Let me know, what you'd prefer @kirrg001

### CODE REVIEW

File: core/server/config/utils.js [hunk 1]
```diff
@@ -69,6 +70,21 @@ exports.getContentPath = function getContentPath(type) {
...
+*/
+exports.sanitiseUrlProtocol = function sanitiseUrlProtocol() {
+    var url = this.get('url');
+
+    if (url.match(/^https?:\/\//i)) {
+        return;
+    } else {
+        this.set('url', 'http://' + url);
+        console.log(chalk.red('Watch out! Your URL in the config should have a protocol! E.g. "http://my-ghost-blog.com"'));
+        console.log(chalk.white('Current URL: ') + chalk.cyan(url));
```
Comment (kirrg001) [inline core/server/config/utils.js]: We have a couple of start messages in `core/ghost-server`.
I would like to keep them in one place. There is already a url stdout for development mode.

Comment (AileenCGN) [inline core/server/config/utils.js]: Would you just prefer to have the stdout for this bundled in `core/server/ghost-server`? Or not output at all?

Here, specifically, I output the url the user has set up in the config and set the sanitised value of this url as the new url to work with.

The user will then first see, how he set up the url and then (coming from `ghost-server.js`) how it should look like.

Here an example:

image

Comment (kirrg001) [inline core/server/config/utils.js]: `Url configured as` is already present?
Maybe double check if it shows up in production as well.

**Review by kirrg001 — APPROVED** [review]
LGTM 👍 

If we feel like we want to add the protocol and start Ghost, we can change the behaviour anytime. But for now, it works similar to the CLI!
