### PR TITLE
🐛 Fixed crash on startup when no active theme

### LINKED ISSUE #10416: Active theme is not always available
Example reference: https://forum.ghost.org/t/after-update-ghost-dont-start/4949/19

## Problem

We have a theme service and a couple of places where we ask for the active theme.

But if you start Ghost and the active theme cannot be found (e.g. does not exist on your server), the active theme is not available -> `themeService.getActive().engine` will crash.

We allow Ghost to start up, because we want to allow serving the admin panel.

## Possible solution

- Protect the code areas against `themeService.getActive()` beeing null

**The solution needs to be confirmed first.**

Any help is appreciated :)

Ghost: master

### PR DESCRIPTION
**Pull request by rshbhgrg**
closes #10416

- Updated to use default theme engine values when no active theme is found

--------------------------------------------------

The only instances of no active theme causing startup to fail are where its trying to access active theme engine (`getActive().engine`) to get the `ghost-api` property, like [here](https://github.com/TryGhost/Ghost/blob/6b758bda7917420dc567210f0f7e039c7f48a7d2/core/server/services/routing/bootstrap.js#L41).

Protecting these instances against active theme being null, a good fallback for `ghost-api` property if no active theme is found seems to be fetching default value from [here](https://github.com/TryGhost/Ghost/blob/master/core/server/services/themes/engines/defaults.json#L2) instead of hardcoding a particular API version.

### CODE REVIEW

**Comment by rishabhgrg** [comment]
@kirrg001 Wanted to confirm this solution as mentioned in issue, mainly for the fallback method we are using here for `ghost-api` value across different instances. 😄

File: core/server/services/routing/bootstrap.js [hunk 1]
```diff
@@ -38,7 +39,7 @@ module.exports.init = (options = {start: false}) => {
  *   - is the PreviewRouter an app?
  */
 module.exports.start = () => {
-    const apiVersion = themeService.getActive().engine('ghost-api');
+    const apiVersion = themeService.getActive() ? themeService.getActive().engine('ghost-api') : defaultThemeEngine['ghost-api'];
```
Comment (kirrg001) [inline core/server/services/routing/bootstrap.js]: In general: i think the url and routing service need to initialise if the active theme can't be found. The direction looks good 👍 

---

I think requiring a specific file from the theme service is quite "dirt"y, because we don't use the official theme interface? It's quite weird that "if there is no active theme, that we require a file from the theme service to get a default"?

Comment (rishabhgrg) [reply core/server/services/routing/bootstrap.js]: Hmm I agree its a bit dirty fetching the default config file, this is a bit of unique case where instead of not having particular value in theme interface, we don't have the theme interface at all, so there is nothing directly to fallback to. Since what we are trying to fetch is engine for a non-existent theme here, themeService seems to be the next best contender to answer it. 

So as fallback the only choices seemed to be between hard-coding a value and using defaults file, what went in favour of latter was -
- Fallback value stays consistent everywhere, picked from one place
- This is the default value we use for a theme if it doesn't specify `ghost-api`, so it seemed like a natural extension in case of no theme itself. 

The only other option I see for getting a fallback is if we tamper theme interface to load defaults instead of `null` in case of non-existent theme, but that seems stretching it a bit too much for the values, wdyt?

Comment (kirrg001) [reply core/server/services/routing/bootstrap.js]: In general: The underlying problemis that the API is currently tied with the url generation.
Content API returns urls. That's why we have to generate the urls even if there is no active theme.

Maybe we could just extend the theme service interface _for now_ like

```
if themeService.hasActiveTheme()
  apiVersion = getActive().engine()
else
  apiVersion = themeService.getDefaults().api_version
```

Comment (rishabhgrg) [reply core/server/services/routing/bootstrap.js]: I like this direction, extending themeService to have `getApiVersion` makes much more sense as it's used across a lot of files which will be much cleaner instead of all the `if/else` everywhere. 👍

Comment (rishabhgrg) [reply core/server/services/routing/bootstrap.js]: @kirrg001 Updated. Looks much cleaner now

**Review by kirrg001 — APPROVED** [review]
