### PR TITLE
🐛 Fix last seen for users

### LINKED ISSUE #10138: Team member "last seen" no longer updating
Latest Chrome / Pro

I am currently logged in, and several people on this list have also been logged in more recently than indicated. Marking this as critical because we have several critical external systems which depend on this info being up to date. (Actually think that's a strong case for this feature having tests)

image

### PR DESCRIPTION
**Pull request by allouis**
closes #10138 

This adds an `updateLastSeen` method to the user model instance, refactors the codebase to use this method anywhere the last_seen is updated and adds middleware to the admin api to ensure that we always update the last_seen property when a user accesses the API.

### CODE REVIEW

File: core/server/models/user.js [hunk 1]
```diff
@@ -777,8 +782,7 @@ User = ghostBookshelf.Model.extend({
 
                 return self.isPasswordCorrect({plainPassword: object.password, hashedPassword: user.get('password')})
                     .then(function then() {
-                        user.set({status: 'active', last_seen: new Date()});
```
[the remark this answers is not in the document]
Comment (allouis) [reply core/server/models/user.js]: It seemed to me that the status had to be active to reach here, but i've just ween the `warn-1` etc... states! will update - what are those states used for though?

[the remark this answers is not in the document]
Comment (kirrg001) [reply core/server/models/user.js]: for all kinds of features:
- suspended
- login attempts
- etc

[the remark this answers is not in the document]
Comment (allouis) [reply core/server/models/user.js]: Ah right - login attempts make sense, but suspended would need to use an "inactive" state right?

File: core/server/models/user.js [hunk 2]
```diff
@@ -783,6 +783,10 @@ User = ghostBookshelf.Model.extend({
                 return self.isPasswordCorrect({plainPassword: object.password, hashedPassword: user.get('password')})
                     .then(function then() {
                         return user.updateLastSeen();
+                    })
+                    .then(function then() {
+                        user.set({status: 'active'});
+                        return user.save();
```
Comment (allouis) [inline core/server/models/user.js]: We _could_ have done smth like
```javascript
user.set({status: 'active'})
return user.updateLastSeen()
```
But that relies too much on the functionality of `updateLastSeen` and seemed brittle

File: core/server/models/user.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (kirrg001) [reply core/server/models/user.js]: > suspended would need to use an "inactive" state right?

yes

[the remark this answers is not in the document]
Comment (allouis) [reply core/server/models/user.js]: okie just checking :+1:

File: core/server/web/shared/middlewares/update-user-last-seen.js [hunk 3]
```diff
@@ -0,0 +1,15 @@
+const constants = require('../../../lib/constants');
+
+module.exports = function updateUserLastSeenMiddleware(req, res, next) {
+    if (!req.user) {
+        return next();
+    }
+
+    if (Date.now() - req.user.get('last_seen') < constants.ONE_HOUR_MS) {
```
Comment (kirrg001) [inline core/server/web/shared/middlewares/update-user-last-seen.js]: 👍 That makes so much more sense :)

Comment (allouis) [reply core/server/web/shared/middlewares/update-user-last-seen.js]: :relaxed:

File: core/server/models/user.js (hunk 2 above)
Comment (kirrg001) [reply core/server/models/user.js]: Hm yeah agree, that's not cool

File: core/server/models/user.js [hunk 4]
```diff
@@ -777,7 +782,10 @@ User = ghostBookshelf.Model.extend({
 
                 return self.isPasswordCorrect({plainPassword: object.password, hashedPassword: user.get('password')})
                     .then(function then() {
-                        user.set({status: 'active', last_seen: new Date()});
+                        return user.updateLastSeen();
+                    })
+                    .then(function then() {
```
Comment (kirrg001) [inline core/server/models/user.js]: Suggestion: ES6 syntax.

e.g. ^ we don't use named fn's in promises.

File: core/server/models/base/listeners.js [hunk 5]
```diff
@@ -8,7 +8,10 @@ var moment = require('moment-timezone'),
  * WHEN access token is created we will update last_seen for user.
  */
 common.events.on('token.added', function (tokenModel) {
```
Comment (kirrg001) [inline core/server/models/base/listeners.js]: Suggestion: This logic is only used for v0.1. IMO add a TODO to remove when we drop v0.1?

File: core/server/web/shared/middlewares/update-user-last-seen.js [hunk 6]
```diff
@@ -0,0 +1,15 @@
...
+        return next();
+    }
+
+    req.user.updateLastSeen().then(() => {
```
Comment (kirrg001) [inline core/server/web/shared/middlewares/update-user-last-seen.js]: Two thoughts on this:

1. We update the user, but we don't update `req.user` after the successful update. Probably doesn't matter right now, because Ghost does not return `req.user` (only for internal usages)
2. Should we just continue with the request if this operation fails?

**Review by kirrg001 — COMMENTED** [review]
Functionality works 👍

File: core/server/web/shared/middlewares/update-user-last-seen.js (hunk 6 above)
Comment (kirrg001) [reply core/server/web/shared/middlewares/update-user-last-seen.js]: Ok agree to both :)

**Review by kirrg001 — APPROVED** [review]

**Comment by kirrg001** [comment]
@allouis Feel free to self merge
