### PR TITLE
Redirect amp links to their non-amp counterpart when amp is disabled

### LINKED ISSUE #9495: Enable automatic redirects for AMP urls if the AMP is disabled.
### Issue Summary

Disabling AMP feature, does not automatically redirect or serve the existing AMP url's that have been served on various sites like Twitter.

### Steps to Reproduce

1. Enable AMP and share one of the posts on twitter.
2. Disable AMP on Ghost and invoke the URL from twitter post again.

### Technical details:

* Ghost Version: 1.21.3
* Node Version: 6.13.0
* Browser/OS: Chrome
* Database: MySQL.

### PR DESCRIPTION
**Pull request by rkalis**
closes #9495

- Added a clause for amp being disabled
- In this clause, we strip the final 'amp/' part of the url, and redirect
- Changed corresponding test in frontend_spec.js

### CODE REVIEW

**Review by aileen — APPROVED** [review]
Tested and works fine for me 👍

File: core/server/apps/amp/index.js [hunk 1]
```diff
@@ -5,17 +5,20 @@ var router           = require('./lib/router'),
     config = require('../../config'),
     settingsCache = require('../../services/settings/cache');
 
+function ampRouter(req, res) {
+    if (settingsCache.get('amp') === true) {
+        return router.apply(this, arguments);
+    } else {
+        var redirectUrl = req.originalUrl.replace(/amp\/$/, '');
+        res.redirect(301, redirectUrl);
```
Comment (kirrg001) [inline core/server/apps/amp/index.js]: Can you pls use `urlService.utils.redirect301`? This is a wrapper function, which allows us to define a behaviour for redirects.

**Comment by AileenCGN** [comment]
@kirrg001 Is this PR good to go for your POV?

**Comment by kirrg001** [comment]
@AileenCGN yeah code looks correct 👍
