### PR TITLE
Avoid infinite transition loop

### LINKED ISSUE #5136: Bug: Author level users cannot access their user profile
If you're logged into Ghost as an author-level user, it is not possible to get to your user profile page. Clicking the link causes the page to hang. There is this error in the console, but not 100% sure it's related: 

### Steps to Reproduce

1. Login as an author
2. Click on the `Your profile` link

### Technical details: 

* Ghost Version: 0.6.0

### PR DESCRIPTION
**Pull request by ErisDS**
This is a first pass at trying to fix the bug with authors not being able to access their profiles. 

It seems the users route suddenly caused an infinite transition loop. The code is unchanged, so must be due to a change in Ember? Moving the transition down to users/index.js resolves the issue.

Whilst I was there I also got rid of the console error (which was unrelated) by wrapping the fetch for notifications in a user role check - this is probably hiding an underlying issue which likely does need resolving, but I've no idea why that's suddenly triggering an error (ember bug?)

Also, I changed all of the calls to `this.store.find('user', 'me')` to use `this.get('session.user')`. It seems like the right thing to do, but I'm not 100% sure whether this will pick up changes to the user - I kind of assume that because it's ember, it will, but I need to test.

fixes #5136
- wrap notification fetch with a user role check to remove console error
- move author transition down to local route for users/user so that there's no infinite loop
- replace all store calls to fetch the current user with the session user instead

### CODE REVIEW

File: core/client/app/mixins/current-user-settings.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import Ember from 'ember';
 var CurrentUserSettings = Ember.Mixin.create({
     currentUser: function () {
```
Comment (novaugust) [inline core/client/app/mixins/current-user-settings.js]: what if this method died? as long as you're reducing the number of alias's for session.user ...

Comment (novaugust) [inline core/client/app/mixins/current-user-settings.js]: If not that then at least consistently using one or the other within a file eh

**Comment by ErisDS** [comment]
@novaugust made your suggested changes. This is no longer a WIP.

**Comment by ErisDS** [comment]
Any more feedback on this or is it good to go?
