### PR TITLE
🐛 Redirected to original image for gifs & svgs

### LINKED ISSUE #10301: Animated GIFs don't work with responsive images
Anyone using Ghost's brand-new responsive image feature will notice that their gifs stop animating when served at reduced sizes.

This is because Sharp doesn't support [resizing gifs](http://sharp.pixelplumbing.com/en/stable/api-output/#tobuffer). We need to skip the feature for gif filetypes.

Ghost keeps the original uploaded image around, and therefore once we fix this, anyone experiencing issues will see the problem go away without needing to reupload or manually intervene in any way.

### To Reproduce

1. Upload an animated gif
2. Setup some responsive images in your theme (or use the latest Casper)
3. Try to view the gif at one of the smaller sizes.

### Technical details:

* Ghost Version: master  / >2.9.0

### PR DESCRIPTION
**Pull request by allouis**
closes #10301 

ronseal really - if the image is gif/svg, redirect to unresized version.

it might be worth pulling the regex out into the image module maybe? and having a test for it?

### CODE REVIEW

File: core/server/web/shared/middlewares/image/handle-image-sizes.js [hunk 1]
```diff
@@ -4,6 +4,7 @@ const storage = require('../../../../adapters/storage');
 const activeTheme = require('../../../../services/themes/active');
 
 const SIZE_PATH_REGEX = /^\/size\/([^/]+)\//;
+const UNRESIZABLE_FILETYPE_REGEX = /\.(?:gif|svgz?)$/;
```
Comment (gargol) [inline core/server/web/shared/middlewares/image/handle-image-sizes.js]: Maybe we could unify it with same logic here: https://github.com/TryGhost/Ghost/blob/fcd275f6c098684ad615b02d0714cf38e5cd8f44/core/server/web/shared/middlewares/image/normalize.js#L14
Tbh, not a fan of regexes when it comes to blacklists like here or any data that can be represented as an array, as it's not visible from first glance that both `.svg` and `.svgz` would be caught by this regexp :thinking:

Comment (allouis) [reply core/server/web/shared/middlewares/image/handle-image-sizes.js]: Blacklist as an array deffo makes more sense :ok_hand: 

Not 100% sure what you meant by unify, so far I've copied the array - do you think we should export the file extension blacklist? Maybe from the `lib/image` or `middleware/image` module?

Comment (gargol) [reply core/server/web/shared/middlewares/image/handle-image-sizes.js]: Yes :+1: , think file extension blacklist should be a part of `lib/image/manipulator` and both middlewares - `normalize` & `handle-image-sizes` would be using the same method like `canTransform` or something along those lines

Comment (allouis) [reply core/server/web/shared/middlewares/image/handle-image-sizes.js]: Yeah nice idea :relaxed: I've added that now

Comment (gargol) [reply core/server/web/shared/middlewares/image/handle-image-sizes.js]: Looks great :+1: Just one more small thing, this note - https://github.com/TryGhost/Ghost/pull/10315/files#diff-ff55d92bb888edcce1b6466a7c7bbc65R10 , would need to be moved to this new method as well. Other then this, it looks very shippable :ship:

Comment (allouis) [reply core/server/web/shared/middlewares/image/handle-image-sizes.js]: Nice catch :male_detective: - updated!

**Review by naz — APPROVED** [review]
:+1: :ship: :ship: :ship: :tada:
