### PR TITLE
🐛 optimise how we populate default settings

### LINKED ISSUE #7345: ERROR: Database version is not recognized on ubuntu14
I followed this tutorial:  https://www.digitalocean.com/community/tutorials/how-to-create-a-blog-with-ghost-and-nginx-on-ubuntu-14-04

when i tried to run "npm start --production", i got following error:

```
test@ubuntu-test-purpose:/home/project/jackieouyang$ sudo npm start --production

> ghost@0.10.1 start /home/project/jackieouyang
> node index

WARNING: Ghost is attempting to use a direct method to send email.
It is recommended that you explicitly configure an email service.
Help and documentation can be found at http://support.ghost.org/mail.


ERROR: Database version is not recognized

 Error
    at Error.DatabaseVersion (/home/project/jackieouyang/core/server/errors/database-version.js:3:18)
    at /home/project/jackieouyang/core/server/data/schema/versioning.js:35:47
    at tryCatcher (/home/project/jackieouyang/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/project/jackieouyang/node_modules/knex/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/project/jackieouyang/node_modules/knex/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/project/jackieouyang/node_modules/knex/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/project/jackieouyang/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/project/jackieouyang/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/project/jackieouyang/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

### Technical details:

* Ghost Version: download  today
* Node Version:4.2.6
* Browser/OS:  ubuntu 14
* Database:  Sqlite version 2.8.17

### PR DESCRIPTION
**Pull request by kirrg001**
closes #7345, refs #7461
- better handling for populating default settings

### CODE REVIEW

File: core/server/index.js [hunk 1]
```diff
@@ -77,75 +77,91 @@ function init(options) {
...
+         * - getDatabaseVersion will throw an error and we will create all tables (including populating settings)
+         * - this will run in one single transaction to avoid having problems with non existent settings
+         * - see https://github.com/TryGhost/Ghost/issues/7345
+         */
+        return versioning.getDatabaseVersion()
+            .then(function () {
+                /**
+                 * No fresh install:
+                 * - every time Ghost starts,  we populate the default settings before we run migrations
+                 * - importing, because it can happen that a new added default property won't be existent
```
Comment (kirrg001) [inline core/server/index.js]: importing, because
jaa 📦
