### PR TITLE
:bug: Fixed session auth for blogs running on sub dir

### LINKED ISSUE #9982: 500 error during setup with api v2 (on a subdirectory)
This issue is very similar to #9952 , but I already have a clean install, from now, and I have this error in first admin page initial setup:

```
[2018-10-10 20:23:52] INFO Model: Post
[2018-10-10 20:23:53] INFO Relation: Role to Permission
[2018-10-10 20:23:53] INFO Relation: Post to Tag
[2018-10-10 20:23:53] INFO Relation: User to Role
[2018-10-10 20:23:54] WARN Theme's file locales/en.json not found.
[2018-10-10 20:23:55] INFO Ghost is running in production...
[2018-10-10 20:23:55] INFO Your blog is now available on https://mysite.org/blog/
[2018-10-10 20:23:55] INFO Ctrl+C to shut down
[2018-10-10 20:23:55] INFO Ghost boot 9.655s
[2018-10-10 20:23:55] INFO Bootstrap client was closed.
[2018-10-10 20:24:05] INFO "GET /blog/ghost/" 200 110ms
[2018-10-10 20:24:06] ERROR "GET /blog/ghost/api/v2/admin/users/me/?include=roles" 500 17ms

NAME: InternalServerError
MESSAGE: Cannot read property 'origin' of undefined

level: normal

empty
empty
ERROR DETAILS:
    empty

InternalServerError: Cannot read property 'origin' of undefined
    at new GhostError (/var/www/ghost/versions/2.2.1/core/server/lib/common/errors.js:10:26)
    at _private.prepareError (/var/www/ghost/versions/2.2.1/core/server/web/shared/middlewares/error-handler.js:42:19)
    at Layer.handle_error (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:275:10)
    at /var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:635:15
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:260:14)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:127:14)
    at Layer.handle_error (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:67:12)

TypeError: Cannot read property 'origin' of undefined
    at cookieCsrfProtection (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:103:22)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at session (/var/www/ghost/versions/2.2.1/node_modules/express-session/index.js:195:71)
    at getSession (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:48:12)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:281:22
    at param (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:354:14)
    at param (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:410:3)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:174:3)
    at router (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:47:12)

[2018-10-10 20:24:06] INFO "GET /blog/ghost/api/v2/admin/configuration/" 200 8ms
[2018-10-10 20:24:06] INFO "GET /blog/ghost/api/v2/admin/authentication/setup/" 200 17ms
[2018-10-10 20:24:06] INFO "GET /blog/ghost/api/v2/admin/authentication/setup/" 200 10ms
[2018-10-10 20:24:06] INFO "GET /blog/ghost/assets/img/install-welcome-ff3912d18bf8949df89c83b1c3b8bb66.png" 200 3ms
[2018-10-10 20:24:22] INFO "GET /blog/ghost/" 200 11ms
[2018-10-10 20:24:22] ERROR "GET /blog/ghost/api/v2/admin/users/me/?include=roles" 500 3ms

NAME: InternalServerError
MESSAGE: Cannot read property 'origin' of undefined

level: normal

empty
empty
ERROR DETAILS:
    empty

InternalServerError: Cannot read property 'origin' of undefined
    at new GhostError (/var/www/ghost/versions/2.2.1/core/server/lib/common/errors.js:10:26)
    at _private.prepareError (/var/www/ghost/versions/2.2.1/core/server/web/shared/middlewares/error-handler.js:42:19)
    at Layer.handle_error (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:275:10)
    at /var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:635:15
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:260:14)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:127:14)
    at Layer.handle_error (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:67:12)

TypeError: Cannot read property 'origin' of undefined
    at cookieCsrfProtection (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:103:22)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at session (/var/www/ghost/versions/2.2.1/node_modules/express-session/index.js:195:71)
    at getSession (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:48:12)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:281:22
    at param (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:354:14)
    at param (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:410:3)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:174:3)
    at router (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/index.js:47:12)

[2018-10-10 20:24:23] INFO "GET /blog/ghost/api/v2/admin/configuration/" 200 10ms
[2018-10-10 20:24:23] INFO "GET /blog/ghost/api/v2/admin/authentication/setup/" 200 16ms
```

### To Reproduce

- Debian 9, clean install.
- NGINX 1.10.3
- PHP 7.2
- MySQL 5.7

I have initial setup to this domain in order to: https://mysite.com, and inside this https://mysite.com/blog resides Ghost.

### Technical details:

* Ghost-CLI version: 1.9.6
* Ghost version: 2.2.1
* Node Version: v8.12.0
* Browser/OS: Chrome / macOS High Sierra
* Database: Mysql 5.7

How I commented, I read this issue (#9952) but this changes has been applied to my version of ghost, and continuously occur this error preventing me for completing my registration to my own blog.
Any idea?

### PR DESCRIPTION
**Pull request by allouis**
closes #9982

This adds the subdirectory to the path for the session cookie, enabling
cookies to be sent/set/parsed for the session authentication to work.

### CODE REVIEW

File: core/server/services/auth/session/middleware.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ const getSession = (req, res, next) => {
             cookie: {
                 maxAge: constants.SIX_MONTH_MS,
                 httpOnly: true,
-                path: '/ghost',
+                path: urlService.utils.getSubdir() + '/ghost',
```
Comment (kirrg001) [inline core/server/services/auth/session/middleware.js]: `urlService.utils.urlFor('admin')`

Comment (allouis) [reply core/server/services/auth/session/middleware.js]: That's gonna include a trailing slash, which means the cookie won't be sent if we're on a page without one - I think that would be confusing behaviour :confused: I could use `urlFor` and strip the slash?

Comment (kirrg001) [reply core/server/services/auth/session/middleware.js]: Hmm, but Ghost forces the trailing slash for any page visit

Comment (kirrg001) [reply core/server/services/auth/session/middleware.js]: Leave this as is, if you think it's safer

Comment (kirrg001) [reply core/server/services/auth/session/middleware.js]: Just decide and selfe merge 👍

Comment (allouis) [reply core/server/services/auth/session/middleware.js]: > Hmm, but Ghost forces the trailing slash for any page visit

It does, I'm just worried that we could be bitten in the future :shrimp: I think this way is slightly safer - but also it's not as nice
