### PR TITLE
#6769 allow manifest.json to be served from theme directory. Implement…

### LINKED ISSUE #6769: manifest.json files are blocked on server
### Issue Summary

Chrome supports extension in JSON format.

Described [here](https://developer.chrome.com/extensions/manifest)

I created such file and added to theme. Unfortunately this file is not hosted. Returns 404.

### Steps to Reproduce

1. Create manifest.json in theme root
2. Update theme and reload. See 404 in inspector.

manifest.json should be supported by Ghost as part of theme or generated dynamically by Ghost.

### PR DESCRIPTION
**Pull request by sakulstra**
Allow manifest.json to be served from theme directory. Implemented via whitelist.
- closes #6769 
- added a whitelist function
- added a test against manifest.json

### CODE REVIEW

File: core/server/middleware/static-theme.js [hunk 1]
```diff
@@ -23,7 +29,7 @@ function forwardToExpressStatic(req, res, next) {
 
 function staticTheme() {
     return function blackListStatic(req, res, next) {
```
Comment (kirrg001) [inline core/server/middleware/static-theme.js]: suggestion: rename the function to `blackOrWhitelistStaticFiles` (or something similar)

**Comment by kirrg001** [comment]
@sakulstra Thanks for the PR - if you have time, could you please fix the travis build errors?

File: core/server/middleware/static-theme.js (hunk 1 above)
Comment (sakulstra) [inline core/server/middleware/static-theme.js]: not sure about this, if you want me to i can rename it

Comment (kirrg001) [inline core/server/middleware/static-theme.js]: not important, was just a suggestion. we can leave as is 👍

**Comment by kirrg001** [comment]
LGTM 👍
