### PR TITLE
Fix Select Component

### LINKED ISSUE #6171: Select component raises error on change
Steps to reproduce:

1. Log in as an admin
2. Load a user page for a non-admin user
3. Use the select box to change the user role
4. Click save
4. Reload page

Expected result: User now has their new role

Actual result: Upon selecting a new role with the select box, the following error is generated and the subsequent save does not update the role:

screen shot 2015-12-04 at 16 00 39

### PR DESCRIPTION
**Pull request by syaiful6**
jQuery instance isn't iterable. So we can't really destructuring it. Quick fix will be just use simple syntax. :smile:

closed https://github.com/TryGhost/Ghost/issues/6171

### CODE REVIEW

File: core/client/app/components/gh-select-native.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ export default Component.extend({
 
     actions: {
         change() {
-            let [selectEl] = this.$('select');
+            let selectEl = this.$('select')[0];
```
Comment (kevinansfield) [inline core/client/app/components/gh-select-native.js]: You'll need to disable the `requireArrayDestructuring` jscs rule here for the linting to pass.

File: content/themes/casper [hunk 2]
```diff
@@ -1 +1 @@
-Subproject commit 1c092c7be098bed496eaa2f194a3ae39dd23659d
+Subproject commit ede6b03afad148eadba701bce9e65401d9e034e8
```
Comment (kevinansfield) [inline content/themes/casper]: Can you rebase and ensure that your submodules are up to date or remove this change from the commit?

**Comment by kevinansfield** [comment]
:+1: Fix is good, the commit just needs some cleanup :smile: Could you also update the commit message to match our [commit guidelines](https://github.com/TryGhost/Ghost/wiki/Git-workflow#commit-messages)? Thanks!

**Comment by syaiful6** [comment]
will rebash it, and do some clean up. :smiley:

**Comment by kevinansfield** [comment]
Awesome, thanks for the quick fix-up :smile:
