### PR TITLE
🐛 Ensure sitemap items are valid

### LINKED ISSUE #7186: Internal tags are showing up in sitemap.xml
### Issue Summary

After adding internal tags the tag pages for those tags are listed in yoursite.com/sitemap-tags.xml but will return 404s as they do not have public pages.

### Steps to Reproduce

1. Enable internal tags labs feature
2. Add some internal tags
3. Check http://localhost:2368/sitemap-tags.xml
4. See that the internal tag pages are listed

### Technical details:

* Ghost Version: 0.9.0

### PR DESCRIPTION
**Pull request by ErisDS**
This PR fixes #7186 and also prevents invited users from appearing in the user sitemap and pages from appearing in the post sitemap.

There are a lot of bugs in the sitemap generation code, this fixes the worst ones I could find. The code & tests both need revisiting but that's a bigger job than for today.

closes #7186
- Add a concept of validity to each generator
- Refactor base generator to handle invalid (empty) nodes for both events & the initial generation
- Update the tests a bit, to fix some bugs in the tests
- TODO: this needs a total overhaul :(

### CODE REVIEW

File: core/server/data/xml/sitemap/page-generator.js [hunk 1]
```diff
@@ -26,6 +26,7 @@ _.extend(PageMapGenerator.prototype, {
             context: {
                 internal: true
             },
+            filter: 'visibility:public',
```
Comment (kirrg001) [inline core/server/data/xml/sitemap/page-generator.js]: question:
There is a `homePage` object manually added in line 34, which never fulfils the condition in `validateDatum`.
Can you explain that to me?

File: core/server/data/xml/sitemap/base-generator.js [hunk 2]
```diff
@@ -55,13 +55,18 @@ _.extend(BaseSiteMapGenerator.prototype, {
         // Create all the url elements in JSON
         var self = this,
             nodes;
-        nodes = _.map(data, function (datum) {
+
+        nodes = _.reduce(data, function (nodeArr, datum) {
```
Comment (kirrg001) [inline core/server/data/xml/sitemap/base-generator.js]: question:
i wonder why we need the changes from line 59 till 69, because when asking for `getData`, this function should already return filtered data based on the query.

Comment (ErisDS) [inline core/server/data/xml/sitemap/base-generator.js]: The changes to `getData` are an optimisation - we don't fetch data we know won't get included.

The method `createUrlNodeFromDatum` is called in two ways:

1. after doing `getData` to do an initial load on boot
2. after an event with a model that was updated

The validations ensure that we always filter the data correctly no matter how it is fetched (event or API call).

By adding the validations, we change the method `createUrlNodeFromDatum` so that it can return false, and both places where this is called have been updated.

Comment (ErisDS) [inline core/server/data/xml/sitemap/base-generator.js]: If you prefer we can not add the filters to the getData call, and just rely on the validations.

File: core/server/data/xml/sitemap/page-generator.js (hunk 1 above)
Comment (ErisDS) [inline core/server/data/xml/sitemap/page-generator.js]: Ah whoops, that's a 🐛 . I thought it was added in the base generator and the base generator always returns true for validations. Will fix.

File: core/server/data/xml/sitemap/base-generator.js (hunk 2 above)
Comment (kirrg001) [inline core/server/data/xml/sitemap/base-generator.js]: filtering the data on `getData` makes sense and i would leave as is - it's a faster query to the database. 

my suggestion would be: move `validateDatum ` into `addOrUpdateUrl`.
then it would do: if there is new or updated data, we first check if it's validate based on conditions on the specific generator. if it's valid we call `createUrlNodeFromDatum`. That would mean `createUrlNodeFromDatum` never returns `false`. This function then has just one independent job: create a node.

But you can choose which solution you would like to go with: keep as is or take my suggestion.

File: core/server/data/xml/sitemap/page-generator.js (hunk 1 above)
Comment (kirrg001) [inline core/server/data/xml/sitemap/page-generator.js]: 👍

**Comment by kirrg001** [comment]
tested in the browser: works good 👍

File: core/server/data/xml/sitemap/base-generator.js (hunk 2 above)
Comment (ErisDS) [inline core/server/data/xml/sitemap/base-generator.js]: I prefer to keep it the way it is, so that the validator ensures the content is correct even if the filter breaks or is not correct anymore. E.g. there's a fallback.

Long term, I'd like to replace this entire thing 😉

**Comment by ErisDS** [comment]
Have fixed the issue with the homepage disappearing, and updated the tests some more.

File: core/server/data/xml/sitemap/base-generator.js [hunk 3]
```diff
@@ -44,6 +44,7 @@ _.extend(BaseSiteMapGenerator.prototype, {
 
         // Load all data
         return this.getData().then(function (data) {
+            console.log('got data', data);
```
Comment (kirrg001) [inline core/server/data/xml/sitemap/base-generator.js]: 😱

File: core/server/data/xml/sitemap/base-generator.js (hunk 2 above)
Comment (kirrg001) [inline core/server/data/xml/sitemap/base-generator.js]: ja sure, i'm fine with that 👍

File: core/server/data/xml/sitemap/base-generator.js (hunk 3 above)
Comment (ErisDS) [inline core/server/data/xml/sitemap/base-generator.js]: 😂

File: core/server/api/posts.js [hunk 4]
```diff
@@ -221,7 +221,7 @@ posts = {
                 fetchOpts = _.defaults({require: true, columns: 'id'}, options);
 
             return Post.findOne(data, fetchOpts).then(function (post) {
-                return post.destroy(options).return(null);
+                return Post.destroy(options).return(null);
```
Comment (ErisDS) [inline core/server/api/posts.js]: This. This was the culprit for why posts weren't getting removed from the sitemap. This is causing the bookshelf `destroy` method instead of the one defined in models/base/index. The event didn't have the model, and so the `unpublished` event wasn't triggered.
