### PR TITLE
🐛  config.theme.timezone must not be overwritten

### LINKED ISSUE #7182: Date helper is returning current dates with wrong timezone
Date helper is returning current dates with wrong timezone, due to options.data.blog.timezone returning default timezone ('Etc/UTC'), even if it is changed in settings panel.

### Issue Summary

Inside the date helper, using console.log on options.data.blog.timezone, it is possible to see that 'Etc/UTC' is being returned as the blog timezone, even if another timezone is set.

### Technical details:

* Ghost Version: 0.9.0
* Node Version: 4.4.7
* Browser/OS: Chrome/OSX
* Database: SQLite

### PR DESCRIPTION
**Pull request by aileen**
closes #7182

When calling `config.set()` in the settings api, we want to set the active timezone of the blog to make it available in our `settingsCache`. But because the `theme` object in the `set` prototype was already set to `Etc/UTC` as default, the `_.merge` function would always overwrite our `activeTimezone` with the default value.

This PR changes the code in the way, that we always set 'Etc/UTC' for the timezone as default, _until_ we fetched our settings and therefore the `activeTimezone` setting, so we can overwrite it.

This issue had not only influence on the date helper, but everywhere in our codebase, where we rely on reading the `timezone` from our config, instead of our settings. The `{{@blog.timezone}}` helper reflected that quiet well, as it would always show `Etc/UTC`

### CODE REVIEW

**Comment by AileenCGN** [comment]
Ready for review and merge 🎉

File: core/server/config/index.js [hunk 1]
```diff
@@ -118,6 +118,15 @@ ConfigManager.prototype.set = function (config) {
         this._config.theme.navigation = config.theme.navigation;
     }
 
+    // Special case for theme.timezone, which should be overridden not merged
+    if (config && config.theme && config.theme.timezone) {
+        this._config.theme.timezone = config.theme.timezone;
+    } else if (this._config && this._config.theme) {
```
Comment (kirrg001) [inline core/server/config/index.js]: With this condition you achieve having `this._config.theme.timezone` undefined.
The `ConfigManager.set` fn is called twice and that's why the logic here works by coincidence.
