### PR TITLE
Use HTTP status 204 on deletes

### LINKED ISSUE #2871: [Ember.js] [API] status code for HTTP API delete responses
In working on #2849, I've run into an issue where Ember wants to call `.set()` operations on post model objects after they have been deleted (i.e., had `destroyRecord()` called on them), and this causes Ember to throw exceptions.

I believe this is because Ghost is currently returning status `200` and the JSON for the object in response to `DELETE` requests to the HTTP API.  According to http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.7/ I feel like we should be returning `204` with an empty response body.

I've changed the API response locally and confirmed that everything works as expected with a `204` response.

Thoughts?

(refs #2187)

### PR DESCRIPTION
**Pull request by jaswilli**
This is built on #6613, so once that PR is resolved this diff will clean itself up.

Closes #2871.
- Refactor API HTTP handlers to send `204` status on deletes.
- Adjust tests to check for `204` status and empty response bodies.
- Add integration tests for destroy post.
- Remove `deleteRecord` override in ember-data adapter.
- Adjust ember-mirage to send the correct response on deletes.

### CODE REVIEW

File: core/server/api/index.js [hunk 1]
```diff
@@ -209,6 +209,10 @@ http = function http(apiMethod) {
             // Add X-Cache-Invalidate, Location, and Content-Disposition headers
             return addHeaders(apiMethod, req, res, (response || {}));
         }).then(function then(response) {
+            if (req.method === 'DELETE') {
+                return res.status(204).end();
```
Comment (ErisDS) [inline core/server/api/index.js]: This could use [sendStatus](http://expressjs.com/en/4x/api.html#res.sendStatus), I think?

**Comment by ErisDS** [comment]
One minor comment, but the API side of this LGTM. Much simpler and easier to read now :+1:

**Comment by kevinansfield** [comment]
Client side is :+1: too

File: core/server/api/index.js (hunk 1 above)
Comment (jaswilli) [inline core/server/api/index.js]: It looks like `sendStatus` puts the status code in the response body? If true that would cause problems for a `204`.

Comment (ErisDS) [inline core/server/api/index.js]: Good point, well made :+1:

Comment (jaswilli) [inline core/server/api/index.js]: I'm at a computer now so looking at this a little more closely. If you use `sendStatus`, the body does get set to `No Content`, but later on `res.send` checks for 204s and strips the body.

So I'm torn between leaving it as and explicitly leaving the response body empty, or using `sendStatus`, which sets and then strips the body later (which seems a little silly).

If you have a strong preference to `sendStatus` I'm cool with changing it, otherwise maybe I'll just leave it as is?

Comment (ErisDS) [inline core/server/api/index.js]: I think the explicit is better :+1:
