### PR TITLE
🐛 Fixed error in error template hiding errors

### LINKED ISSUE #8808: Failed to lookup view "error" in views directory "/path/to/ghost/views"
Originally reported in: https://github.com/TryGhost/Ghost-CLI/issues/386

This is a horribly nuanced bug, and mostly affects production mode.

Case 1: active theme has a fatal error, start in production mode, try to request the home page
Case 2: don't build any production assets, trying to access /ghost/
Case 3: make an image error? Not confirmed yet

This is to do with how our loading of handlebars was refactored in 1.0. There are a couple of edge cases I've missed. I am working on resolving them.

### PR DESCRIPTION
**Pull request by ErisDS**
closes #8808

Problem:
- In certain cases, particularly in production mode, errors would be hidden
- E.g. fatal theme errors could not be seen, users instead saw "Failed to lookup view 'error' in views directory"
- This is extremely unhelpful, particularly for people upgrading from 1.0.0 or 1.0.1 where the disqus rule was added
afterwards and modified casper would error
Solution:
- Ensure that we properly setup handlebars when we throw an error
- If engines is not set, set all the view engine related properties

### CODE REVIEW

File: core/server/middleware/error-handler.js [hunk 1]
```diff
@@ -81,6 +82,8 @@ _private.HTMLErrorRenderer = function HTMLErrorRender(err, req, res, /*jshint un
     // This ensures that no matter what res.render will work here
     if (_.isEmpty(req.app.engines)) {
         req.app.engine('hbs', _private.createHbsEngine());
+        req.app.set('view engine', 'hbs');
+        req.app.set('views', config.get('paths').defaultViews);
```
Comment (kirrg001) [inline core/server/middleware/error-handler.js]: Unrelated to this line.

If we would add `message: err.message` to https://github.com/TryGhost/Ghost/pull/8832/files#diff-6b41d6f0ef148f7d202931a87d5c4130R37, this would prefers the inherited error message. 

gaga1
gaga2

Comment (kirrg001) [inline core/server/middleware/error-handler.js]: We agreed on keeping it like it is, because there are other cases where we want to show `Resource could not be found`. 

Here is how i tested this use case:
- I've removed the `admin/views` html files and restarted Ghost
- Then i have added the inheritance message property to the html error handler to get the underlying error message
