### PR TITLE
Ensure static page edit route redirects to editor

### LINKED ISSUE #7168: Adding 'edit' to the end of a URL results in a 404 on static pages.
### Issue Summary

Adding edit/ to the end of a URL for a static page results in a 404.

### Steps to Reproduce

1. Visit the URL of a static page.
2. Add edit/ to the end of the URL.
3. Observe a 404.

I would expect this to open the editor for the appropriate page. 

### Technical details:

* Ghost Version: 0.9.0
* Node Version: v0.10.24
* Browser/OS: Chrome Version 52.0.2743.82 m / Windows 10 x64

### PR DESCRIPTION
**Pull request by acburdine**
closes #7168
- check for edit route before checking for slug
- add tests

### CODE REVIEW

File: core/server/controllers/frontend/index.js [hunk 1]
```diff
@@ -67,7 +67,10 @@ frontendControllers = {
             }
 
             // CASE: we only support /:slug format for pages
-            if (post.page && post.url !== req.path) {
+            // However, given that a url with `/edit/` appended is different
+            // than the post url, we must remove `/edit/` from the url if it
+            // is an edit url.
+            if (post.page && post.url !== ((lookup.isEditURL) ? req.path.replace(/edit\/$/, '') : req.path)) {
```
Comment (kirrg001) [inline core/server/controllers/frontend/index.js]: I wonder why we can't switch the calling order?
`lookup.isEditURL` with `post.page && post.url !== req.path`. 
That should work in my opinion?

Comment (acburdine) [inline core/server/controllers/frontend/index.js]: That was my initial approach. Unfortunately though - that means that in theory if a user had permalinks turned on, both `blog.com/2016/08/05/page-name/edit` and `blog.com/page-name/edit` would work.

There was an explicit unit test in there already for that case that failed with just switching the order - so I went with this method :)

Comment (kirrg001) [inline core/server/controllers/frontend/index.js]: Yes so true, so i think the problem sits in `post-lookup.js`, because it should only detect `isEditURL` if static page has no date permalink.

Comment (acburdine) [inline core/server/controllers/frontend/index.js]: Honestly I would agree, but I don't think it's super simple to do that.

In the [post lookup method](https://github.com/TryGhost/Ghost/blob/master/core/server/controllers/frontend/post-lookup.js#L26) - we compare the url from the request to the `config.theme.permalinks` value - and there are two things that can happen:

1. Date permalinks are turned off - and a user navigates to the page url. The postLookup function would match the post permalink pattern, because it's identical to the page lookup pattern
2. Date permalinks are turned on - and a user navigates to the page url with a date prepended. This would still match the post lookup pattern, leaving no way to determine if the user is looking up a post or a page.

Now, we can do the comparison after the `api.posts.read` call - which knows whether or not the post is a page or not; however, in order to determine fully if the user is accessing it via the correct path, we'd have to know somehow whether the value of `config.theme.permalinks` had the date in it, leading to more complexity, especially if we end up supporting custom permalinks at some point.

**Comment by acburdine** [comment]
@kirrg001 ready for review (again) 😄
