### PR TITLE
Delete associated roles_users rows when user is destroyed

### LINKED ISSUE #8843: When you delete a user, the roles ain't cleaned
### Issue Summary

When you delete a user, the roles ain't cleaned

### Steps to Reproduce

1. Delete a user;
2. And observe:

```
mysql> select users.id, users.name, roles.name from roles join roles_users on roles_users.role_id=roles.id left join users on users.id = roles_users.user_id;
+--------------------------+----------------+---------------+
| id                       | name           | name          |
+--------------------------+----------------+---------------+
| 1                        | Adrien Giboire | Owner         |
| 5984be102f295b5ab0bef447 | Adrien Giboire | Administrator |
| NULL                     | NULL           | Author        |
+--------------------------+----------------+---------------+
```

### Technical details:

* Ghost Version: `1.5.0`
* Node Version: `6.11.1`
* Database: `mysql  Ver 14.14 Distrib 5.7.19`

### PR DESCRIPTION
**Pull request by dexterleng**
Fixes #8843.

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `npm test`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by kirrg001** [comment]
Thanks will review asap 😇

File: core/server/api/v2/users.js [hunk 1]
```diff
@@ -126,7 +126,11 @@ module.exports = {
                 return Promise.all([
                     models.Accesstoken.destroyByUser(frame.options),
                     models.Refreshtoken.destroyByUser(frame.options),
-                    models.Post.destroyByAuthor(frame.options)
+                    models.Post.destroyByAuthor(frame.options),
+                    frame.options.transacting('roles_users')
```
Comment (kirrg001) [inline core/server/api/v2/users.js]: Thanks for your PR 👍 This works, but this is not really a bookshelf/ORM approach.

Do you mind if i push a commit to this PR?
Or let me know if you want to change your code, then i can help/advice you.

**Background: (in case you are curious):**
The user model should destroy it's relation automatically. Otherwise, any unit who calls `User.destroy` needs to handle removing the relations.
