### PR TITLE
Fixed import for tags without slugs belonging to a post

### LINKED ISSUE #10785: Importer: multiple relationships not handled if objects don't have slugs
Note: This is a regression in behaviour, as a result of the importer refactor over a year ago. Noone else seems to have noticed, so it's not urgent, but we should consider if this can/should be fixed, or if the docs should be updated. I'd lean towards the former, it's quite the gotcha!

## Summary

If you attempt to run an import with a bunch of posts with related tags/authors, where the tags or authors in the import file don't have a slug, the importer will not import all the relations. It will only import the first related item.

Individual tags and authors are imported correctly.
Individual posts are imported correctly.
Associations between posts and items without a slug are silently lost, without error or warning.

This is due to this line:

https://github.com/TryGhost/Ghost/blob/d1e3205569f11fcb0d9867dd68de781478c4c7f6/core/server/data/importer/importers/data/posts.js#L111

This is where we try to look up items from the  import file, and match them to the object that was actually imported (the ids will be different). This line assumes it can match on slug. If the import file didn't have a slug, this will look for an originalSlug (which will be undefined) that matches the slug from the import file (which is also undefined).

This line (_.find) will always return the first item.

Therefore, in [these lines](https://github.com/TryGhost/Ghost/blob/d1e3205569f11fcb0d9867dd68de781478c4c7f6/core/server/data/importer/importers/data/posts.js#L136-L139) we go from having all references, to all references pointing at the same, first tag.

### To Reproduce

1. Try importing this file, in which tags don't have slugs https://gist.github.com/ErisDS/10fed8d3df18512598bca9d9535d2152
2. After importing, notice all tags are present
3. See that the post "example post" only has the tag "A Tag" associated with it, instead of all 4 tags
4. See that the post "second post" has the tag "A Tag" associated with it, but it should be "#Internal"

There is no expectation that the import file must contain slugs for all objects: https://docs.ghost.org/api/migration/. Only IDs and a name/title.

### Technical details:

* Ghost Version: master

### PR DESCRIPTION
**Pull request by naz**
closes #10785

The change adds a fallback to use the original `id` property of imported object when handling relations, this was ignored previously. The main change here was around `beforeImport` method in the Importer base class, so that `id` property substitution is trackable.

### CODE REVIEW

File: core/test/regression/importer/importer_spec.js [hunk 1]
```diff
@@ -809,6 +809,52 @@ describe('Integration: Importer', function () {
                 });
         });
 
+        it('can handle related tags with missing optional fields', function () {
```
Comment (allouis) [inline core/test/regression/importer/importer_spec.js]: IMO this should at least mention that the slug field is missing _or_ maybe be explicit about what the missing optional fields are.

Even if you did like

```js
exportData.data.tags[0] = testUtils.DataGenerator.forKnex.createTag();
delete exportData.data.tags[0].slug;
```

File: core/server/data/importer/importers/data/posts.js [hunk 2]
```diff
@@ -100,7 +100,13 @@ class PostsImporter extends BaseImporter {
 
                 // CASE: search through imported data.
                 // EDGE CASE: uppercase tag slug was imported and auto modified
-                let importedObject = _.find(this.requiredImportedData[tableName], {originalSlug: objectInFile.slug});
+                let importedObject = null;
+
+                if (objectInFile.slug) {
+                    importedObject = _.find(this.requiredImportedData[tableName], {originalSlug: objectInFile.slug});
+                } else {
+                    importedObject = _.find(this.requiredImportedData[tableName], {originalId: objectInFile.id});
```
Comment (allouis) [inline core/server/data/importer/importers/data/posts.js]: Do we need to check for the existence of `objectInFile.id`? 

I noticed above that the `originalIdMap` doesn't necessarily contain an entry for every id - just trying to work out if there's an edge we're missing here?

**Review by allouis — COMMENTED** [review]
Overall changes seem to make sense, just come questions/comments about edge case and explicitness in tests :+1:

File: core/test/regression/importer/importer_spec.js (hunk 1 above)
Comment (gargol) [reply core/test/regression/importer/importer_spec.js]: I like this idea of how explicit deleting a field is! 

Tried out this approach and concluded it generates too much noise because you'd need to:
```
delete exportData.data.tags[0].slug;
delete exportData.data.tags[0].description;
// and so on for each optional field
```

Opted into leaving a comment about 'name' field being the only required field to handle the import correctly.

File: core/server/data/importer/importers/data/posts.js (hunk 2 above)
Comment (gargol) [reply core/server/data/importer/importers/data/posts.js]: The `objectInFile.id` is always there because of [this bit](https://github.com/TryGhost/Ghost/pull/10917/files#diff-f41262b74e0c309d6ef623f67e2dd79eR96). But you are right, making it `else if (objectInFile.id)` makes it proof to accidental ` === undefined` comparisons in case id assigning code changes in the future :+1:

Comment (allouis) [reply core/server/data/importer/importers/data/posts.js]: Aaaah I see! Yup that makes sense :relaxed: 

One more thing, what is the reason to attempt to match on slug first? Could we just always match on the id and remove the conditional?

Comment (gargol) [reply core/server/data/importer/importers/data/posts.js]: Very good point! Was thinking of slug matching as a fallback, but after rereading the previous statement there's no point in keeping it as the `originalId` will always be accessible :bulb:

Comment (allouis) [reply core/server/data/importer/importers/data/posts.js]: :dancer: !!

**Review by allouis — APPROVED** [review]
You can probably remove a few `if` statements now if you want - but up to you - merge at will

**Comment by gargol** [comment]
Leaving the `if` for the reason mentioned in the [comments](https://github.com/TryGhost/Ghost/pull/10917#discussion_r303794176):
> if (objectInFile.id) makes it proof to accidental === undefined comparisons in case id assigning code changes in the future +1

:ship:

**Comment by allouis** [comment]
Good call :tada:
