### PR TITLE
🐛  Fixed known filter limitations

### LINKED ISSUE #10108: Better error handling for incorrect sql
If you pass a wrong GQL/NQL filter, Ghost should catch this error and return a proper bad request error.

The error handling should probably happen in the model layer.

e.g. you send an invalid filter syntax, you get a 500

Ghost :master

### PR DESCRIPTION
**Pull request by kirrg001**
refs #10105, closes #10108

## Tasks

- [x] NQL must forward relation config
- [x] use NQL tarball for now
- [x] remove preProcessFilters in filter plugin
- [x] remove preProcessFilters in filter plugin
- [x] check `order = `(SELECT count(*) FROM posts_tags WHERE post_id = posts.id) DESC, ${order}`;` is tested well
- [x] change NQL API
- [x] tag_spec count test
- [x] double protect `extraFilters` fn in Ghost (check public context!) -> not needed, see commit
- [x] double check if we have .skip tests because of older GQL bugs
- [x] test members cases
- [x] QA

### CODE REVIEW

File: core/server/models/plugins/filter.js [hunk 1]
```diff
@@ -191,36 +193,33 @@ filter = function filter(Bookshelf) {
...
+         *
+         * - release nql with latest mongo-knex
+         * - NQL must forward options to mongo-knex
          */
         applyDefaultAndCustomFilters: function applyDefaultAndCustomFilters(options) {
-            var self = this;
-
-            // @TODO figure out a better place/way to trigger loading filters
-            if (!this._filters) {
-                this.fetchAndCombineFilters(options);
```
Comment (gargol) [inline core/server/models/plugins/filter.js]: I think we might still need this or alternative method to combine all the filters together :thinking: ?

Comment (kirrg001) [reply core/server/models/plugins/filter.js]: yeah 100%.

no need to touch or refactor existing functions of this filter plugin?
requirement: we need filter combination. the rest depends on the utility.

File: core/test/functional/api/v2/content/posts_spec.js [hunk 2]
```diff
@@ -98,8 +98,8 @@ describe('Posts', function () {
             });
     });
 
-    it('browse posts with basic filters', function (done) {
-        request.get(localUtils.API.getApiQuery(`posts/?key=${validKey}&filter=tag:kitchen-sink,featured:true&include=tags`))
+    it.only('browse posts with basic filters', function (done) {
+        request.get(localUtils.API.getApiQuery(`posts/?key=${validKey}&filter=tags.slug:kitchen-sink,featured:true&include=tags`))
```
Comment (kirrg001) [inline core/test/functional/api/v2/content/posts_spec.js]: Need to revert the alias change as soon as we support aliases. But later...

File: core/server/models/plugins/filter.js [hunk 3]
```diff
@@ -191,36 +193,31 @@ filter = function filter(Bookshelf) {
...
+            const defaultFilters = this.enforcedFilters(options);
+            const enforcedFilters = this.enforcedFilters(options);
+
+            debug('custom', customFilter);
+            debug('default', defaultFilters);
+            debug('enforced', enforcedFilters);
+
+            if (customFilter) {
+                this.query((qb) => {
+                    nql(customFilter, {relations: {tags: {
```
Comment (kirrg001) [inline core/server/models/plugins/filter.js]: We will sort this out later. Can stay like this for now. No priority, as long as it works.

**Comment by kirrg001** [comment]
@gargol Could you pls work on getting rid of the functions [`preProcessFilters`](https://github.com/TryGhost/Ghost/blob/master/core/server/models/plugins/filter.js#L89) and [`postProcessFilters`](https://github.com/TryGhost/Ghost/blob/master/core/server/models/plugins/filter.js#L119).

The goal should be to enable existing test cases which used these two filters in the past. If you can't find a test case, add one for now as functional test.

The test cases will be restricted by the functionality of [mongo-knex.](https://github.com/NexesJS/mongo-knex/commits/master). 

I will work on finishing up https://github.com/NexesJS/mongo-knex/pull/16.

**Comment by gargol** [comment]
Sure, starting on preProcessFilters and postProcessFilters now.

File: core/server/models/plugins/filter.js [hunk 4]
```diff
@@ -1,92 +1,165 @@
...
+        let processed = filters;
+
+        aliases.forEach((alias) => {
+            const {key, replacement, filter} = alias;
+            if (processed.match(key)) {
+                // matches:
+                // - 'key:customFilter'
+                // - 'key:[customFilter]'
+                // - 'key:[custom,filter]'
+                const keyGroupMatch = `${key}:\\s?(\\w+|\\[(\\w+|,)+\\])`;
```
Comment (kirrg001) [inline core/server/models/plugins/filter.js]: The regex will not work for e.g. `primary_author:joe-blog`

We need e.g.
```
`${key}:\\s?([a-zA-Z\\-]+|\\[([a-zA-Z\\-]+|,)+\\])
```

Comment (gargol) [reply core/server/models/plugins/filter.js]: good. point. also looking at it with a fresh eye, need to allow for negation operator as well

File: core/server/models/plugins/filter.js [hunk 5]
```diff
@@ -1,92 +1,175 @@
...
-        // Merge custom filter options into a single set of statements
-        custom = gql.json.mergeStatements.apply(this, custom);
+        const primaryKeys = filterUtils.getFilterKeys(primary);
+        let reducedFilter = secondary;
 
-        // if there is no enforced or default statements, return just the custom statements;
-        if (!enforced && !defaults) {
-            return custom;
+        primaryKeys.forEach((key) => {
+            if (reducedFilter.match(key)) {
```
Comment (kirrg001) [inline core/server/models/plugins/filter.js]: i think we have to match `key:`, otherwise if you add an alias "tag" -> "tags.slug", it would match "tags".

Comment (gargol) [reply core/server/models/plugins/filter.js]: :+1: fa3517b6d7c133d4eb12d7bf845f0f073ab1ad5d

File: core/server/models/plugins/filter.js [hunk 6]
```diff
@@ -1,92 +1,174 @@
...
+    processFilters: (filter, aliases) => {
+        let processed = filter;
+
+        aliases.forEach((alias) => {
+            if (processed.match(`${alias.key}:`)) {
+                // matches:
+                // - 'key:customFilter'
+                // - 'key:[customFilter]'
+                // - 'key:[custom,filter]'
+                const keyGroupMatch = `${alias.key}:\\s?(\\w+|\\[(\\w+|,)+\\])`;
```
Comment (kirrg001) [inline core/server/models/plugins/filter.js]: Could you pls push the new regex? :)
I am working on a core/test/functional/api/v2/content/posts_spec.js, it passes 99%

File: core/server/models/plugins/filter.js (hunk 5 above)
Comment (kirrg001) [reply core/server/models/plugins/filter.js]: 👍 Just realised, i added the comment on the wrong match 🤣 they look so similar

File: core/server/models/plugins/filter.js (hunk 6 above)
Comment (gargol) [reply core/server/models/plugins/filter.js]: Pushed it out :+1:

File: core/server/models/post.js [hunk 7]
```diff
@@ -587,12 +587,12 @@ Post = ghostBookshelf.Model.extend({
...
         // CASE: if the filter contains an `IN` operator, we should return the posts first, which match both tags
         if (options.filter && options.filter.match(/(tags|tag):\s?\[.*\]/)) {
-            order = `count(tags.id) DESC, ${order}`;
+            order = `(SELECT count(*) FROM posts_tags WHERE post_id = posts.id) DESC, ${order}`;
         }
 
         // CASE: if the filter contains an `IN` operator, we should return the posts first, which match both authors
         if (options.filter && options.filter.match(/(authors|author):\s?\[.*\]/)) {
-            order = `count(authors.id) DESC, ${order}`;
+            order = `(SELECT count(*) FROM posts_authors WHERE post_id = posts.id) DESC, ${order}`;
```
Comment (kirrg001) [inline core/server/models/post.js]: We need a TODO here if this SELECT works.

mongo-knex no longer joins with e.g. authors table, so we dont have access to authors.id.
AND even if mongo-knex would still join, then it would tie mongo-knex and Ghost together, because Ghost knows that mongo-knex will JOIN 👻 So raw SQL is fine here? needs investigation.

This is a little lower priority for now, because it only kicks in if you use tags:[X,Y].
But we should look at it soon.

Comment (kirrg001) [reply core/server/models/post.js]: @gargol from our sync :)

File: core/test/functional/api/v0.1/posts_spec.js [hunk 8]
```diff
@@ -298,6 +298,98 @@ describe('Post API', function () {
...
+                        testUtils.API.checkResponse(jsonResponse, 'posts');
+                        jsonResponse.posts.should.have.length(4);
+                        testUtils.API.checkResponse(jsonResponse.posts[0], 'post');
+                        testUtils.API.checkResponse(jsonResponse.meta.pagination, 'pagination');
+                        jsonResponse.posts[0].slug.should.equal('not-so-short-bit-complex');
+                        done();
+                    });
+            });
+
+            it('can retrieve pages filtered by primary_tag', function (done) {
```
Comment (kirrg001) [inline core/test/functional/api/v0.1/posts_spec.js]: @gargol from sync: test does not pass :)

File: core/server/models/plugins/filter.js [hunk 9]
```diff
@@ -1,210 +1,226 @@
...
+        tags: {
+            tableName: 'tags',
+            type: 'manyToMany',
+            join_table: 'posts_tags',
+            join_from: 'post_id',
+            join_to: 'tag_id'
+        },
+        authors: {
+            tableName: 'users',
+            tableNameAs: 'authors',
```
Comment (kirrg001) [inline core/server/models/plugins/filter.js]: > tableNameAs: 'authors',

this can be removed. left over from testing

File: core/server/models/plugins/filter.js [hunk 10]
```diff
@@ -1,210 +1,226 @@
...
+            debug('filter', filter);
 
-        /**
-         * ## Apply Filters
-         * Method which makes the necessary query builder calls (through knex) for the filters set
-         * on this model instance
-         * @param {Object} options
-         * @returns {Bookshelf.Model}
-         */
-        applyDefaultAndCustomFilters: function applyDefaultAndCustomFilters(options) {
```
Comment (kirrg001) [inline core/server/models/plugins/filter.js]: Sexy Alarm: Maybe we can later rename `applyDefaultAndCustomFilters` to simply `applyFilters`.

File: core/server/models/post.js (hunk 7 above)
Comment (kirrg001) [reply core/server/models/post.js]: @gargol I am leaving soon. Would be cool if you could add a code comment :) Thanks

File: core/test/unit/models/tag_spec.js [hunk 11]
```diff
@@ -16,7 +16,8 @@ describe('Unit: models/tag', function () {
         sandbox.restore();
     });
 
-    describe('SQL', function () {
+    // @NOTE: need to be regenerated once functional tests are passing
+    describe.skip('SQL', function () {
```
Comment (kirrg001) [inline core/test/unit/models/tag_spec.js]: `filter=count.posts:>=X` was never supported.

It was resulting in

> message: "select count(distinct tags.id) as aggregate from `tags` where `count`.`posts` >= 2 - ER_BAD_FIELD_ERROR: Unknown column 'count.posts' in 'where clause'",

Because this is a unit test and it only captures the generated SQL statement, it does succeed. Otherwise, the db would throw an error.

Only `include=count.posts` is supported.

Why is now throwing an error?
Because mongo-knex currently throws an error and has a logic bug [here](https://github.com/NexesJS/mongo-knex/blob/master/lib/convertor.js#L75). If we can't detect a relation, we need to assume that it's a column on the destination table. 

I will update mongo-knex and then update or remove this test. Need to see if this test has any value.

Comment (gargol) [reply core/test/unit/models/tag_spec.js]: Sounds perfect. We've put that error handling there as an experiment anyway, this case clearly shows why we should not have it there :)

File: core/test/unit/models/plugins/filter_spec.js [hunk 12]
```diff
@@ -24,639 +24,778 @@ describe('Filter', function () {
...
+                        defaults: {page:false},
+                        custom: {tag:'photo'},
+                    };
+                    const output = {$and: [
+                        {$and: [
+                            {status:'published'},
+                            {tag:'photo'}
+                        ]},
+                        {page:false}
+                    ]};
```
[the remark this answers is not in the document]
Comment (gargol) [reply core/test/unit/models/plugins/filter_spec.js]: Good observation. At the moment the grouping logic is very simple and doesn't recognize if the group would produce an equivalent result like in this example. I see it more like an optimization that could be done later. But maybe there's some use case I'm missing? :thinking:

[the remark this answers is not in the document]
Comment (kirrg001) [reply core/test/unit/models/plugins/filter_spec.js]: I have not really looked in detail at the logic. IMO the logic does too many $and connections. And i think it might be hard to detect this on runtime, because you don't know the values of the filters.

I thought the logic works like this:

You receive:

- enforced (0)
- custom (1)
- default (2)


You reject any key of `default` which is in all the other filters.
You repeat that for custom.

Now you combine all three together ($and: [enforced, custom, default]).

This would also simplify the logic a lot and we would only connect $and once.

[the remark this answers is not in the document]
Comment (ErisDS) [reply core/test/unit/models/plugins/filter_spec.js]: There is a big discussion of this logic here: https://github.com/NexesJS/nql/issues/2#issuecomment-442038597

IMO you have to work through the cascade to get the right logic. 

Having outer AND statements ensures safety. We can look to optimise this later, but IMO this should not block shipping as the current impl is safer, even if it is not optimal.

File: core/test/unit/models/post_spec.js [hunk 13]
```diff
@@ -182,15 +182,15 @@ describe('Unit: models/post', function () {
...
+                    queries[1].sql.should.eql('select `posts`.* from `posts` where ((`posts`.`id` in (select `posts_authors`.`post_id` from `posts_authors` inner join `users` as `authors` on `authors`.`id` = `posts_authors`.`author_id` and `posts_authors`.`sort_order` = 0 where `authors`.`slug` = ? and `authors`.`visibility` = ?)) and (`posts`.`page` = ? and `posts`.`status` = ?)) order by CASE WHEN posts.status = \'scheduled\' THEN 1 WHEN posts.status = \'draft\' THEN 2 ELSE 3 END ASC,CASE WHEN posts.status != \'draft\' THEN posts.published_at END DESC,posts.updated_at DESC,posts.id DESC limit ?');
```
Comment (kirrg001) [inline core/test/unit/models/post_spec.js]: These were just replacements of `IN` with `=`

**Comment by gargol** [comment]
It's :green_heart: !

**Comment by kirrg001** [comment]
🤣

**Comment by kirrg001** [comment]
Travis is failing because of a random failure, tracked in #7470 again 🤨
Will merge anyway!
